<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Sesión 4 Estadística Inferencial: Introducción | Estadística para el Análisis Político I</title>
  <meta name="description" content="Sesión 4 Estadística Inferencial: Introducción | Estadística para el Análisis Político I" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Sesión 4 Estadística Inferencial: Introducción | Estadística para el Análisis Político I" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Sesión 4 Estadística Inferencial: Introducción | Estadística para el Análisis Político I" />
  
  
  

<meta name="author" content="Docente: Christian Chiroque Ruiz" />


<meta name="date" content="2023-09-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="visualización-de-datos-con-ggplot2.html"/>
<link rel="next" href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística AP I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción a Estadística con R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#estadística-los-fundamentos"><i class="fa fa-check"></i><b>1.1</b> Estadística: los fundamentos</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#unidad-de-análisis"><i class="fa fa-check"></i><b>1.1.1</b> Unidad de análisis</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#tipos-de-variables-y-escalas-de-medición"><i class="fa fa-check"></i><b>1.1.2</b> Tipos de variables y escalas de medición</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#r-los-fundamentos"><i class="fa fa-check"></i><b>1.2</b> R: los fundamentos</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#por-qué-r"><i class="fa fa-check"></i><b>1.2.1</b> ¿Por qué R?</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#poo"><i class="fa fa-check"></i><b>1.2.2</b> POO</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#los-objetos"><i class="fa fa-check"></i><b>1.2.3</b> Los objetos</a></li>
<li class="chapter" data-level="1.2.4" data-path="index.html"><a href="index.html#los-vectores"><i class="fa fa-check"></i><b>1.2.4</b> Los vectores</a></li>
<li class="chapter" data-level="1.2.5" data-path="index.html"><a href="index.html#los-factores"><i class="fa fa-check"></i><b>1.2.5</b> Los factores</a></li>
<li class="chapter" data-level="1.2.6" data-path="index.html"><a href="index.html#data-frames"><i class="fa fa-check"></i><b>1.2.6</b> Data frames</a></li>
<li class="chapter" data-level="1.2.7" data-path="index.html"><a href="index.html#índices"><i class="fa fa-check"></i><b>1.2.7</b> Índices</a></li>
<li class="chapter" data-level="1.2.8" data-path="index.html"><a href="index.html#nuestras-herramientas-paquetes-y-funciones"><i class="fa fa-check"></i><b>1.2.8</b> Nuestras herramientas: Paquetes y funciones</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#importación-y-exploración-de-datos"><i class="fa fa-check"></i><b>1.3</b> Importación y exploración de datos</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#verificar-el-tipo-de-variable"><i class="fa fa-check"></i><b>1.3.1</b> Verificar el tipo de variable</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html"><i class="fa fa-check"></i><b>2</b> Análisis exploratorio de datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#estadísticos-descriptivos"><i class="fa fa-check"></i><b>2.1</b> Estadísticos descriptivos</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#tendencia-central"><i class="fa fa-check"></i><b>2.1.1</b> Tendencia central</a></li>
<li class="chapter" data-level="2.1.2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#dispersión"><i class="fa fa-check"></i><b>2.1.2</b> Dispersión</a></li>
<li class="chapter" data-level="2.1.3" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#posición"><i class="fa fa-check"></i><b>2.1.3</b> Posición</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#manipulación-de-tablas"><i class="fa fa-check"></i><b>2.2</b> Manipulación de tablas</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#filtrar-filas"><i class="fa fa-check"></i><b>2.2.1</b> Filtrar filas</a></li>
<li class="chapter" data-level="2.2.2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#seleccionar-columnas"><i class="fa fa-check"></i><b>2.2.2</b> Seleccionar columnas</a></li>
<li class="chapter" data-level="2.2.3" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#crear-nuevas-variables"><i class="fa fa-check"></i><b>2.2.3</b> Crear nuevas variables</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#ejercicios"><i class="fa fa-check"></i><b>2.3</b> Ejercicios</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#ejercicio-1"><i class="fa fa-check"></i><b>2.3.1</b> Ejercicio 1</a></li>
<li class="chapter" data-level="2.3.2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#ejercicio-2"><i class="fa fa-check"></i><b>2.3.2</b> Ejercicio 2</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#preparación"><i class="fa fa-check"></i><b>2.4</b> Preparación</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#entorno-de-trabajo"><i class="fa fa-check"></i><b>2.4.1</b> Entorno de trabajo</a></li>
<li class="chapter" data-level="2.4.2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#paquetes-a-utilizar"><i class="fa fa-check"></i><b>2.4.2</b> Paquetes a utilizar</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#base-de-datos"><i class="fa fa-check"></i><b>2.5</b> Base de datos</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#importación"><i class="fa fa-check"></i><b>2.5.1</b> Importación</a></li>
<li class="chapter" data-level="2.5.2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#verificar-el-tipo-de-variable-1"><i class="fa fa-check"></i><b>2.5.2</b> Verificar el tipo de variable</a></li>
<li class="chapter" data-level="2.5.3" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#creación-de-subset"><i class="fa fa-check"></i><b>2.5.3</b> Creación de subset</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#estadísticos-de-tendencia-central"><i class="fa fa-check"></i><b>2.6</b> Estadísticos de tendencia central</a></li>
<li class="chapter" data-level="2.7" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#estadísticos-de-posición"><i class="fa fa-check"></i><b>2.7</b> Estadísticos de posición</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#percentiles"><i class="fa fa-check"></i><b>2.7.1</b> Percentiles</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#estadísticos-de-dispersión"><i class="fa fa-check"></i><b>2.8</b> Estadísticos de dispersión</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#el-rango"><i class="fa fa-check"></i><b>2.8.1</b> El Rango</a></li>
<li class="chapter" data-level="2.8.2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#la-varianza"><i class="fa fa-check"></i><b>2.8.2</b> La Varianza</a></li>
<li class="chapter" data-level="2.8.3" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#la-desviación-estándar"><i class="fa fa-check"></i><b>2.8.3</b> La Desviación Estándar</a></li>
<li class="chapter" data-level="2.8.4" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#el-rango-intercuartílico"><i class="fa fa-check"></i><b>2.8.4</b> El Rango intercuartílico</a></li>
<li class="chapter" data-level="2.8.5" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#curvas-de-distribución-de-frecuencias"><i class="fa fa-check"></i><b>2.8.5</b> Curvas de distribución de frecuencias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html"><i class="fa fa-check"></i><b>3</b> Visualización de datos con ggplot2</a>
<ul>
<li class="chapter" data-level="3.1" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#gráficos"><i class="fa fa-check"></i><b>3.1</b> Gráficos</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#para-numéricas"><i class="fa fa-check"></i><b>3.1.1</b> Para numéricas</a></li>
<li class="chapter" data-level="3.1.2" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#para-categóricas"><i class="fa fa-check"></i><b>3.1.2</b> Para categóricas</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#graficando-con-ggplot2"><i class="fa fa-check"></i><b>3.2</b> Graficando con ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html"><i class="fa fa-check"></i><b>4</b> Estadística Inferencial: Introducción</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#conceptos-principales"><i class="fa fa-check"></i><b>4.1</b> Conceptos principales</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#inferencia"><i class="fa fa-check"></i><b>4.1.1</b> Inferencia</a></li>
<li class="chapter" data-level="4.1.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#la-desviación-estándar-1"><i class="fa fa-check"></i><b>4.1.2</b> La desviación estándar</a></li>
<li class="chapter" data-level="4.1.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#distribución-normal"><i class="fa fa-check"></i><b>4.1.3</b> Distribución normal</a></li>
<li class="chapter" data-level="4.1.4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#teorema-del-límite-central"><i class="fa fa-check"></i><b>4.1.4</b> Teorema del límite central</a></li>
<li class="chapter" data-level="4.1.5" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#ley-de-los-grandes-números"><i class="fa fa-check"></i><b>4.1.5</b> Ley de los grandes números</a></li>
<li class="chapter" data-level="4.1.6" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#varias-muestras"><i class="fa fa-check"></i><b>4.1.6</b> Varias muestras</a></li>
<li class="chapter" data-level="4.1.7" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#error-estándar"><i class="fa fa-check"></i><b>4.1.7</b> Error estándar</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#métodos-de-estimación"><i class="fa fa-check"></i><b>4.2</b> Métodos de estimación</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#estimación-puntual"><i class="fa fa-check"></i><b>4.2.1</b> Estimación puntual</a></li>
<li class="chapter" data-level="4.2.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#intervalo-de-confianza-de-una-media"><i class="fa fa-check"></i><b>4.2.2</b> Intervalo de confianza de una media</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#ejercicio-1-enades-2022"><i class="fa fa-check"></i><b>4.3</b> Ejercicio 1: ENADES 2022</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#abrir-base-de-datos"><i class="fa fa-check"></i><b>4.3.1</b> Abrir base de datos</a></li>
<li class="chapter" data-level="4.3.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#identificar-una-variable-numérica"><i class="fa fa-check"></i><b>4.3.2</b> Identificar una variable numérica</a></li>
<li class="chapter" data-level="4.3.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#cálculo-del-estimador-puntual"><i class="fa fa-check"></i><b>4.3.3</b> Cálculo del estimador puntual</a></li>
<li class="chapter" data-level="4.3.4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#cálculo-del-ic-al-95"><i class="fa fa-check"></i><b>4.3.4</b> Cálculo del IC al 95%</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><i class="fa fa-check"></i><b>5</b> IC de una proporción e introducción a pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#recordemos"><i class="fa fa-check"></i><b>5.1</b> Recordemos</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#pasos-previos"><i class="fa fa-check"></i><b>5.1.1</b> Pasos previos</a></li>
<li class="chapter" data-level="5.1.2" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#estimación-puntual-1"><i class="fa fa-check"></i><b>5.1.2</b> Estimación puntual</a></li>
<li class="chapter" data-level="5.1.3" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#ic-para-una-media"><i class="fa fa-check"></i><b>5.1.3</b> IC para una media</a></li>
<li class="chapter" data-level="5.1.4" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#ic-para-una-media-según-grupos"><i class="fa fa-check"></i><b>5.1.4</b> IC para una media según grupos</a></li>
<li class="chapter" data-level="5.1.5" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#barras-de-error"><i class="fa fa-check"></i><b>5.1.5</b> Barras de error</a></li>
<li class="chapter" data-level="5.1.6" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#ahora-hazlo-tú"><i class="fa fa-check"></i><b>5.1.6</b> Ahora hazlo tú!</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#intervalo-de-una-proporción"><i class="fa fa-check"></i><b>5.2</b> Intervalo de una proporción</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#definición"><i class="fa fa-check"></i><b>5.2.1</b> Definición</a></li>
<li class="chapter" data-level="5.2.2" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#fórmula"><i class="fa fa-check"></i><b>5.2.2</b> Fórmula</a></li>
<li class="chapter" data-level="5.2.3" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#ic-de-proporción-con-la-fórmula"><i class="fa fa-check"></i><b>5.2.3</b> IC de proporción con la fórmula</a></li>
<li class="chapter" data-level="5.2.4" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#ic-de-proporción-con-prop.test"><i class="fa fa-check"></i><b>5.2.4</b> IC de proporción con <code>prop.test()</code></a></li>
<li class="chapter" data-level="5.2.5" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#ic-de-proporción-según-grupos"><i class="fa fa-check"></i><b>5.2.5</b> IC de proporción según grupos</a></li>
<li class="chapter" data-level="5.2.6" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#ahora-hazlo-tú-1"><i class="fa fa-check"></i><b>5.2.6</b> Ahora hazlo tú!</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#prueba-de-hipótesis-una-introducción"><i class="fa fa-check"></i><b>5.3</b> Prueba de hipótesis: Una introducción</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#definición-1"><i class="fa fa-check"></i><b>5.3.1</b> Definición</a></li>
<li class="chapter" data-level="5.3.2" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#paso-1-establer-hipótesis"><i class="fa fa-check"></i><b>5.3.2</b> Paso 1: Establer hipótesis</a></li>
<li class="chapter" data-level="5.3.3" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#paso-2-verificar-supuestos"><i class="fa fa-check"></i><b>5.3.3</b> Paso 2: Verificar supuestos</a></li>
<li class="chapter" data-level="5.3.4" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#paso-3-establecer-nivel-de-significancia"><i class="fa fa-check"></i><b>5.3.4</b> Paso 3: Establecer nivel de significancia</a></li>
<li class="chapter" data-level="5.3.5" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#paso-4-aplicar-test-estadístico-y-obtener-p-value"><i class="fa fa-check"></i><b>5.3.5</b> Paso 4: Aplicar test estadístico y obtener p-value</a></li>
<li class="chapter" data-level="5.3.6" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#paso-5-tomar-una-decisión"><i class="fa fa-check"></i><b>5.3.6</b> Paso 5: Tomar una decisión</a></li>
<li class="chapter" data-level="5.3.7" data-path="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html"><a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html#paso-6-interpretación"><i class="fa fa-check"></i><b>5.3.7</b> Paso 6: Interpretación</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística para el Análisis Político I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estadística-inferencial-introducción" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Sesión 4</span> Estadística Inferencial: Introducción<a href="estadística-inferencial-introducción.html#estadística-inferencial-introducción" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="conceptos-principales" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Conceptos principales<a href="estadística-inferencial-introducción.html#conceptos-principales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="inferencia" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Inferencia<a href="estadística-inferencial-introducción.html#inferencia" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>La estadística inferencial utiliza la muestra de datos para hacer estimaciones y tomar decisiones acerca de las características de una población. Esto implica la utilización de técnicas y métodos para inferir información sobre la población a partir de la información recopilada en la muestra.</p></li>
<li><p>Algunas definiciones básicas:</p></li>
</ul>
<table>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>Definición</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Población</td>
<td>Se refiere al conjunto total de individuos, objetos, eventos, medidas o cualquier otra cosa que se quiera estudiar. En estadística inferencial, la población se utiliza como el objeto de estudio, y se busca inferir información sobre ella a partir de la muestra.</td>
</tr>
<tr class="even">
<td>Muestra</td>
<td>Es un subconjunto de la población que se utiliza para hacer inferencias sobre la población en su conjunto. La selección de la muestra debe hacerse de tal forma que represente de manera adecuada las características de la población.</td>
</tr>
<tr class="odd">
<td>Estadístico</td>
<td>Es una medida numérica que se utiliza para resumir o describir alguna característica de la muestra. Los estadísticos se calculan a partir de los datos de la muestra y se utilizan para hacer inferencias sobre los parámetros de la población.</td>
</tr>
<tr class="even">
<td>Parámetro</td>
<td>Es una medida numérica que describe alguna característica de la población. En estadística inferencial, el objetivo es hacer inferencias sobre los parámetros de la población a partir de los datos de la muestra.</td>
</tr>
</tbody>
</table>
</div>
<div id="la-desviación-estándar-1" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> La desviación estándar<a href="estadística-inferencial-introducción.html#la-desviación-estándar-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>La desviación estándar es una parte integral de la estadística inferencial y entender su funcionamiento nos ayudará a utilizarla más adelante.</p></li>
<li><p>Recuerda, la desviación estándar es la raíz cuadrada de la sumatoria de todas las diferencias entre los valores observados y su media.</p></li>
</ul>
<p><span class="math display">\[\sigma = \sqrt{\frac{1}{N}\sum_{i=1}^{N}(x_i - \mu)^2}\]</span></p>
<ul>
<li>La desviación estándar se llama “estándar” porque <strong>proporciona una unidad de medida común</strong> para comparar unidades observadas de medida muy diferente. Ejemplo: imaginemos que tenemos la variable ingreso que tiene media 120 y desviación estándar 10 y deseamos analizar el caso X = 130.</li>
</ul>
<table>
<colgroup>
<col width="38%" />
<col width="45%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th>Forma de puntuación</th>
<th>Fórmula</th>
<th>Ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Puntuación en bruto</td>
<td><span class="math display">\[X\]</span></td>
<td>130 soles</td>
</tr>
<tr class="even">
<td>Puntuación de desviación</td>
<td><span class="math display">\[X - \bar{X}\]</span></td>
<td>10 soles</td>
</tr>
<tr class="odd">
<td>Puntuación estandarizada Z</td>
<td><span class="math display">\[Z = \frac{X - \bar{X}}{S_X}\]</span></td>
<td>1 SD</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Presta atención a las unidades de medida!</p>
</blockquote>
<ul>
<li><p>En el ejemplo anterior podemos corroborar que nosotros podemos medir la lejanía de una observación respecto a su media, no sólo en las unidades originales, sino diciendo <strong>cuántas desviaciones estándar</strong> la separa de su media. Está última medida se conoce como puntuaciones Z y es muy útil para comparar niveles de dispersión de variables observadas.</p></li>
<li><p>Algunas reglas: 1) mientras más lejana esté una observación de su media, mayor será su puntuación de desvación y su puntuación Z. 2) El signo de la puntuación Z indica si la observación está por debajo o por encima de la media.</p></li>
</ul>
</div>
<div id="distribución-normal" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Distribución normal<a href="estadística-inferencial-introducción.html#distribución-normal" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Anteriormente te comenté que la curva normal (forma de campana) ejercía un rol fundamental en el contexto de la estadística inferencial. Esto es gracias a una propiedades muy interesantes.</p></li>
<li><p>La principal: cuando una variable tiene distribución de puntuaciones que es normal (casi) la totalidad de observaciones están distribuidas +- 3 desviaciones estándar (puntuaciones Z) respecto de su media.</p></li>
</ul>
<p><img src="figures/curva_normal_desviaciones.png" /></p>
<ul>
<li><p>Este principio matemático sienta las bases de la imaginación estadística, dado que muchos fenómenos naturales poseen distribuciones de frecuencias en forma de campana como la curva normal.</p></li>
<li><p>Como se ve en la figura, son 4 los principios: 1) 50% de las puntuaciones caen encima de la media y 50% debajo; 2) Prácticamente todas las puntuaciones caen dentro de 3 SD a partir de la media en ambas direcciones (en realidad el 99.7%); 3) Cerca del 95% de las puntuaciones de una variable normalmente distribuida caen dentro de una distancia de +- 2 SD respecto de la media; y 4) Alrededor del 68% de las puntuaciones caen dentro de una distancia de +-1 SD respecto de la media.</p></li>
</ul>
</div>
<div id="teorema-del-límite-central" class="section level3 hasAnchor" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> Teorema del límite central<a href="estadística-inferencial-introducción.html#teorema-del-límite-central" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>El teorema del límite central (TLC) es uno de los conceptos más importantes de la estadística y es fundamental en el muestreo y la inferencia estadística.</p></li>
<li><p>En términos simples, el teorema del límite central dice que si tomamos suficientes muestras aleatorias grandes de una población, la distribución de las medias de esas muestras será una distribución normal, sin importar cómo se vea la distribución original de la población.</p></li>
<li><p>Esto es importante en el muestreo porque nos permite hacer inferencias precisas sobre una población, incluso si no conocemos su distribución. <strong>Si podemos asumir que la distribución de la población es aproximadamente normal</strong>, entonces podemos usar la distribución normal de las medias de las muestras para hacer predicciones y estimaciones precisas sobre la población.</p></li>
<li><p>Además, el TLC nos permite calcular intervalos de confianza y realizar pruebas de hipótesis (siguiente secciòn) con mayor precisión, lo que nos permite tomar decisiones más informadas basadas en los datos muestrales. En resumen, el teorema del límite central es una herramienta clave en la inferencia estadística y nos permite hacer generalizaciones precisas sobre una población a partir de datos muestrales.</p></li>
</ul>
<p><strong>Máquina de Galton</strong></p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/EvHiee7gs9Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
</iframe>
<p>El Tablero de Galton ilustra cómo la distribución de frecuencias de los resultados de muchos eventos aleatorios independientes se acerca a una distribución normal, independientemente de la forma de la distribución original, siempre que el número de eventos sea lo suficientemente grande.</p>
</div>
<div id="ley-de-los-grandes-números" class="section level3 hasAnchor" number="4.1.5">
<h3><span class="header-section-number">4.1.5</span> Ley de los grandes números<a href="estadística-inferencial-introducción.html#ley-de-los-grandes-números" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>La ley de los grandes números es un teorema en estadística que establece que, a medida que el tamaño de una muestra aumenta, la media muestral se acerca a la media poblacional. En otras palabras, cuando se toman muestras cada vez más grandes de una población, se espera que la media de esas muestras se acerque cada vez más a la media real de la población.</p></li>
<li><p>Esta ley es importante porque permite a los investigadores obtener estimaciones precisas de los parámetros de una población a partir de una muestra relativamente pequeña. Además, esta ley también es fundamental para la teoría de la probabilidad y es utilizada en muchas áreas de la estadística y de la ciencia en general.</p></li>
</ul>
<blockquote>
<p>Mientras más grande sea la muestra, la media muestras se acerca a la media poblacional.</p>
</blockquote>
</div>
<div id="varias-muestras" class="section level3 hasAnchor" number="4.1.6">
<h3><span class="header-section-number">4.1.6</span> Varias muestras<a href="estadística-inferencial-introducción.html#varias-muestras" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cuando extraemos varias muestras de una población y calculamos la media para cada una de esas muestras, obtenemos una variedad de medias muestrales. Aunque cada muestra es única y puede tener su propia media, si repitiéramos este proceso de muestreo muchas veces, observaríamos que la distribución de estas medias muestrales tiende a adoptar una forma específica. Esta forma es lo que conocemos como la “distribución de muestreo de la media”.</p>
<p>El Teorema del Límite Central, uno de los pilares fundamentales de la estadística inferencial, nos dice que, independientemente de la forma de la distribución original de la población, la distribución de las medias muestrales se aproximará a una distribución normal (o gaussiana) a medida que el tamaño de la muestra aumenta. Esta distribución normal centrada en la media verdadera de la población y con una desviación estándar llamada “error estándar” nos permite hacer inferencias sobre la media poblacional a partir de las medias de nuestras muestras, especialmente cuando el tamaño de la muestra es grande.</p>
</div>
<div id="error-estándar" class="section level3 hasAnchor" number="4.1.7">
<h3><span class="header-section-number">4.1.7</span> Error estándar<a href="estadística-inferencial-introducción.html#error-estándar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El error estándar es una medida que nos indica cuánto esperamos que varíe una estadística (como la media o la proporción) de una muestra a otra, si tomáramos múltiples muestras de la misma población. En otras palabras, es una forma de medir la variabilidad que se espera en nuestras estimaciones debido al hecho de que estamos trabajando con muestras y no con la totalidad de la población.</p>
<p>Podríamos pensar en el error estándar como una herramienta que nos ayuda a entender cuán “confiables” o “precisas” son nuestras estimaciones basadas en muestras. Un error estándar pequeño sugiere que nuestras estimaciones son relativamente estables y consistentes de una muestra a otra, mientras que un error estándar grande indica que esas estimaciones podrían variar considerablemente entre diferentes muestras.</p>
<p>Es importante destacar que el error estándar está relacionado con la desviación estándar de la población. Mientras que la desviación estándar nos dice cuánto varían los valores individuales alrededor de la media en una población o muestra, el error estándar nos dice cuánto esperamos que varíen nuestras estadísticas de muestra (como la media muestral) alrededor de la verdadera estadística poblacional.</p>
<ul>
<li><p>Recuerdas que habíamos dicho que en la curva normal se podría evidenciar que la totalidad de las observaciones se encontraban entre -3 y +3 desviaciones estándar respecto de la media? En el caso de las distribuciones muestrales, esa desviación estándar es conocida como <strong>error estándar</strong>.</p></li>
<li><p>El error estándar mide la dispersión del error de muestreo que ocurre cuando se muestrea repetidamente una población (como lo hicimos líneas arriba).</p></li>
</ul>
<p><span class="math display">\[s_{\hat{x}} = \frac{s}{\sqrt{n}}\]</span></p>
<p>Entonces los puntos más importantes del EE son:</p>
<ul>
<li><p>El error estándar es una medida de cuánto se espera que varíen las medias de las muestras tomadas de una población determinada. A medida que el tamaño de la muestra aumenta, el error estándar tiende a disminuir.</p></li>
<li><p>El error estándar es importante en el cálculo de los intervalos de confianza. Cuanto menor sea el error estándar, menor será la variabilidad de las medias muestrales y más preciso será el intervalo de confianza.</p></li>
<li><p>El error estándar se calcula dividiendo la desviación estándar de la población entre la raíz cuadrada del tamaño de la muestra. En la mayoría de los casos, la desviación estándar de la población no se conoce y se utiliza <strong>la desviación estándar de la muestra para estimar el error estándar</strong>.</p></li>
</ul>
</div>
</div>
<div id="métodos-de-estimación" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Métodos de estimación<a href="estadística-inferencial-introducción.html#métodos-de-estimación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="estimación-puntual" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Estimación puntual<a href="estadística-inferencial-introducción.html#estimación-puntual" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En estadística inferencial, la estimación puntual se refiere a la técnica de utilizar los datos de una muestra para calcular un único valor, conocido como punto estimado, que es la mejor suposición o predicción del valor de un parámetro desconocido de la población.</p>
<p>Por ejemplo, si queremos conocer el salario promedio de todos los trabajadores de una empresa, podríamos tomar una muestra aleatoria de trabajadores, calcular el salario promedio de esa muestra y usar ese valor como nuestra estimación puntual del salario promedio real de toda la empresa.</p>
<p>Esencialmente, este valor es nuestra “mejor suposición” basada en la información que hemos recolectado. Sin embargo, aunque la estimación puntual es directa y fácil de entender, no refleja la incertidumbre o variabilidad que podría haber en esa estimación.</p>
<p>Es por esta razón que, en muchas situaciones, se complementa con técnicas como la estimación por intervalo para obtener una visión más completa y matizada del parámetro que estamos tratando de estimar.</p>
</div>
<div id="intervalo-de-confianza-de-una-media" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Intervalo de confianza de una media<a href="estadística-inferencial-introducción.html#intervalo-de-confianza-de-una-media" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="figures/intervalos.png" /></p>
<ul>
<li><p>El intervalo de confianza es un rango de valores posibles de un parámetro expresado con un grado específico de confianza.</p></li>
<li><p>Si tenemos un nivel de confianza de 95% quiere decir que si realizamos 100 veces el mismo procedimiento de muestreo y calculamos los estadísticos de interés, 95 veces nos van a salir resultados en los intervalos calculados. Si lo realizamos con un 99% de confianza, de igual manera, si realizamos 100 veces el procedimiento, 99 veces nos va a salir resultados en el intervalo resultante. Esto lo tenemos claro gracias a la explicación del rol que cumple la curva normal y sus propiedades.</p></li>
</ul>
<blockquote>
<p>A MAYOR CONFIANZA MENOR ES LA PRECISIÓN (LOS INTERVALOS SON MÁS AMPLIOS)</p>
</blockquote>
<ul>
<li>Para el cálculo de un intervalo de confianza utilizamos la siguiente fórmula. Recuerda</li>
</ul>
<p><img src="figures/IC_MEDIAS.jpg" />
- Ese valor que se suma y se resta a la media muestral es el <strong>término de error</strong>, sin embargo, es más conocido como margen de error.</p>
</div>
</div>
<div id="ejercicio-1-enades-2022" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Ejercicio 1: ENADES 2022<a href="estadística-inferencial-introducción.html#ejercicio-1-enades-2022" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El Instituto de Estudios Peruanos, por encargo de Oxfam en Perú, elaboró la I Encuesta Nacional de percepción de Desigualdades – ENADES 2022. Este estudio pone a disposición del público el análisis estadístico más completo a la fecha sobre la percepción de las diferentes formas de desigualdad en el Perú.</p>
<p>Además de factores económicos, la presente encuesta incluye indicadores que permiten medir la magnitud de una serie de brechas sociales y políticas: desde diferencias de género, clase y relaciones étnico-raciales, hasta dimensiones subjetivas de la desigualdad y sus vínculos con orientaciones políticas. Como se muestra a lo largo del informe, la base de datos de este proyecto provee herramientas valiosas a expertos de diferentes campos, tanto académicos como profesionales, estudiantes y personas interesadas en el análisis multidimensional de la desigualdad en el país.</p>
<p>Puedes abrir el cuestionario de la encuestas <strong><a href="https://iep.org.pe/wp-content/uploads/2022/08/Cuestionario-Oxfam-IEP.-ENADES-2022-final.pdf">aquí</a></strong>.</p>
<p>También puedes ver el informe <strong><a href="https://iep.org.pe/wp-content/uploads/2022/07/I-Encuesta-nacional-de-percepcion-de-desigualdades-ENADES-2022-v2.pdf">aquí</a></strong>.</p>
<div id="abrir-base-de-datos" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Abrir base de datos<a href="estadística-inferencial-introducción.html#abrir-base-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="estadística-inferencial-introducción.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="estadística-inferencial-introducción.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="estadística-inferencial-introducción.html#cb1-3" tabindex="-1"></a>enades<span class="ot">&lt;-</span><span class="fu">read_spss</span>(<span class="st">&quot;data/ENADES_2022.sav&quot;</span>) <span class="co"># Con esta función abrimos archivos de SPSS</span></span>
<span id="cb1-4"><a href="estadística-inferencial-introducción.html#cb1-4" tabindex="-1"></a><span class="co"># enades&lt;-read_spss(&quot;https://github.com/ChristianChiroqueR/banco_de_datos/raw/main/ENADES_2022.sav&quot;)</span></span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="estadística-inferencial-introducción.html#cb2-1" tabindex="-1"></a><span class="fu">names</span>(enades)</span></code></pre></div>
<pre><code>##  [1] &quot;NC&quot;          &quot;edad&quot;        &quot;edadr&quot;       &quot;sexo&quot;        &quot;dep&quot;        
##  [6] &quot;prov&quot;        &quot;dist&quot;        &quot;zona1&quot;       &quot;zona2&quot;       &quot;zona3&quot;      
## [11] &quot;zonali1&quot;     &quot;zonali2&quot;     &quot;region&quot;      &quot;area&quot;        &quot;area2&quot;      
## [16] &quot;ambito&quot;      &quot;hijos18&quot;     &quot;hogar&quot;       &quot;edu&quot;         &quot;edur&quot;       
## [21] &quot;edu2&quot;        &quot;edupadre&quot;    &quot;edupadrer&quot;   &quot;edupadre2&quot;   &quot;edumadre&quot;   
## [26] &quot;edumadrer&quot;   &quot;edumadre2&quot;   &quot;ocup1&quot;       &quot;ocup2.CIUO1&quot; &quot;ocup2.CIUO2&quot;
## [31] &quot;ocupadre&quot;    &quot;p01.1&quot;       &quot;p01.2&quot;       &quot;p01.3&quot;       &quot;p01.4&quot;      
## [36] &quot;p01.5&quot;       &quot;p01.99&quot;      &quot;p02&quot;         &quot;p03.1&quot;       &quot;p03.2&quot;      
## [41] &quot;p03.3&quot;       &quot;p03.4&quot;       &quot;p03.5&quot;       &quot;p04&quot;         &quot;p04a&quot;       
## [46] &quot;p05&quot;         &quot;p06&quot;         &quot;p07&quot;         &quot;p07a&quot;        &quot;p08&quot;        
## [51] &quot;yhogar&quot;      &quot;yhogar_pc1&quot;  &quot;yhogar_pc2&quot;  &quot;ABq10d&quot;      &quot;p10.1&quot;      
## [56] &quot;p10.2&quot;       &quot;p10.3&quot;       &quot;p10.4&quot;       &quot;p10.5&quot;       &quot;p10.6&quot;      
## [61] &quot;p10.7&quot;       &quot;p11.1&quot;       &quot;p11.2&quot;       &quot;p11.3&quot;       &quot;p11.4&quot;      
## [66] &quot;p12.1&quot;       &quot;p12.2&quot;       &quot;p12.3&quot;       &quot;p12.4&quot;       &quot;ABros1&quot;     
## [71] &quot;ABros6&quot;      &quot;ABros4&quot;      &quot;p13&quot;         &quot;p14_1&quot;       &quot;p14_2&quot;      
## [76] &quot;p14_3&quot;       &quot;p15&quot;         &quot;p16&quot;         &quot;p17&quot;         &quot;etnicidad&quot;  
## [81] &quot;etnicidad2&quot;  &quot;ideología&quot;   &quot;ideologia2&quot;  &quot;NSE&quot;         &quot;NSE1&quot;       
## [86] &quot;NSE2&quot;        &quot;pondera&quot;</code></pre>
<blockquote>
<p>Recuerda que si en un primer momento te pierdes un poco entre los nombres de las variables, eso quiere decir que tienes que leer el cuestionario y el diccionario de variables!</p>
</blockquote>
</div>
<div id="identificar-una-variable-numérica" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Identificar una variable numérica<a href="estadística-inferencial-introducción.html#identificar-una-variable-numérica" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Elijamos la variable P17:</p>
<ul>
<li>En una escala del 1 al 10, en la que 1 es “Totalmente inaceptable” y 10 es “Totalmente aceptable”. ¿Hasta qué punto es aceptable la desigualdad en el Perú? Dígame un número de 1 a 10, recuerde que 1 es “Totalmente inaceptable” y 10 es “Totalmente aceptable (RESPUESTA ESPONTÁNEA)</li>
</ul>
<p>La convertimos en numérica.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="estadística-inferencial-introducción.html#cb4-1" tabindex="-1"></a>enades<span class="sc">$</span>p17<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(enades<span class="sc">$</span>p17)</span></code></pre></div>
<p>Solicitamos los estadísticos descriptivos para darle una primera mirada.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="estadística-inferencial-introducción.html#cb5-1" tabindex="-1"></a><span class="fu">summary</span>(enades<span class="sc">$</span>p17)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.000   1.000   5.000   4.571   7.000  10.000      23</code></pre>
<p>Podemos graficarlo</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="estadística-inferencial-introducción.html#cb7-1" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="estadística-inferencial-introducción.html#cb7-2" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb7-3"><a href="estadística-inferencial-introducción.html#cb7-3" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x=</span>p17)<span class="sc">+</span></span>
<span id="cb7-4"><a href="estadística-inferencial-introducción.html#cb7-4" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="cálculo-del-estimador-puntual" class="section level3 hasAnchor" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> Cálculo del estimador puntual<a href="estadística-inferencial-introducción.html#cálculo-del-estimador-puntual" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Calculamos el estimador puntual, en este caso, la media muestral.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="estadística-inferencial-introducción.html#cb8-1" tabindex="-1"></a><span class="fu">mean</span>(enades<span class="sc">$</span>p17, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 4.571334</code></pre>
<p>Tienes que recordar lo básico de este:</p>
<ol style="list-style-type: decimal">
<li><p>Es solo una aproximación del verdadero valor poblacional, y su precisión puede variar dependiendo del tamaño y calidad de la muestra, entre otros factores.</p></li>
<li><p>Es por ello que, a menudo, se complementa con intervalos de confianza para ofrecer un rango de valores en los que es probable que se encuentre el verdadero parámetro poblacional.</p></li>
</ol>
</div>
<div id="cálculo-del-ic-al-95" class="section level3 hasAnchor" number="4.3.4">
<h3><span class="header-section-number">4.3.4</span> Cálculo del IC al 95%<a href="estadística-inferencial-introducción.html#cálculo-del-ic-al-95" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>MANUAL</strong></p>
<p>Recordemos qué necesitamos para calcular el intervalo de confianza de una media.</p>
<p>Necesitamos la media muestral (mean) de esa única muestra que obtuvimos de la población, la desviación estándar (sd) y el tamaño de muestra que tenemos (n).</p>
<p>Así también, necesitamos elegir qué nivel de confianza vamos a tomar (recuerdas los intervalos de la distribución normal? y cómo se aplicaría a distribuciones muestrales?), es decir, si vamos al 95% (1.96) o algún otro nivel.</p>
<p>Calculemos cada uno de estos</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="estadística-inferencial-introducción.html#cb10-1" tabindex="-1"></a>media<span class="ot">&lt;-</span><span class="fu">mean</span>(enades<span class="sc">$</span>p17, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-2"><a href="estadística-inferencial-introducción.html#cb10-2" tabindex="-1"></a>SE<span class="ot">&lt;-</span> <span class="fu">sd</span>(enades<span class="sc">$</span>p17, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-3"><a href="estadística-inferencial-introducción.html#cb10-3" tabindex="-1"></a>n <span class="ot">&lt;-</span><span class="fu">length</span>(enades<span class="sc">$</span>p17)</span>
<span id="cb10-4"><a href="estadística-inferencial-introducción.html#cb10-4" tabindex="-1"></a>z<span class="ot">&lt;-</span> <span class="fl">1.96</span></span></code></pre></div>
<p>Ahora recordamos la fórmula:</p>
<p><img src="figures/IC_MEDIAS.jpg" /></p>
<p>Dónde el error estándar está dado por:</p>
<p><span class="math display">\[s_{\hat{x}} = \frac{s}{\sqrt{n}}\]</span></p>
<p>Entonces:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="estadística-inferencial-introducción.html#cb11-1" tabindex="-1"></a>error_estandar <span class="ot">&lt;-</span> SE<span class="sc">/</span><span class="fu">sqrt</span>(n)</span>
<span id="cb11-2"><a href="estadística-inferencial-introducción.html#cb11-2" tabindex="-1"></a>error_estandar</span></code></pre></div>
<pre><code>## [1] 0.08009848</code></pre>
<p>Por lo pronto, hemos obtenido un error estándar con un valor de 0.08009848.</p>
<p>El error estándar, en su esencia, nos brinda una medida de cuánta variabilidad podemos esperar en nuestras estimaciones si repitiéramos el muestreo muchas veces. Cuando interpretamos un error estándar específico, como 0.08009848podemos considerar lo siguiente:</p>
<p>Un error estándar de 0.08009848 sugiere que, si tomáramos múltiples muestras del mismo tamaño de la población y calculáramos la estadística de interés (por ejemplo, la media) para cada muestra, esperaríamos que la mayoría de esas estadísticas estuvieran dentro de 0.08009848 unidades de la estadística media de todas esas muestras.</p>
<p>En otras palabras, el valor de 0.08009848 nos da una idea de la “precisión” de nuestra estimación basada en una sola muestra. Una estimación con un error estándar más pequeño generalmente se considera más “precisa” que una con un error estándar más grande, porque indica menos variabilidad entre las estimaciones de diferentes muestras.</p>
<p>Ahora sí, una vez calculado el error estándar podemos calcular los límite inferior o superior. Recuerda que debemos aplicar la fórmula y que la única diferencia para calcular el límite inferior y superior es el signo:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="estadística-inferencial-introducción.html#cb13-1" tabindex="-1"></a>limite_inferior<span class="ot">&lt;-</span> media <span class="sc">-</span> (z<span class="sc">*</span>error_estandar)</span>
<span id="cb13-2"><a href="estadística-inferencial-introducción.html#cb13-2" tabindex="-1"></a>limite_superior<span class="ot">&lt;-</span> media <span class="sc">+</span> (z<span class="sc">*</span>error_estandar)</span></code></pre></div>
<p>Los presentamos:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="estadística-inferencial-introducción.html#cb14-1" tabindex="-1"></a>limite_inferior</span></code></pre></div>
<pre><code>## [1] 4.414341</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="estadística-inferencial-introducción.html#cb16-1" tabindex="-1"></a>limite_superior</span></code></pre></div>
<pre><code>## [1] 4.728327</code></pre>
<p>Con ello podemos concluir que: <strong>Con un 95% de confianza, podemos afirmar que la media poblacional de la aceptación de la desigualdad en el Perú (que va del 1 al 10) se encuentra entre 4.414341 y 4.728327</strong>.</p>
<p>Esto lo podemos interpretar también de las siguientes forma:</p>
<ul>
<li><p>Estoy 95% seguro de que el promedio de aceptación de la desigualdad en el país real (es decir el parámetro) se encuentra entre 4.414341 y 4.728327.</p></li>
<li><p>Si realizara este estudio 100 veces, 95 veces obtendré un promedio de aceptación de la desigualdad dentro de este intervalo: 4.414341 y 4.728327.</p></li>
</ul>
<p><strong>CON LA FUNCIÓN ciMean()</strong></p>
<p>Una vez que hemos navegado por el proceso de calcular un intervalo de confianza de manera manual, utilizando la fórmula tradicional, es hora de introducir herramientas que simplifiquen y agilicen este proceso en el mundo real del análisis de datos. Para ello, en R, utilizaremos el paquete lsr y, específicamente, la función ciMean. Esta función está diseñada para calcular automáticamente el intervalo de confianza para la media de un conjunto de datos. Al proporcionarle una serie de datos como entrada, ciMean nos devuelve el rango en el que, con un nivel de confianza específico (por defecto, 95%), esperamos que se encuentre la verdadera media poblacional. Es una herramienta poderosa que combina precisión con eficiencia, permitiéndonos centrarnos en la interpretación y aplicación de nuestros resultados.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="estadística-inferencial-introducción.html#cb18-1" tabindex="-1"></a><span class="fu">library</span>(lsr)</span>
<span id="cb18-2"><a href="estadística-inferencial-introducción.html#cb18-2" tabindex="-1"></a><span class="fu">ciMean</span>(enades<span class="sc">$</span>p17, <span class="at">na.rm =</span> T)</span></code></pre></div>
<pre><code>##          2.5%    97.5%
## [1,] 4.413023 4.729645</code></pre>
<p>Es el mismo resultado que obtuvimos arriba. Como te puedes dar cuenta, si hemos recorrido este camino (medio tedioso) es para que te quede claro cómo se obtienen esos dos números que llamamos intervalos de confianza y de qué depende en la práctica al utilizar una muestra real.</p>
<p><img src="https://i.pinimg.com/1200x/a1/bd/fa/a1bdfae8b7dc576b5c2bfaeea7608973.jpg" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="visualización-de-datos-con-ggplot2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ic-de-una-proporción-e-introducción-a-pruebas-de-hipótesis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ChristianChiroqueR/Estadistica_AP_1_PUCP/edit/master/04-intro_inferencia.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ChristianChiroqueR/Estadistica_AP_1_PUCP/blob/master/04-intro_inferencia.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
