<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Sesión 5 Estadística Inferencial II | Estadística para el Análisis Político I</title>
  <meta name="description" content="Sesión 5 Estadística Inferencial II | Estadística para el Análisis Político I" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Sesión 5 Estadística Inferencial II | Estadística para el Análisis Político I" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Sesión 5 Estadística Inferencial II | Estadística para el Análisis Político I" />
  
  
  

<meta name="author" content="Docente: Christian Chiroque Ruiz" />


<meta name="date" content="2023-04-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estadística-inferencial-introducción.html"/>
<link rel="next" href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística AP I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#los-pilares-de-la-estadística"><i class="fa fa-check"></i><b>1.1</b> Los pilares de la Estadística</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#definición"><i class="fa fa-check"></i><b>1.1.1</b> Definición</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#unidad-de-análisis"><i class="fa fa-check"></i><b>1.1.2</b> Unidad de análisis</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#tipos-de-variable"><i class="fa fa-check"></i><b>1.1.3</b> Tipos de variable</a></li>
<li class="chapter" data-level="1.1.4" data-path="index.html"><a href="index.html#escalas-de-medición"><i class="fa fa-check"></i><b>1.1.4</b> Escalas de medición</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#los-objetos-elementos-básicos-en-el-r"><i class="fa fa-check"></i><b>1.2</b> Los objetos: elementos básicos en el R</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#las-estructuras-en-el-r"><i class="fa fa-check"></i><b>1.3</b> Las Estructuras en el R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#los-vectores"><i class="fa fa-check"></i><b>1.3.1</b> Los vectores</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#un-vector-especial-los-factores"><i class="fa fa-check"></i><b>1.3.2</b> Un vector especial: los factores</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#data-frames"><i class="fa fa-check"></i><b>1.3.3</b> Data frames</a></li>
<li class="chapter" data-level="1.3.4" data-path="index.html"><a href="index.html#propiedades"><i class="fa fa-check"></i><b>1.3.4</b> Propiedades</a></li>
<li class="chapter" data-level="1.3.5" data-path="index.html"><a href="index.html#índices"><i class="fa fa-check"></i><b>1.3.5</b> Índices</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#nuestras-herramientas-paquetes-y-funciones"><i class="fa fa-check"></i><b>1.4</b> Nuestras herramientas: Paquetes y funciones</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#paquetes"><i class="fa fa-check"></i><b>1.4.1</b> Paquetes</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#funciones"><i class="fa fa-check"></i><b>1.4.2</b> Funciones</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#abrir-una-base-de-datos"><i class="fa fa-check"></i><b>1.5</b> Abrir una base de datos</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#manipulación-de-datos-con-tidyverse"><i class="fa fa-check"></i><b>1.6</b> Manipulación de datos con Tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html"><i class="fa fa-check"></i><b>2</b> Manipulación de datos y estadísticos descriptivos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#preparación"><i class="fa fa-check"></i><b>2.1</b> Preparación</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#entorno-de-trabajo"><i class="fa fa-check"></i><b>2.1.1</b> Entorno de trabajo</a></li>
<li class="chapter" data-level="2.1.2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#paquetes-a-utilizar"><i class="fa fa-check"></i><b>2.1.2</b> Paquetes a utilizar</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#base-de-datos"><i class="fa fa-check"></i><b>2.2</b> Base de datos</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#importación"><i class="fa fa-check"></i><b>2.2.1</b> Importación</a></li>
<li class="chapter" data-level="2.2.2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#verificar-el-tipo-de-variable"><i class="fa fa-check"></i><b>2.2.2</b> Verificar el tipo de variable</a></li>
<li class="chapter" data-level="2.2.3" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#creación-de-subset"><i class="fa fa-check"></i><b>2.2.3</b> Creación de subset</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-tendencia-central"><i class="fa fa-check"></i><b>2.3</b> Estadísticos de tendencia central</a></li>
<li class="chapter" data-level="2.4" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-posición"><i class="fa fa-check"></i><b>2.4</b> Estadísticos de posición</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#percentiles"><i class="fa fa-check"></i><b>2.4.1</b> Percentiles</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-dispersión"><i class="fa fa-check"></i><b>2.5</b> Estadísticos de dispersión</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#el-rango"><i class="fa fa-check"></i><b>2.5.1</b> El Rango</a></li>
<li class="chapter" data-level="2.5.2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#la-varianza"><i class="fa fa-check"></i><b>2.5.2</b> La Varianza</a></li>
<li class="chapter" data-level="2.5.3" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#la-desviación-estándar"><i class="fa fa-check"></i><b>2.5.3</b> La Desviación Estándar</a></li>
<li class="chapter" data-level="2.5.4" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#el-rango-intercuartílico"><i class="fa fa-check"></i><b>2.5.4</b> El Rango intercuartílico</a></li>
<li class="chapter" data-level="2.5.5" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#curvas-de-distribución-de-frecuencias"><i class="fa fa-check"></i><b>2.5.5</b> Curvas de distribución de frecuencias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html"><i class="fa fa-check"></i><b>3</b> Visualización de datos con ggplot2</a>
<ul>
<li class="chapter" data-level="3.1" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#base-de-datos-1"><i class="fa fa-check"></i><b>3.1</b> Base de datos</a></li>
<li class="chapter" data-level="3.2" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#section"><i class="fa fa-check"></i><b>3.2</b> </a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html"><i class="fa fa-check"></i><b>4</b> Estadística Inferencial: Introducción</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#antecedentes-relevantes"><i class="fa fa-check"></i><b>4.1</b> Antecedentes relevantes</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#la-desviación-estándar-1"><i class="fa fa-check"></i><b>4.1.1</b> La desviación estándar</a></li>
<li class="chapter" data-level="4.1.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#la-distribución-curva-normal-y-las-sd"><i class="fa fa-check"></i><b>4.1.2</b> La distribución (curva) normal y las SD</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#elementos-básicos-de-probabilidad"><i class="fa fa-check"></i><b>4.2</b> Elementos básicos de probabilidad</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#conceptos"><i class="fa fa-check"></i><b>4.2.1</b> Conceptos</a></li>
<li class="chapter" data-level="4.2.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#curva-normal-y-probabilidades"><i class="fa fa-check"></i><b>4.2.2</b> Curva normal y probabilidades</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#ejercicio-con-r"><i class="fa fa-check"></i><b>4.3</b> Ejercicio con R</a></li>
<li class="chapter" data-level="4.4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#elementos-básicos-de-la-inferencia"><i class="fa fa-check"></i><b>4.4</b> Elementos básicos de la inferencia</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#definiciones-preliminares"><i class="fa fa-check"></i><b>4.4.1</b> Definiciones preliminares</a></li>
<li class="chapter" data-level="4.4.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#estimación-puntual"><i class="fa fa-check"></i><b>4.4.2</b> Estimación puntual</a></li>
<li class="chapter" data-level="4.4.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#error-de-muestreo"><i class="fa fa-check"></i><b>4.4.3</b> Error de muestreo</a></li>
<li class="chapter" data-level="4.4.4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#distribuciones-de-muestreo."><i class="fa fa-check"></i><b>4.4.4</b> Distribuciones de muestreo.</a></li>
<li class="chapter" data-level="4.4.5" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#error-estándar"><i class="fa fa-check"></i><b>4.4.5</b> Error estándar</a></li>
<li class="chapter" data-level="4.4.6" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#teorema-del-límite-central"><i class="fa fa-check"></i><b>4.4.6</b> Teorema del límite central</a></li>
<li class="chapter" data-level="4.4.7" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#ley-de-los-grandes-números"><i class="fa fa-check"></i><b>4.4.7</b> Ley de los grandes números</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#intervalo-de-confianza-de-una-media"><i class="fa fa-check"></i><b>4.5</b> Intervalo de confianza de una media</a></li>
<li class="chapter" data-level="4.6" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#ejercicio-con-r-enades-2022"><i class="fa fa-check"></i><b>4.6</b> Ejercicio con R: ENADES 2022</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#abrir-base-de-datos"><i class="fa fa-check"></i><b>4.6.1</b> Abrir base de datos</a></li>
<li class="chapter" data-level="4.6.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#identificar-una-variable-numérica"><i class="fa fa-check"></i><b>4.6.2</b> Identificar una variable numérica</a></li>
<li class="chapter" data-level="4.6.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#cálculo-del-estimador-puntual-media-muestral"><i class="fa fa-check"></i><b>4.6.3</b> Cálculo del estimador puntual: media muestral</a></li>
<li class="chapter" data-level="4.6.4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#cálculo-del-intervalo-de-confianza-al-95"><i class="fa fa-check"></i><b>4.6.4</b> Cálculo del intervalo de confianza al 95%</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html"><i class="fa fa-check"></i><b>5</b> Estadística Inferencial II</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#recordemos"><i class="fa fa-check"></i><b>5.1</b> Recordemos</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#pasos-previos"><i class="fa fa-check"></i><b>5.1.1</b> Pasos previos</a></li>
<li class="chapter" data-level="5.1.2" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#estimación-puntual-1"><i class="fa fa-check"></i><b>5.1.2</b> Estimación puntual</a></li>
<li class="chapter" data-level="5.1.3" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#ic-para-una-media"><i class="fa fa-check"></i><b>5.1.3</b> IC para una media</a></li>
<li class="chapter" data-level="5.1.4" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#ic-para-una-media-según-grupos"><i class="fa fa-check"></i><b>5.1.4</b> IC para una media según grupos</a></li>
<li class="chapter" data-level="5.1.5" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#barras-de-error"><i class="fa fa-check"></i><b>5.1.5</b> Barras de error</a></li>
<li class="chapter" data-level="5.1.6" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#ahora-hazlo-tú"><i class="fa fa-check"></i><b>5.1.6</b> Ahora hazlo tú!</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#intervalo-de-una-proporción"><i class="fa fa-check"></i><b>5.2</b> Intervalo de una proporción</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#definición-1"><i class="fa fa-check"></i><b>5.2.1</b> Definición</a></li>
<li class="chapter" data-level="5.2.2" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#fórmula"><i class="fa fa-check"></i><b>5.2.2</b> Fórmula</a></li>
<li class="chapter" data-level="5.2.3" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#ic-de-proporción-con-la-fórmula"><i class="fa fa-check"></i><b>5.2.3</b> IC de proporción con la fórmula</a></li>
<li class="chapter" data-level="5.2.4" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#ic-de-proporción-con-prop.test"><i class="fa fa-check"></i><b>5.2.4</b> IC de proporción con <code>prop.test()</code></a></li>
<li class="chapter" data-level="5.2.5" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#ic-de-proporción-según-grupos"><i class="fa fa-check"></i><b>5.2.5</b> IC de proporción según grupos</a></li>
<li class="chapter" data-level="5.2.6" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#ahora-hazlo-tú-1"><i class="fa fa-check"></i><b>5.2.6</b> Ahora hazlo tú!</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#prueba-de-hipótesis-introducción"><i class="fa fa-check"></i><b>5.3</b> Prueba de hipótesis: Introducción</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#definición-2"><i class="fa fa-check"></i><b>5.3.1</b> Definición</a></li>
<li class="chapter" data-level="5.3.2" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#paso-1-establer-hipótesis"><i class="fa fa-check"></i><b>5.3.2</b> Paso 1: Establer hipótesis</a></li>
<li class="chapter" data-level="5.3.3" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#paso-2-verificar-supuestos"><i class="fa fa-check"></i><b>5.3.3</b> Paso 2: Verificar supuestos</a></li>
<li class="chapter" data-level="5.3.4" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#paso-3-establecer-nivel-de-significancia"><i class="fa fa-check"></i><b>5.3.4</b> Paso 3: Establecer nivel de significancia</a></li>
<li class="chapter" data-level="5.3.5" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#paso-4-aplicar-test-estadístico-y-obtener-p-value"><i class="fa fa-check"></i><b>5.3.5</b> Paso 4: Aplicar test estadístico y obtener p-value</a></li>
<li class="chapter" data-level="5.3.6" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#paso-5-tomar-una-decisión"><i class="fa fa-check"></i><b>5.3.6</b> Paso 5: Tomar una decisión</a></li>
<li class="chapter" data-level="5.3.7" data-path="estadística-inferencial-ii.html"><a href="estadística-inferencial-ii.html#paso-6-interpretación"><i class="fa fa-check"></i><b>5.3.7</b> Paso 6: Interpretación</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><i class="fa fa-check"></i><b>6</b> Estadística Inferencial III: Comparación en dos muestras independientes</a>
<ul>
<li class="chapter" data-level="6.1" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#recordemos-1"><i class="fa fa-check"></i><b>6.1</b> Recordemos</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#prueba-de-hipótesis"><i class="fa fa-check"></i><b>6.1.1</b> Prueba de hipótesis</a></li>
<li class="chapter" data-level="6.1.2" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#flujograma"><i class="fa fa-check"></i><b>6.1.2</b> Flujograma</a></li>
<li class="chapter" data-level="6.1.3" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#tipos-de-prueba-de-hipótesis"><i class="fa fa-check"></i><b>6.1.3</b> Tipos de prueba de hipótesis</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#prueba-t-para-diferencia-de-medias"><i class="fa fa-check"></i><b>6.2</b> Prueba T para diferencia de medias</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#definición-3"><i class="fa fa-check"></i><b>6.2.1</b> Definición</a></li>
<li class="chapter" data-level="6.2.2" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#paso-0-análisis-exploratorio-de-datos-eda"><i class="fa fa-check"></i><b>6.2.2</b> Paso 0: Análisis exploratorio de datos (EDA)</a></li>
<li class="chapter" data-level="6.2.3" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#paso-1-establecer-hipótesis"><i class="fa fa-check"></i><b>6.2.3</b> Paso 1: Establecer hipótesis</a></li>
<li class="chapter" data-level="6.2.4" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#paso-2-verificar-supuestos-1"><i class="fa fa-check"></i><b>6.2.4</b> Paso 2: Verificar supuestos</a></li>
<li class="chapter" data-level="6.2.5" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#paso-3-establecer-nivel-de-significancia-1"><i class="fa fa-check"></i><b>6.2.5</b> Paso 3: Establecer nivel de significancia</a></li>
<li class="chapter" data-level="6.2.6" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#paso-4-calcular-estadístico-de-prueba-y-p-valor"><i class="fa fa-check"></i><b>6.2.6</b> Paso 4: Calcular estadístico de prueba y p-valor</a></li>
<li class="chapter" data-level="6.2.7" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#paso-5-tomar-una-decisión-1"><i class="fa fa-check"></i><b>6.2.7</b> Paso 5: Tomar una decisión</a></li>
<li class="chapter" data-level="6.2.8" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#paso-6-interpretación-1"><i class="fa fa-check"></i><b>6.2.8</b> Paso 6: Interpretación</a></li>
<li class="chapter" data-level="6.2.9" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#ahora-hazlo-tú-2"><i class="fa fa-check"></i><b>6.2.9</b> Ahora hazlo tú!</a></li>
<li class="chapter" data-level="6.2.10" data-path="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html"><a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html#a-tener-en-cuenta-ph-para-igualdad-de-varianzas"><i class="fa fa-check"></i><b>6.2.10</b> A tener en cuenta: PH para igualdad de varianzas</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística para el Análisis Político I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estadística-inferencial-ii" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Sesión 5</span> Estadística Inferencial II<a href="estadística-inferencial-ii.html#estadística-inferencial-ii" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="recordemos" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Recordemos<a href="estadística-inferencial-ii.html#recordemos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Abramos los paquetes que vamos a necesitar:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="estadística-inferencial-ii.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb125-2"><a href="estadística-inferencial-ii.html#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="fu">p_load</span>(haven, tidyverse, lsr, kableExtra)</span>
<span id="cb125-3"><a href="estadística-inferencial-ii.html#cb125-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-4"><a href="estadística-inferencial-ii.html#cb125-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Esto equivale a:</span></span>
<span id="cb125-5"><a href="estadística-inferencial-ii.html#cb125-5" aria-hidden="true" tabindex="-1"></a><span class="co"># library(haven)</span></span>
<span id="cb125-6"><a href="estadística-inferencial-ii.html#cb125-6" aria-hidden="true" tabindex="-1"></a><span class="co"># library(tidyverse)</span></span>
<span id="cb125-7"><a href="estadística-inferencial-ii.html#cb125-7" aria-hidden="true" tabindex="-1"></a><span class="co"># library(lsr)</span></span>
<span id="cb125-8"><a href="estadística-inferencial-ii.html#cb125-8" aria-hidden="true" tabindex="-1"></a><span class="co"># library(kableExtra)</span></span>
<span id="cb125-9"><a href="estadística-inferencial-ii.html#cb125-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-10"><a href="estadística-inferencial-ii.html#cb125-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Es útil cuando necesitamos abrir un gran número de librerías!</span></span></code></pre></div>
<p>Continuemos con el ejercicio que vimos en la última clase utilizando la ENADES.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="estadística-inferencial-ii.html#cb126-1" aria-hidden="true" tabindex="-1"></a>enades<span class="ot">&lt;-</span><span class="fu">read_spss</span>(<span class="st">&quot;data/ENADES_2022.sav&quot;</span>) <span class="co"># Con esta función abrimos archivos de SPSS</span></span>
<span id="cb126-2"><a href="estadística-inferencial-ii.html#cb126-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-3"><a href="estadística-inferencial-ii.html#cb126-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Si quiere abrirlo desde GitHub entonces corre la siguiente línea:</span></span>
<span id="cb126-4"><a href="estadística-inferencial-ii.html#cb126-4" aria-hidden="true" tabindex="-1"></a><span class="co"># enades&lt;-read_spss(&quot;https://github.com/ChristianChiroqueR/banco_de_datos/raw/main/ENADES_2022.sav&quot;)</span></span></code></pre></div>
<p>Elijamos la variable P17:</p>
<ul>
<li>En una escala del 1 al 10, en la que 1 es “Totalmente inaceptable” y 10 es “Totalmente aceptable”. ¿Hasta qué punto es aceptable la desigualdad en el Perú? Dígame un número de 1 a 10, recuerde que 1 es “Totalmente inaceptable” y 10 es “Totalmente aceptable (RESPUESTA ESPONTÁNEA)</li>
</ul>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="estadística-inferencial-ii.html#cb127-1" aria-hidden="true" tabindex="-1"></a>enades<span class="sc">$</span>p17<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(enades<span class="sc">$</span>p17) <span class="co">#Lo convertimos a numérica</span></span>
<span id="cb127-2"><a href="estadística-inferencial-ii.html#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(enades<span class="sc">$</span>p17) <span class="co"># Calculamos estadísticos de resumen de forma rápida.</span></span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu. 
##   1.000   1.000   5.000   4.571   7.000 
##    Max.    NA&#39;s 
##  10.000      23</code></pre>
<div id="pasos-previos" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Pasos previos<a href="estadística-inferencial-ii.html#pasos-previos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Cuál es la variable?</li>
</ul>
<p>Nivel de aceptación de la desigualdad en el Perú.</p>
<ul>
<li>Qué deseamos saber?</li>
</ul>
<p>Con nuestra muestra deseamos conocer el parámetro poblacional, es decir, la media de aceptación de la desigualdad en la población.</p>
</div>
<div id="estimación-puntual-1" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Estimación puntual<a href="estadística-inferencial-ii.html#estimación-puntual-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El estimador puntual es una estadística descriptiva que se utiliza para estimar el valor desconocido de un parámetro poblacional a partir de una muestra. El estimador puntual proporciona una única estimación del valor del parámetro y se calcula a partir de los datos de la muestra.</p>
<p>En este caso, la mejor estimación de la media población es simplemente la media muestral.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="estadística-inferencial-ii.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(enades<span class="sc">$</span>p17, <span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="co">#Calculamos la media, obviando valores perdidos. </span></span></code></pre></div>
<pre><code>## [1] 4.571334</code></pre>
</div>
<div id="ic-para-una-media" class="section level3 hasAnchor" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> IC para una media<a href="estadística-inferencial-ii.html#ic-para-una-media" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora, una vez identificado el estimador puntual, podemos cambiar nuestra estimación, ahora utilizando intervalos.</p>
<p>La clase pasada lo hicimos con la fórmula, paso por paso. Ahora, utilizaremos una función:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="estadística-inferencial-ii.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(lsr) #Recuerda que esta función está en el paquete lsr</span></span>
<span id="cb131-2"><a href="estadística-inferencial-ii.html#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ciMean</span>(enades<span class="sc">$</span>p17, <span class="at">na.rm =</span> T) <span class="co"># Calculamos el intervalo de confianza de p17, obviando valores perdidos. </span></span></code></pre></div>
<pre><code>##          2.5%    97.5%
## [1,] 4.413023 4.729645</code></pre>
</div>
<div id="ic-para-una-media-según-grupos" class="section level3 hasAnchor" number="5.1.4">
<h3><span class="header-section-number">5.1.4</span> IC para una media según grupos<a href="estadística-inferencial-ii.html#ic-para-una-media-según-grupos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora bien, en la mayoría de casos lo que deseamos es comparar grupos poblacionales. Por ejemplo:</p>
<ul>
<li><p>Quién gana en promedio más dinero, los hombres o las mujeres?</p></li>
<li><p>Quién apoya más, en promedio, a la democracia, los de la zona A o la zona B?</p></li>
<li><p>Entre otros.</p></li>
</ul>
<p>Lo primero que necesitamos para comparar es justamente un grupo de comparación. Ya hablando en programación del R, necesitamos un <strong>factor</strong>.</p>
<p>Recuerda que el factor era una variable que visualmente son números, pero teóricamente sabemos que cada número es un nivel.</p>
<p>Utilizaremos la variable zona3, la cual separa a los encuestados según su procedencia en: Lima Metropolitana y Perú sin Lima.</p>
<p>Veamos:</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="estadística-inferencial-ii.html#cb133-1" aria-hidden="true" tabindex="-1"></a>enades<span class="sc">$</span>zona3<span class="ot">&lt;-</span><span class="fu">factor</span>(enades<span class="sc">$</span>zona3, <span class="co"># Nombre de la variable a convertir</span></span>
<span id="cb133-2"><a href="estadística-inferencial-ii.html#cb133-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="co"># Definimos los niveles (esta variable sólo tenía 2 niveles)</span></span>
<span id="cb133-3"><a href="estadística-inferencial-ii.html#cb133-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Lima Metropolitana&quot;</span>, <span class="st">&quot;Perú sin Lima&quot;</span>)) <span class="co">#Colocamos sus etiquetas</span></span>
<span id="cb133-4"><a href="estadística-inferencial-ii.html#cb133-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-5"><a href="estadística-inferencial-ii.html#cb133-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Con este comando hemos sobreescrito la variable zona3. Ahora lo que inicialmente era una variable numérica, ahora es un factor. </span></span></code></pre></div>
<p>Corroboremos:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="estadística-inferencial-ii.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(enades<span class="sc">$</span>zona3) <span class="co">#Solicitamos la estructura de la variable zona3</span></span></code></pre></div>
<pre><code>##  Factor w/ 2 levels &quot;Lima Metropolitana&quot;,..: 1 1 2 2 2 2 2 2 2 2 ...</code></pre>
<p>Solicitemos el intervalo de confianza de la variable p17 para cada grupo identificado:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="estadística-inferencial-ii.html#cb136-1" aria-hidden="true" tabindex="-1"></a>p17_segun_zona<span class="ot">&lt;-</span>enades <span class="sc">%&gt;%</span> </span>
<span id="cb136-2"><a href="estadística-inferencial-ii.html#cb136-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(zona3) <span class="sc">%&gt;%</span> <span class="co">#Agrupamos por zona</span></span>
<span id="cb136-3"><a href="estadística-inferencial-ii.html#cb136-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(p17, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co">#Utilizamos summarise y pedimos la media,</span></span>
<span id="cb136-4"><a href="estadística-inferencial-ii.html#cb136-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">ci_lower =</span> <span class="fu">ciMean</span>(p17, <span class="at">na.rm =</span> T)[<span class="dv">1</span>], <span class="co"># También el PRIMER ELEMENTO de la función ciMean</span></span>
<span id="cb136-5"><a href="estadística-inferencial-ii.html#cb136-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">ci_upper =</span> <span class="fu">ciMean</span>(p17, <span class="at">na.rm =</span> T)[<span class="dv">2</span>]) <span class="co">#Y el SEGUNDO ELEMENTO de la función ciMean</span></span></code></pre></div>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="estadística-inferencial-ii.html#cb137-1" aria-hidden="true" tabindex="-1"></a>p17_segun_zona</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   zona3               mean ci_lower ci_upper
##   &lt;fct&gt;              &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Lima Metropolitana  4.36     4.10     4.62
## 2 Perú sin Lima       4.69     4.49     4.89</code></pre>
<p>Según el cálculo, para Lima Metropolitana la media poblacional se encuentra entre 4.09 y 4.62, mientras que para Perú sin Lima se encuentra entre 4.48 y 4.88.</p>
</div>
<div id="barras-de-error" class="section level3 hasAnchor" number="5.1.5">
<h3><span class="header-section-number">5.1.5</span> Barras de error<a href="estadística-inferencial-ii.html#barras-de-error" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En el contexto de intervalos de confianza, las barras de error se utilizan para representar el nivel de incertidumbre en una estimación puntual del parámetro poblacional. Un intervalo de confianza es un rango de valores plausible para el valor del parámetro poblacional, y se construye a partir de una muestra aleatoria y un nivel de confianza específico.</p>
<p>Las barras de error en un gráfico de intervalos de confianza se construyen a partir de los límites superior e inferior del intervalo de confianza. Generalmente se dibujan líneas verticales que se extienden desde el valor estimado del parámetro (que puede ser una media, una proporción, una diferencia de medias, etc.) hasta los límites del intervalo de confianza.</p>
<p>Por ejemplo, si se estima la media de una variable a partir de una muestra y se desea construir un intervalo de confianza al 95%, las barras de error se construirán a partir del límite inferior y superior del intervalo de confianza, que contendrán el verdadero valor de la media poblacional con una probabilidad del 95%.</p>
<p>Las barras de error en un gráfico de intervalos de confianza pueden ser útiles para comparar la precisión de las estimaciones entre diferentes grupos o condiciones. Si las barras de error son muy pequeñas, esto sugiere que la estimación es muy precisa y que hay una alta confianza en la validez del intervalo de confianza. Por otro lado, si las barras de error son grandes, esto sugiere que la estimación es menos precisa y que hay una mayor incertidumbre en el intervalo de confianza.</p>
<p>Podemos utilizar un comando básico como la función <code>plotmeans()</code>:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="estadística-inferencial-ii.html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gplots)</span>
<span id="cb139-2"><a href="estadística-inferencial-ii.html#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotmeans</span>(enades<span class="sc">$</span>p17<span class="sc">~</span>enades<span class="sc">$</span>zona3, <span class="at">p=</span><span class="fl">0.95</span>, </span>
<span id="cb139-3"><a href="estadística-inferencial-ii.html#cb139-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab=</span><span class="st">&quot;Ámbito&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Aceptación desigualdad&quot;</span>, </span>
<span id="cb139-4"><a href="estadística-inferencial-ii.html#cb139-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">main=</span><span class="st">&quot;Gráfico de medias de Aceptación de la desigualdad en el Perú&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>Sin embargo, te recomiendo utilizar <code>ggplot()</code>!</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="estadística-inferencial-ii.html#cb140-1" aria-hidden="true" tabindex="-1"></a>p17_segun_zona <span class="sc">|&gt;</span> <span class="co">#Data</span></span>
<span id="cb140-2"><a href="estadística-inferencial-ii.html#cb140-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span>       <span class="co">#Iniciamos el ggplot. A partir de ahora son +! ya no |&gt;!</span></span>
<span id="cb140-3"><a href="estadística-inferencial-ii.html#cb140-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">y=</span>mean, <span class="at">x=</span>zona3)<span class="sc">+</span>  <span class="co">#Los grupos en el eje X y la media en el eje Y</span></span>
<span id="cb140-4"><a href="estadística-inferencial-ii.html#cb140-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>ci_lower, <span class="at">ymax=</span>ci_upper), <span class="at">width=</span><span class="fl">0.2</span>)<span class="sc">+</span> <span class="co">#Graficamos la barra de error</span></span>
<span id="cb140-5"><a href="estadística-inferencial-ii.html#cb140-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">paste</span>(<span class="fu">round</span>(mean, <span class="dv">2</span>))), <span class="at">vjust=</span><span class="dv">0</span>, <span class="at">size=</span><span class="dv">5</span>)<span class="sc">+</span> <span class="co">#Colocamos el texto del valor de la media</span></span>
<span id="cb140-6"><a href="estadística-inferencial-ii.html#cb140-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Procedencia&quot;</span>) <span class="sc">+</span> <span class="co">#Etiqueta del eje X</span></span>
<span id="cb140-7"><a href="estadística-inferencial-ii.html#cb140-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Nivel de aceptación de la desigualdad&quot;</span>) <span class="co"># Etiqueta del eje y</span></span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-120-1.png" width="672" /></p>
<blockquote>
<p>Una guía: Se superponen los intervalos?</p>
</blockquote>
<p>Si los intervalos de confianza se superponen significa que no hay una diferencia estadísticamente significativa entre las estimaciones correspondientes a cada intervalo. Es decir, la diferencia entre las estimaciones no es lo suficientemente grande como para ser considerada significativa desde un punto de vista estadístico.</p>
<p><strong>IMPORTANTE!!</strong></p>
<p><strong>Es importante tener en cuenta que la superposición de los intervalos de confianza no es una prueba concluyente de que no hay una diferencia significativa entre las estimaciones. Se debe realizar una prueba de hipótesis para determinar si la diferencia es estadísticamente significativa o no. Sin embargo, la superposición de los intervalos de confianza puede ser una indicación inicial de que la diferencia no es significativa y que no se debe buscar más evidencia.</strong></p>
</div>
<div id="ahora-hazlo-tú" class="section level3 hasAnchor" number="5.1.6">
<h3><span class="header-section-number">5.1.6</span> Ahora hazlo tú!<a href="estadística-inferencial-ii.html#ahora-hazlo-tú" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cree un .Rmd y realice lo siguiente:</p>
<p>Utilizando la variable monto mínimo mensual que requiere su hogar para vivir (P08).</p>
<p>Calcule:</p>
<ul>
<li><p>Brinde el estimador puntual de la media poblacional.</p></li>
<li><p>Calcule el intervalo de confianza de la media poblacional.</p></li>
<li><p>Calcule los intervalos de confianza de la media según si el individuo vive en el área urbana o rural (area2). En otras palabras, compare la media de la variable en esos dos grupos.</p></li>
<li><p>Realice un gráfico de barras de error. Existe indicio de DIFERENCIA entre los dos grupos?</p></li>
</ul>
<blockquote>
<p>Tienes 15 minutos!</p>
</blockquote>
</div>
</div>
<div id="intervalo-de-una-proporción" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Intervalo de una proporción<a href="estadística-inferencial-ii.html#intervalo-de-una-proporción" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="definición-1" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Definición<a href="estadística-inferencial-ii.html#definición-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En estadística, el intervalo de una proporción es un rango de valores posibles para la proporción de una característica en una población, que se estima a partir de una muestra aleatoria de la población. Al igual que con la media, el intervalo de una proporción se construye utilizando un nivel de confianza específico y se utiliza para determinar la precisión de la estimación de la proporción en la población.</p>
<p>Por ejemplo, si se desea estimar la proporción de personas en una población que votará por un candidato específico, se puede seleccionar una muestra aleatoria de la población y estimar la proporción de personas que votarán por ese candidato en la muestra. A partir de esta estimación, se puede construir un intervalo de confianza que contendrá el valor real de la proporción en la población con un cierto nivel de confianza.</p>
<p>El ancho del intervalo depende del tamaño de la muestra y del nivel de confianza especificado. A medida que el tamaño de la muestra aumenta, el intervalo se estrecha y se vuelve más preciso. Del mismo modo, a medida que se aumenta el nivel de confianza, el intervalo se amplía y se vuelve menos preciso.</p>
<p>El intervalo de una proporción es una herramienta útil en la inferencia estadística, ya que permite a los investigadores cuantificar la incertidumbre en una estimación de la proporción y determinar si una diferencia entre dos proporciones es estadísticamente significativa.</p>
</div>
<div id="fórmula" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Fórmula<a href="estadística-inferencial-ii.html#fórmula" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Recuerda que en este caso, al igual que en la media, todo gira en torno a los principios de la curva normal, el número de desviaciones estándar/errores estándar a la izquierda y a la derecha, el teorema central del límite y la ley de los grandes números. Si alguno de estos conceptos no están claros, te recomiendo regresar a la sesión 4 y repasarlos!</p>
</blockquote>
<p>Para calcular el intervalo de confianza de una proporción variamos un poco la fórmula que ya conocemos hasta ahora.</p>
<p>Primero hay que tener en cuenta que cuando calculamos la proporción, nos estamos refiriendo específicamente a la proporción de <strong>UNA CATEGORÍA</strong> de una variable <strong>CATEGÓRICA</strong>. Hago el énfasis en ello porque siempre se genera la confusión de “a qué le estoy calculando la proporción”.</p>
<p>Dicho de otra manera, nosotros debemos poner el ojo en una categoría de una variable nominal/ordinal al principio de este cálculo.</p>
<p><span class="math display">\[\text{Intervalo de confianza para una proporción: } \hat{p} \pm z \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<p>Donde:</p>
<p><span class="math inline">\(\hat{p}\)</span> = Proporción muestral de la categoría elegida</p>
<p>z = Puntuación crítica dependiendo de nuestro nivel de confianza elegido</p>
<p><span class="math inline">\(\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span> = Error estándar de una proporción</p>
</div>
<div id="ic-de-proporción-con-la-fórmula" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> IC de proporción con la fórmula<a href="estadística-inferencial-ii.html#ic-de-proporción-con-la-fórmula" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Primero ubiquemos una variable categórica. Utilicemos la p11.1:</p>
<p>¿Qué tan desigual es el acceso de los peruanos a la EDUCACIÓN?
1. Muy desigual
2. Poco desigual
3. Nada desigual</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="estadística-inferencial-ii.html#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Configuramos nuestra variable como factor</span></span>
<span id="cb141-2"><a href="estadística-inferencial-ii.html#cb141-2" aria-hidden="true" tabindex="-1"></a>enades<span class="sc">$</span>p11<span class="fl">.1</span><span class="ot">&lt;-</span><span class="fu">factor</span>(enades<span class="sc">$</span>p11<span class="fl">.1</span>, <span class="co"># Nombre de la variable a convertir</span></span>
<span id="cb141-3"><a href="estadística-inferencial-ii.html#cb141-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="co"># Definimos los niveles (esta variable sólo tenía 2 niveles)</span></span>
<span id="cb141-4"><a href="estadística-inferencial-ii.html#cb141-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Muy desigual&quot;</span>, <span class="st">&quot;Poco desigual&quot;</span>, <span class="st">&quot;Nada desigual&quot;</span>)) <span class="co">#Colocamos sus etiquetas</span></span></code></pre></div>
<p>La muestra se divide entre estas tres opciones. Ahora elegimos <strong>UNA CATEGORÍA</strong> de estas tres a la que vamos a calcular la proporción. En este caso vamos a elegir la proporción de individuos que afirmó que el acceso a la educación en el Perú es “Muy desigual”.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="estadística-inferencial-ii.html#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculamos p</span></span>
<span id="cb142-2"><a href="estadística-inferencial-ii.html#cb142-2" aria-hidden="true" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb142-3"><a href="estadística-inferencial-ii.html#cb142-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb142-4"><a href="estadística-inferencial-ii.html#cb142-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p=</span>n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   p11.1             n      p
##   &lt;fct&gt;         &lt;int&gt;  &lt;dbl&gt;
## 1 Muy desigual    912 0.596 
## 2 Poco desigual   503 0.329 
## 3 Nada desigual    80 0.0523
## 4 &lt;NA&gt;             35 0.0229</code></pre>
<p>Ahora sabemos que nuestro <span class="math inline">\(\hat{p}\)</span> = 0.59</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="estadística-inferencial-ii.html#cb144-1" aria-hidden="true" tabindex="-1"></a>p<span class="ot">&lt;-</span><span class="fl">0.5961</span></span></code></pre></div>
<p>El número total de casos es:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="estadística-inferencial-ii.html#cb145-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span> <span class="dv">1530</span></span></code></pre></div>
<p>Ahora definimos la puntuación crítica. Cuánto era para 95% de confianza?</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="estadística-inferencial-ii.html#cb146-1" aria-hidden="true" tabindex="-1"></a>z<span class="ot">&lt;-</span><span class="fl">1.96</span></span></code></pre></div>
<p>Ahora el error estándar <span class="math inline">\(\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span></p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="estadística-inferencial-ii.html#cb147-1" aria-hidden="true" tabindex="-1"></a>error_estandar<span class="ot">&lt;-</span> <span class="fu">sqrt</span>((p<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p))<span class="sc">/</span>n)</span></code></pre></div>
<p>Nuestro límite inferior es la proporción muestral menos z*error estándar:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="estadística-inferencial-ii.html#cb148-1" aria-hidden="true" tabindex="-1"></a>limite_inferior<span class="ot">&lt;-</span> p<span class="sc">-</span>z<span class="sc">*</span>error_estandar</span>
<span id="cb148-2"><a href="estadística-inferencial-ii.html#cb148-2" aria-hidden="true" tabindex="-1"></a>limite_inferior</span></code></pre></div>
<pre><code>## [1] 0.5715129</code></pre>
<p>Y el límite superior es la proporción muestral más z*error estándar:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="estadística-inferencial-ii.html#cb150-1" aria-hidden="true" tabindex="-1"></a>limite_superior<span class="ot">&lt;-</span> p<span class="sc">+</span>z<span class="sc">*</span>error_estandar</span>
<span id="cb150-2"><a href="estadística-inferencial-ii.html#cb150-2" aria-hidden="true" tabindex="-1"></a>limite_superior</span></code></pre></div>
<pre><code>## [1] 0.6206871</code></pre>
<p>Lo podemos colocar todo en un data frame</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="estadística-inferencial-ii.html#cb152-1" aria-hidden="true" tabindex="-1"></a>resultados<span class="ot">&lt;-</span><span class="fu">data.frame</span>(p, error_estandar, limite_inferior, limite_superior)</span>
<span id="cb152-2"><a href="estadística-inferencial-ii.html#cb152-2" aria-hidden="true" tabindex="-1"></a>resultados <span class="sc">|&gt;</span> </span>
<span id="cb152-3"><a href="estadística-inferencial-ii.html#cb152-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">|&gt;</span> </span>
<span id="cb152-4"><a href="estadística-inferencial-ii.html#cb152-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
p
</th>
<th style="text-align:right;">
error_estandar
</th>
<th style="text-align:right;">
limite_inferior
</th>
<th style="text-align:right;">
limite_superior
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.5961
</td>
<td style="text-align:right;">
0.0125444
</td>
<td style="text-align:right;">
0.5715129
</td>
<td style="text-align:right;">
0.6206871
</td>
</tr>
</tbody>
</table>
</div>
<div id="ic-de-proporción-con-prop.test" class="section level3 hasAnchor" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> IC de proporción con <code>prop.test()</code><a href="estadística-inferencial-ii.html#ic-de-proporción-con-prop.test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora bien, también podemos utilizar la función <code>prop.test()</code>:</p>
<p>Recordemos:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="estadística-inferencial-ii.html#cb153-1" aria-hidden="true" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb153-2"><a href="estadística-inferencial-ii.html#cb153-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb153-3"><a href="estadística-inferencial-ii.html#cb153-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p=</span>n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   p11.1             n      p
##   &lt;fct&gt;         &lt;int&gt;  &lt;dbl&gt;
## 1 Muy desigual    912 0.596 
## 2 Poco desigual   503 0.329 
## 3 Nada desigual    80 0.0523
## 4 &lt;NA&gt;             35 0.0229</code></pre>
<p>Colocamos la <strong>frecuencia</strong> de la categoría elegida y el tamaño total de la muestra.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="estadística-inferencial-ii.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">912</span>, <span class="dv">1530</span>)<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 0.5709514 0.6207178
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<blockquote>
<p>Por qué colocamos frecuencia? Porque así está configurada esta función.</p>
</blockquote>
</div>
<div id="ic-de-proporción-según-grupos" class="section level3 hasAnchor" number="5.2.5">
<h3><span class="header-section-number">5.2.5</span> IC de proporción según grupos<a href="estadística-inferencial-ii.html#ic-de-proporción-según-grupos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora comparemos la proporción elegida (aquellos que creen que el acceso de los peruanos a la EDUCACIÓN es MUY DESIGUAL) entre el sector rural y urbano (area2).</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="estadística-inferencial-ii.html#cb157-1" aria-hidden="true" tabindex="-1"></a>enades<span class="sc">$</span>area2<span class="ot">&lt;-</span> <span class="fu">factor</span>(enades<span class="sc">$</span>area2, <span class="co"># Nombre de la variable a convertir</span></span>
<span id="cb157-2"><a href="estadística-inferencial-ii.html#cb157-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="co"># Definimos los niveles (esta variable sólo tenía 2 niveles)</span></span>
<span id="cb157-3"><a href="estadística-inferencial-ii.html#cb157-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Urbano&quot;</span>, <span class="st">&quot;Rural&quot;</span>)) <span class="co">#Colocamos sus etiquetas</span></span></code></pre></div>
<p>Primero, nos tenemos que preguntar cuál es la frecuencia en cada grupo</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="estadística-inferencial-ii.html#cb158-1" aria-hidden="true" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb158-2"><a href="estadística-inferencial-ii.html#cb158-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(area2) <span class="sc">|&gt;</span> </span>
<span id="cb158-3"><a href="estadística-inferencial-ii.html#cb158-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb158-4"><a href="estadística-inferencial-ii.html#cb158-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p=</span>n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 8 × 4
## # Groups:   area2 [2]
##   area2  p11.1             n      p
##   &lt;fct&gt;  &lt;fct&gt;         &lt;int&gt;  &lt;dbl&gt;
## 1 Urbano Muy desigual    769 0.604 
## 2 Urbano Poco desigual   409 0.321 
## 3 Urbano Nada desigual    67 0.0526
## 4 Urbano &lt;NA&gt;             28 0.0220
## 5 Rural  Muy desigual    143 0.556 
## 6 Rural  Poco desigual    94 0.366 
## 7 Rural  Nada desigual    13 0.0506
## 8 Rural  &lt;NA&gt;              7 0.0272</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="estadística-inferencial-ii.html#cb160-1" aria-hidden="true" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb160-2"><a href="estadística-inferencial-ii.html#cb160-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(area2)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   area2      n
##   &lt;fct&gt;  &lt;int&gt;
## 1 Urbano  1273
## 2 Rural    257</code></pre>
<p>Ahora calculamos la función teniendo en cuenta que:</p>
<ul>
<li>En el primer grupo hay 769 casos de éxito de un total de 1273.</li>
</ul>
<p>Lo ingresamos a la función:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="estadística-inferencial-ii.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">769</span>), <span class="at">n=</span><span class="fu">c</span>(<span class="dv">1273</span>))<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 0.5765493 0.6309849
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<ul>
<li>En el segundo grupo hay 143 casos de éxito de un total de 257.</li>
</ul>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="estadística-inferencial-ii.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">143</span>), <span class="at">n=</span><span class="fu">c</span>(<span class="dv">257</span>))<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 0.4933505 0.6177753
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>Lo podemos ordenar en un data.frame.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="estadística-inferencial-ii.html#cb166-1" aria-hidden="true" tabindex="-1"></a>resultados_prop<span class="ot">&lt;-</span>  <span class="fu">data.frame</span>(<span class="at">Grupo =</span><span class="fu">c</span>(<span class="st">&quot;Urbano&quot;</span>, <span class="st">&quot;Rural&quot;</span>), </span>
<span id="cb166-2"><a href="estadística-inferencial-ii.html#cb166-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">P =</span><span class="fu">c</span>(<span class="fl">0.60</span>, <span class="fl">0.55</span>), </span>
<span id="cb166-3"><a href="estadística-inferencial-ii.html#cb166-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Lim_inf=</span><span class="fu">c</span>(<span class="fl">0.57</span>, <span class="fl">0.49</span>), </span>
<span id="cb166-4"><a href="estadística-inferencial-ii.html#cb166-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Lim_sup=</span> <span class="fu">c</span>(<span class="fl">0.63</span>,<span class="fl">0.61</span>))</span></code></pre></div>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="estadística-inferencial-ii.html#cb167-1" aria-hidden="true" tabindex="-1"></a>resultados_prop</span></code></pre></div>
<pre><code>##    Grupo    P Lim_inf Lim_sup
## 1 Urbano 0.60    0.57    0.63
## 2  Rural 0.55    0.49    0.61</code></pre>
<p>Lo visualizamos:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="estadística-inferencial-ii.html#cb169-1" aria-hidden="true" tabindex="-1"></a>resultados_prop <span class="sc">|&gt;</span> <span class="co">#Data</span></span>
<span id="cb169-2"><a href="estadística-inferencial-ii.html#cb169-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span>       <span class="co">#Iniciamos el ggplot. A partir de ahora son +! ya no |&gt;!</span></span>
<span id="cb169-3"><a href="estadística-inferencial-ii.html#cb169-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">y=</span>p, <span class="at">x=</span>Grupo)<span class="sc">+</span>  <span class="co">#Los grupos en el eje X y la media en el eje Y</span></span>
<span id="cb169-4"><a href="estadística-inferencial-ii.html#cb169-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>Lim_inf, <span class="at">ymax=</span>Lim_sup), <span class="at">width=</span><span class="fl">0.2</span>)<span class="sc">+</span> <span class="co">#Graficamos la barra de error</span></span>
<span id="cb169-5"><a href="estadística-inferencial-ii.html#cb169-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Procedencia&quot;</span>) <span class="sc">+</span> <span class="co">#Etiqueta del eje X</span></span>
<span id="cb169-6"><a href="estadística-inferencial-ii.html#cb169-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;P la cobertura en educación es Muy Desigual&quot;</span>) <span class="co"># Etiqueta del eje y</span></span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-139-1.png" width="672" /></p>
<p>Otra alternativa es pedirlos al mismo tiempo en la función <code>prop.test()</code>. En este caso lo que nos muestra, es el <strong>intervalo de la diferencia</strong>.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="estadística-inferencial-ii.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">769</span>, <span class="dv">143</span>), <span class="at">n=</span><span class="fu">c</span>(<span class="dv">1273</span>, <span class="dv">257</span>))<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] -0.02108879  0.11641800
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>En este caso, se sigue la siguiente interpretación:</p>
<p>Si el intervalo de confianza no contiene el valor cero, esto sugiere que las proporciones de los dos grupos son significativamente diferentes y que la hipótesis nula de que las proporciones son iguales debe ser rechazada. Por otro lado, si el intervalo de confianza contiene el valor cero, no podemos rechazar la hipótesis nula y no podemos concluir que las proporciones son significativamente diferentes.</p>
</div>
<div id="ahora-hazlo-tú-1" class="section level3 hasAnchor" number="5.2.6">
<h3><span class="header-section-number">5.2.6</span> Ahora hazlo tú!<a href="estadística-inferencial-ii.html#ahora-hazlo-tú-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cree un .Rmd y realice lo siguiente:</p>
<p>Utilizando la variable “ideología2” (1: Izquierda, 2:Centro, 3:Derecha):</p>
<p>Realice lo siguiente:</p>
<ul>
<li><p>Brinde el estimador puntual de la proporción de población de Izquierda en el Perú.</p></li>
<li><p>Calcule el intervalo de confianza de la proporción poblacional de Izquierda en el Perú.</p></li>
<li><p>Calcule por separado, utilizando prop.test(), la proporción de población de izquierda en el área urbano y rural (area2).</p></li>
<li><p>Mediante la función prop.test(), compare los dos grupos y evalúe el intervalo de confianza de la diferencia en los p poblacionales.</p></li>
</ul>
</div>
</div>
<div id="prueba-de-hipótesis-introducción" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Prueba de hipótesis: Introducción<a href="estadística-inferencial-ii.html#prueba-de-hipótesis-introducción" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="definición-2" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Definición<a href="estadística-inferencial-ii.html#definición-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Una prueba de hipótesis es un método para determinar si una afirmación sobre una población es verdadera o falsa, basándose en la información obtenida de una muestra aleatoria de la población. Este enfoque proporciona una forma sistemática y rigurosa para tomar decisiones informadas y hacer inferencias sobre la población en función de la evidencia empírica.</p>
<p>Para aplicar una prueba debemos seguir pasos muy ordenados y entender qué estamos haciendo en cada uno de ellos.</p>
<p><img src="figures/prueba_pasos.png" /></p>
<blockquote>
<p>En términos referenciales, es como seguir un proceso de investigación policial! Vamos a utilizar esta analogía!</p>
</blockquote>
<p><img src="figures/detective.jpg" /></p>
</div>
<div id="paso-1-establer-hipótesis" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Paso 1: Establer hipótesis<a href="estadística-inferencial-ii.html#paso-1-establer-hipótesis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>En este punto somos como detectives (como Benoit Blanc en Knives Out) y estas son nuestras hipótesis de investigación. Si vamos a investigar un crimen partimos con la H0 que la persona investigada es inocente. Nuestra hipótesis alterna es que es culpable!</p>
</blockquote>
<p>Las hipótesis son afirmaciones o suposiciones acerca de una población o de un conjunto de datos que se pretende analizar.</p>
<p>En el contexto de las pruebas de hipótesis, se suelen plantear dos hipótesis: la hipótesis nula (H0) y la hipótesis alternativa (H1). La hipótesis nula establece que no hay diferencia significativa entre las muestras o poblaciones que se están comparando, mientras que la hipótesis alternativa indica que sí existe una diferencia significativa.</p>
<table>
<colgroup>
<col width="45%" />
<col width="54%" />
</colgroup>
<thead>
<tr class="header">
<th>Hipótesis</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hipótesis nula (H0)</td>
<td>Es una afirmación que se establece inicialmente y que se asume verdadera a menos que se disponga de suficiente evidencia para rechazarla. La hipótesis nula generalmente establece que <strong>no hay diferencia significativa entre dos grupos</strong> o variables que se están comparando, o que no hay efecto de un tratamiento o una intervención.</td>
</tr>
<tr class="even">
<td>Hipótesis alternativa (H1)</td>
<td>Es la afirmación opuesta a la hipótesis nula y establece que <strong>sí hay una diferencia significativa entre los dos grupos</strong> o variables que se están comparando, o que sí hay un efecto de un tratamiento o intervención. La hipótesis alternativa se utiliza para probar lo que se espera demostrar si se rechaza la hipótesis nula.</td>
</tr>
</tbody>
</table>
<p>Tener en cuenta que la forma cómo planteamos nuestras hipótesis va a repercutir en todo el flujograma.</p>
</div>
<div id="paso-2-verificar-supuestos" class="section level3 hasAnchor" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> Paso 2: Verificar supuestos<a href="estadística-inferencial-ii.html#paso-2-verificar-supuestos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="figures/detective_escena.jpg" /></p>
<blockquote>
<p>Antes de ver los hechos, debemos ver el contexto en el cual se encuentran. No es lo mismo que el crimen se realice en una casa o al aire libre. Entender previamente estas características nos permitirá investigar mejor! Es nuestra escena del crimen!</p>
</blockquote>
<p>Recuerdas todos los principios de la curva normal, desviaciones estándar, errores estándar (en el caso de las distribuciones muestrales), etc? Eso también se aplica aquí.</p>
<p>Partimos de la idea de que si se extraen muchas muestras repetidas (como en la clase anterior), los estadísticos muestrales se centrarán alrededor de un valor con una distribución aproximadamente normal.</p>
<p>En este caso debemos corroborar ciertas características de la distribución de nuestra muestra. Algunas de estas:</p>
<ul>
<li><p>Que las variables provengan de una distribución gaussiana o normal.</p></li>
<li><p>Que las varianzas poblacionales sean iguales. Es decir, que la curva de distribución muestral en cada grupo analizado sea homogénea. Si son iguales, el camino de la investigación se dirigirá por un lado, si es diferente irá por otro.</p></li>
</ul>
</div>
<div id="paso-3-establecer-nivel-de-significancia" class="section level3 hasAnchor" number="5.3.4">
<h3><span class="header-section-number">5.3.4</span> Paso 3: Establecer nivel de significancia<a href="estadística-inferencial-ii.html#paso-3-establecer-nivel-de-significancia" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Cuando investigamos un crimen debemos cotejar el comportamiento del investigado frente a una actitud vista como normal o regular. Si encontramos que el investigado asistía a lugares muy fuera de su rutina puede ser un indicio!</p>
</blockquote>
<p>Como en el caso del intervalo de confianza, elegir el nivel de confianza con el que estamos trabajando es vital.</p>
<p>El nivel de significancia en una prueba de hipótesis es la probabilidad máxima de que un resultado observado sea producto del azar, es decir, que no haya una diferencia real entre las muestras o poblaciones que se están comparando. Es un valor establecido previamente por el investigador antes de realizar la prueba de hipótesis y representa el umbral a partir del cual se considera que los resultados son estadísticamente significativos (o en nuestro caso, a partir de qué punto catalogamos un hecho como sospechoso).</p>
<p>Por ejemplo, si se realiza una prueba de hipótesis con un nivel de significancia del 5%, esto significa que hay una probabilidad máxima del 5% de que los resultados observados se deban al azar, y que hay una diferencia real entre las muestras o poblaciones que se están comparando. En otras palabras, si el valor p obtenido en la prueba de hipótesis es menor que el nivel de significancia establecido, se rechaza la hipótesis nula y se concluye que hay evidencia suficiente para aceptar la hipótesis alternativa.</p>
<blockquote>
<p>Por ejemplo, si investigamos un robo y nos damos cuenta que el sospechoso, que había vivido toda su vida en Lima y nunca había viajado a ningún departamento, justamente había decidido mudarse a Europa a los pocos días de acontecido el robo.</p>
</blockquote>
<p>Es importante destacar que el nivel de significancia elegido puede tener un impacto en la interpretación de los resultados y que, en última instancia, es el investigador quien debe decidir el nivel adecuado en función del contexto de la investigación y del grado de incertidumbre que esté dispuesto a asumir.</p>
</div>
<div id="paso-4-aplicar-test-estadístico-y-obtener-p-value" class="section level3 hasAnchor" number="5.3.5">
<h3><span class="header-section-number">5.3.5</span> Paso 4: Aplicar test estadístico y obtener p-value<a href="estadística-inferencial-ii.html#paso-4-aplicar-test-estadístico-y-obtener-p-value" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Ahora debemos recopilar evidencia!</p>
</blockquote>
<p><img src="figures/detective_rastro.jpg" /></p>
<p>Tenemos que identificar el comportamiento extraño, pero para eso debemos saber cuál es el comportamiento normal.</p>
<p>En estadística, el <strong>comportamiento</strong> normal nos lo entrega un test estadístico. Este nos brinda un <strong>estadístico de prueba</strong>, el cual va a ser la referencia con la cual vamos a medir la rareza de lo que encontramos en la práctica en nuestra data.</p>
<p>Antes de seguir te pido que recuerdes esto:</p>
<p><img src="figures/ejemplo_paso4.png" />
Ok, ahora sí. El test estadístico lo que te indica es cuál es el valor de umbral a la confianza elegida, pero en términos de EE (en el ejemplo de arriba, sería 20).</p>
<p>Luego de eso, tomandolo como referencia, te dice qué tan raro es el estadístico <strong>OBSERVADO</strong> en tu muestra y te brinda la probabilidad de que eso ocurriese. Esa probabilidad es tu p-valor.</p>
<p>En el ejemplo anterior, sabemos que 59 o 141 estaban dentro de ese otro 5% de probabilidad. Sin embargo, el test estadístico nos da la <strong>probabilidad exacta</strong>, esta probabilidad exacta se llama <strong>p-valor</strong>.</p>
</div>
<div id="paso-5-tomar-una-decisión" class="section level3 hasAnchor" number="5.3.6">
<h3><span class="header-section-number">5.3.6</span> Paso 5: Tomar una decisión<a href="estadística-inferencial-ii.html#paso-5-tomar-una-decisión" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Ahora, de acuerdo a la evidencia. Debes tomar una decisión. Si el evento es demasiado raro entonces tienes que rechazar la hipótesis nula (es inocente). Si el evento es normal entonces NO puedes rechazar una hipótesis nula.</p>
</blockquote>
<p><img src="figures/sospechoso.jpg" /></p>
<p>Si el p-valor es menor que el nivel de significancia establecido (por ejemplo, α = 0.05), se rechaza la hipótesis nula (H0: Medias iguales).</p>
<p>Si el p-valor es mayor que el nivel de significancia establecido NO rechazamos la hipótesis nula.</p>
<p>Es importante tener en cuenta que el p-valor no proporciona información sobre la magnitud de la diferencia observada entre las muestras o poblaciones que se están comparando, sino simplemente sobre la probabilidad de que los resultados observados sean producto del azar. Además, la interpretación del p-valor debe contextualizarse adecuadamente y no se debe basar únicamente en la regla general del nivel de significancia establecido.</p>
<p><img src="figures/pasos_pvalor.jpg" /></p>
<blockquote>
<p>OJO: EN TÉRMINOS ESTRICTOS NUNCA DECIMOS QUE <strong>ACEPTAMOS</strong> LA ALTERNATIVA.</p>
</blockquote>
</div>
<div id="paso-6-interpretación" class="section level3 hasAnchor" number="5.3.7">
<h3><span class="header-section-number">5.3.7</span> Paso 6: Interpretación<a href="estadística-inferencial-ii.html#paso-6-interpretación" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>El paso final de la investigación es dar tu conclusión como detective. Entonces decimos que con un 95% podemos rechazar que el sospechoso sea inocente, por lo que lo presentamos al Poder Judicial para que un juez dictamine la sentencia. Cumplimos con nuestro trabajo.</p>
</blockquote>
<p><img src="figures/JUEZ.jpg" /></p>
<p>El paso final es proporcionar una interpretación de los resultados.</p>
<p>Podemos utilizar el siguiente fraseo.</p>
<p>SI EL P-VALOR &lt;0.05</p>
<p>A un 95% de confianza, obtuvimos un p-valor de _____, por lo que rechazamos la hipótesis nula de que _______ y concluimos que existe _______ estadísticamente significativa.</p>
<p>SI EL P-VALOR &gt;=0.05</p>
<p>A un 95% de confianza, obtuvimos un p-valor de _____, por lo que <strong>NO</strong> rechazamos la hipótesis nula de que _______ y concluimos que <strong>NO</strong> existe _______ estadísticamente significativa.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estadística-inferencial-introducción.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estadística-inferencial-iii-comparación-en-dos-muestras-independientes.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ChristianChiroqueR/Estadistica_AP_1_PUCP/edit/master/05-inferencia_2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ChristianChiroqueR/Estadistica_AP_1_PUCP/blob/master/05-inferencia_2.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
