<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Sesión 5 IC para una media y una proporción, IC entre grupos | Estadística para el Análisis Político I</title>
  <meta name="description" content="Sesión 5 IC para una media y una proporción, IC entre grupos | Estadística para el Análisis Político I" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Sesión 5 IC para una media y una proporción, IC entre grupos | Estadística para el Análisis Político I" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Sesión 5 IC para una media y una proporción, IC entre grupos | Estadística para el Análisis Político I" />
  
  
  

<meta name="author" content="Docente: Christian Chiroque Ruiz" />


<meta name="date" content="2023-11-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introducción-a-la-estadística-inferencial-i.html"/>
<link rel="next" href="prueba-de-hipótesis-t.test-y-prop.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.2/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística AP I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción a Estadística con R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#estadística-los-fundamentos"><i class="fa fa-check"></i><b>1.1</b> Estadística: los fundamentos</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#unidad-de-análisis"><i class="fa fa-check"></i><b>1.1.1</b> Unidad de análisis</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#tipos-de-variables-y-escalas-de-medición"><i class="fa fa-check"></i><b>1.1.2</b> Tipos de variables y escalas de medición</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#r-los-fundamentos"><i class="fa fa-check"></i><b>1.2</b> R: los fundamentos</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#por-qué-r"><i class="fa fa-check"></i><b>1.2.1</b> ¿Por qué R?</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#poo"><i class="fa fa-check"></i><b>1.2.2</b> POO</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#los-objetos"><i class="fa fa-check"></i><b>1.2.3</b> Los objetos</a></li>
<li class="chapter" data-level="1.2.4" data-path="index.html"><a href="index.html#los-vectores"><i class="fa fa-check"></i><b>1.2.4</b> Los vectores</a></li>
<li class="chapter" data-level="1.2.5" data-path="index.html"><a href="index.html#los-factores"><i class="fa fa-check"></i><b>1.2.5</b> Los factores</a></li>
<li class="chapter" data-level="1.2.6" data-path="index.html"><a href="index.html#data-frames"><i class="fa fa-check"></i><b>1.2.6</b> Data frames</a></li>
<li class="chapter" data-level="1.2.7" data-path="index.html"><a href="index.html#índices"><i class="fa fa-check"></i><b>1.2.7</b> Índices</a></li>
<li class="chapter" data-level="1.2.8" data-path="index.html"><a href="index.html#nuestras-herramientas-paquetes-y-funciones"><i class="fa fa-check"></i><b>1.2.8</b> Nuestras herramientas: Paquetes y funciones</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#importación-y-exploración-de-datos"><i class="fa fa-check"></i><b>1.3</b> Importación y exploración de datos</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#verificar-el-tipo-de-variable"><i class="fa fa-check"></i><b>1.3.1</b> Verificar el tipo de variable</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html"><i class="fa fa-check"></i><b>2</b> Análisis exploratorio de datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-exploratorio-de-datos.html"><a href="análisis-exploratorio-de-datos.html#estadísticos-descriptivos"><i class="fa fa-check"></i><b>2.1</b> Estadísticos descriptivos</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html"><i class="fa fa-check"></i><b>3</b> Visualización de datos con ggplot2</a></li>
<li class="chapter" data-level="4" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html"><i class="fa fa-check"></i><b>4</b> Introducción a la Estadística Inferencial I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#objetivo-de-la-sesión"><i class="fa fa-check"></i><b>4.1</b> Objetivo de la sesión</a></li>
<li class="chapter" data-level="4.2" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#fundamentos"><i class="fa fa-check"></i><b>4.2</b> Fundamentos</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#inferencia"><i class="fa fa-check"></i><b>4.2.1</b> Inferencia</a></li>
<li class="chapter" data-level="4.2.2" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#la-desviación-estándar"><i class="fa fa-check"></i><b>4.2.2</b> La desviación estándar</a></li>
<li class="chapter" data-level="4.2.3" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#distribución-normal"><i class="fa fa-check"></i><b>4.2.3</b> Distribución normal</a></li>
<li class="chapter" data-level="4.2.4" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#teorema-del-límite-central"><i class="fa fa-check"></i><b>4.2.4</b> Teorema del límite central</a></li>
<li class="chapter" data-level="4.2.5" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#ley-de-los-grandes-números"><i class="fa fa-check"></i><b>4.2.5</b> Ley de los grandes números</a></li>
<li class="chapter" data-level="4.2.6" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#varias-muestras"><i class="fa fa-check"></i><b>4.2.6</b> Varias muestras</a></li>
<li class="chapter" data-level="4.2.7" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#error-estándar"><i class="fa fa-check"></i><b>4.2.7</b> Error estándar</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#métodos-de-estimación"><i class="fa fa-check"></i><b>4.3</b> Métodos de estimación</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#estimación-puntual"><i class="fa fa-check"></i><b>4.3.1</b> Estimación puntual</a></li>
<li class="chapter" data-level="4.3.2" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#intervalo-de-confianza-de-una-media"><i class="fa fa-check"></i><b>4.3.2</b> Intervalo de confianza de una media</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#ejercicio-1-enades-2022"><i class="fa fa-check"></i><b>4.4</b> Ejercicio 1: ENADES 2022</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#abrir-base-de-datos"><i class="fa fa-check"></i><b>4.4.1</b> Abrir base de datos</a></li>
<li class="chapter" data-level="4.4.2" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#identificar-una-variable-numérica"><i class="fa fa-check"></i><b>4.4.2</b> Identificar una variable numérica</a></li>
<li class="chapter" data-level="4.4.3" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#cálculo-del-estimador-puntual"><i class="fa fa-check"></i><b>4.4.3</b> Cálculo del estimador puntual</a></li>
<li class="chapter" data-level="4.4.4" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#cálculo-del-ic-al-95"><i class="fa fa-check"></i><b>4.4.4</b> Cálculo del IC al 95%</a></li>
<li class="chapter" data-level="4.4.5" data-path="introducción-a-la-estadística-inferencial-i.html"><a href="introducción-a-la-estadística-inferencial-i.html#barras-de-error"><i class="fa fa-check"></i><b>4.4.5</b> Barras de error</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><i class="fa fa-check"></i><b>5</b> IC para una media y una proporción, IC entre grupos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#objetivo-de-la-sesión."><i class="fa fa-check"></i><b>5.1</b> Objetivo de la sesión.</a></li>
<li class="chapter" data-level="5.2" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#índice-aditivo"><i class="fa fa-check"></i><b>5.2</b> Índice Aditivo</a></li>
<li class="chapter" data-level="5.3" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#intervalos-de-confianza-para-grupos"><i class="fa fa-check"></i><b>5.3</b> Intervalos de confianza para grupos</a></li>
<li class="chapter" data-level="5.4" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ejercicio-1"><i class="fa fa-check"></i><b>5.4</b> Ejercicio 1</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#pregunta-de-investigación"><i class="fa fa-check"></i><b>5.4.1</b> Pregunta de investigación</a></li>
<li class="chapter" data-level="5.4.2" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#creamos-el-índice-aditivo"><i class="fa fa-check"></i><b>5.4.2</b> Creamos el índice aditivo</a></li>
<li class="chapter" data-level="5.4.3" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cálculo-del-intervalo-de-confianza-al-95"><i class="fa fa-check"></i><b>5.4.3</b> Cálculo del intervalo de confianza al 95%</a></li>
<li class="chapter" data-level="5.4.4" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-para-una-media"><i class="fa fa-check"></i><b>5.4.4</b> IC para una media</a></li>
<li class="chapter" data-level="5.4.5" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-para-una-media-según-grupos"><i class="fa fa-check"></i><b>5.4.5</b> IC para una media según grupos</a></li>
<li class="chapter" data-level="5.4.6" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#visualización"><i class="fa fa-check"></i><b>5.4.6</b> Visualización</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ejercicio-2"><i class="fa fa-check"></i><b>5.5</b> Ejercicio 2</a></li>
<li class="chapter" data-level="5.6" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#intervalo-de-una-proporción"><i class="fa fa-check"></i><b>5.6</b> Intervalo de una proporción</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#definición"><i class="fa fa-check"></i><b>5.6.1</b> Definición</a></li>
<li class="chapter" data-level="5.6.2" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#fórmula"><i class="fa fa-check"></i><b>5.6.2</b> Fórmula</a></li>
<li class="chapter" data-level="5.6.3" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-de-proporción-con-la-fórmula"><i class="fa fa-check"></i><b>5.6.3</b> IC de proporción con la fórmula</a></li>
<li class="chapter" data-level="5.6.4" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-de-proporción-con-prop.test"><i class="fa fa-check"></i><b>5.6.4</b> IC de proporción con <code>prop.test()</code></a></li>
<li class="chapter" data-level="5.6.5" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-de-proporción-según-grupos"><i class="fa fa-check"></i><b>5.6.5</b> IC de proporción según grupos</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="ic-para-una-media-y-una-proporción-ic-entre-grupos.html"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ejercicio-3"><i class="fa fa-check"></i><b>5.7</b> Ejercicio 3</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html"><i class="fa fa-check"></i><b>6</b> Prueba de hipótesis: t.test y prop.test</a>
<ul>
<li class="chapter" data-level="6.1" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#prueba-de-hipótesis"><i class="fa fa-check"></i><b>6.1</b> Prueba de hipótesis</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-1-establecer-hipótesis"><i class="fa fa-check"></i><b>6.1.1</b> Paso 1: Establecer hipótesis</a></li>
<li class="chapter" data-level="6.1.2" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-2-verificar-supuestos"><i class="fa fa-check"></i><b>6.1.2</b> Paso 2: Verificar supuestos</a></li>
<li class="chapter" data-level="6.1.3" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-3-establecer-nivel-de-significancia"><i class="fa fa-check"></i><b>6.1.3</b> Paso 3: Establecer nivel de significancia</a></li>
<li class="chapter" data-level="6.1.4" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-4-aplicar-test-estadístico-y-obtener-p-value"><i class="fa fa-check"></i><b>6.1.4</b> Paso 4: Aplicar test estadístico y obtener p-value</a></li>
<li class="chapter" data-level="6.1.5" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-5-tomar-una-decisión"><i class="fa fa-check"></i><b>6.1.5</b> Paso 5: Tomar una decisión</a></li>
<li class="chapter" data-level="6.1.6" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-6-interpretación"><i class="fa fa-check"></i><b>6.1.6</b> Paso 6: Interpretación</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#tipos-error-posibles"><i class="fa fa-check"></i><b>6.2</b> Tipos error posibles</a></li>
<li class="chapter" data-level="6.3" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#tipos-de-prueba-de-hipótesis"><i class="fa fa-check"></i><b>6.3</b> Tipos de prueba de hipótesis</a></li>
<li class="chapter" data-level="6.4" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#diferencia-de-medias-t.test"><i class="fa fa-check"></i><b>6.4</b> Diferencia de medias (t.test)</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#pregunta-de-investigación-1"><i class="fa fa-check"></i><b>6.4.1</b> Pregunta de investigación</a></li>
<li class="chapter" data-level="6.4.2" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-0-análisis-exploratorio-de-datos-eda"><i class="fa fa-check"></i><b>6.4.2</b> Paso 0: Análisis exploratorio de datos (EDA)</a></li>
<li class="chapter" data-level="6.4.3" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-1-establecer-hipótesis-1"><i class="fa fa-check"></i><b>6.4.3</b> Paso 1: Establecer hipótesis</a></li>
<li class="chapter" data-level="6.4.4" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-2-verificar-supuestos-1"><i class="fa fa-check"></i><b>6.4.4</b> Paso 2: Verificar supuestos</a></li>
<li class="chapter" data-level="6.4.5" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-3-establecer-nivel-de-significancia-1"><i class="fa fa-check"></i><b>6.4.5</b> Paso 3: Establecer nivel de significancia</a></li>
<li class="chapter" data-level="6.4.6" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-4-calcular-estadístico-de-prueba-y-p-valor"><i class="fa fa-check"></i><b>6.4.6</b> Paso 4: Calcular estadístico de prueba y p-valor</a></li>
<li class="chapter" data-level="6.4.7" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-5-tomar-una-decisión-1"><i class="fa fa-check"></i><b>6.4.7</b> Paso 5: Tomar una decisión</a></li>
<li class="chapter" data-level="6.4.8" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#paso-6-interpretación-1"><i class="fa fa-check"></i><b>6.4.8</b> Paso 6: Interpretación</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#ejercicio-1-1"><i class="fa fa-check"></i><b>6.5</b> Ejercicio 1</a></li>
<li class="chapter" data-level="6.6" data-path="prueba-de-hipótesis-t.test-y-prop.html"><a href="prueba-de-hipótesis-t.test-y-prop.html#recuerda"><i class="fa fa-check"></i><b>6.6</b> Recuerda!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html"><i class="fa fa-check"></i><b>7</b> ANOVA: Comparación en más de dos muestras</a>
<ul>
<li class="chapter" data-level="7.1" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#recordemos"><i class="fa fa-check"></i><b>7.1</b> Recordemos</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#flujograma"><i class="fa fa-check"></i><b>7.1.1</b> Flujograma</a></li>
<li class="chapter" data-level="7.1.2" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#qué-sigue"><i class="fa fa-check"></i><b>7.1.2</b> Qué sigue?</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#anova-de-un-factor"><i class="fa fa-check"></i><b>7.2</b> ANOVA de un factor</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#pregunta-de-investigación-2"><i class="fa fa-check"></i><b>7.2.1</b> Pregunta de investigación</a></li>
<li class="chapter" data-level="7.2.2" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#paso-0-análisis-exploratorio-de-datos-eda-1"><i class="fa fa-check"></i><b>7.2.2</b> Paso 0: Análisis exploratorio de datos (EDA)</a></li>
<li class="chapter" data-level="7.2.3" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#paso-1-establecer-hipótesis-2"><i class="fa fa-check"></i><b>7.2.3</b> Paso 1: Establecer hipótesis</a></li>
<li class="chapter" data-level="7.2.4" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#paso-2-verificar-supuestos-2"><i class="fa fa-check"></i><b>7.2.4</b> Paso 2: Verificar supuestos</a></li>
<li class="chapter" data-level="7.2.5" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#paso-3-establecer-nivel-de-significancia-2"><i class="fa fa-check"></i><b>7.2.5</b> Paso 3: Establecer nivel de significancia</a></li>
<li class="chapter" data-level="7.2.6" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#paso-4-calcular-estadístico-de-prueba-y-p-valor-1"><i class="fa fa-check"></i><b>7.2.6</b> Paso 4: Calcular estadístico de prueba y p-valor</a></li>
<li class="chapter" data-level="7.2.7" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#paso-5-tomar-una-decisión-2"><i class="fa fa-check"></i><b>7.2.7</b> Paso 5: Tomar una decisión</a></li>
<li class="chapter" data-level="7.2.8" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#paso-6-interpretación-2"><i class="fa fa-check"></i><b>7.2.8</b> Paso 6: Interpretación</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#identificar-ellos-grupos-diferentes"><i class="fa fa-check"></i><b>7.3</b> Identificar el/los grupos diferentes</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#pruebas-post-hoc-test-de-tukey"><i class="fa fa-check"></i><b>7.3.1</b> Pruebas post hoc: Test de Tukey</a></li>
<li class="chapter" data-level="7.3.2" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#visualización-1"><i class="fa fa-check"></i><b>7.3.2</b> Visualización</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#ejercicio-1-2"><i class="fa fa-check"></i><b>7.4</b> Ejercicio 1</a></li>
<li class="chapter" data-level="7.5" data-path="anova-comparación-en-más-de-dos-muestras.html"><a href="anova-comparación-en-más-de-dos-muestras.html#ejercicio-2-1"><i class="fa fa-check"></i><b>7.5</b> Ejercicio 2</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html"><i class="fa fa-check"></i><b>8</b> Asociación de dos factores</a>
<ul>
<li class="chapter" data-level="8.1" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#base-de-datos-lapop"><i class="fa fa-check"></i><b>8.1</b> Base de datos: LAPOP</a></li>
<li class="chapter" data-level="8.2" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#pregunta-de-investigaciòn"><i class="fa fa-check"></i><b>8.2</b> Pregunta de investigaciòn</a></li>
<li class="chapter" data-level="8.3" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#preprocesamiento"><i class="fa fa-check"></i><b>8.3</b> Preprocesamiento</a></li>
<li class="chapter" data-level="8.4" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#comparación-clave"><i class="fa fa-check"></i><b>8.4</b> Comparación clave</a></li>
<li class="chapter" data-level="8.5" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#tablas-de-contingencia"><i class="fa fa-check"></i><b>8.5</b> Tablas de contingencia</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#tc-de-frecuencias"><i class="fa fa-check"></i><b>8.5.1</b> TC de frecuencias</a></li>
<li class="chapter" data-level="8.5.2" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#tc-de-proporciones"><i class="fa fa-check"></i><b>8.5.2</b> TC de proporciones</a></li>
<li class="chapter" data-level="8.5.3" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#variable-independiente-y-dependiente"><i class="fa fa-check"></i><b>8.5.3</b> Variable independiente y dependiente?</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#gráficando-barras-y-barras-apiladas"><i class="fa fa-check"></i><b>8.6</b> Gráficando: Barras y barras apiladas</a></li>
<li class="chapter" data-level="8.7" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#prueba-χ²"><i class="fa fa-check"></i><b>8.7</b> Prueba χ²</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#paso-0-análisis-exploratorio"><i class="fa fa-check"></i><b>8.7.1</b> Paso 0: Análisis exploratorio</a></li>
<li class="chapter" data-level="8.7.2" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#paso-1-establecer-hipótesis-3"><i class="fa fa-check"></i><b>8.7.2</b> Paso 1: Establecer hipótesis</a></li>
<li class="chapter" data-level="8.7.3" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#paso-2-verificar-supuestos-3"><i class="fa fa-check"></i><b>8.7.3</b> Paso 2: Verificar supuestos</a></li>
<li class="chapter" data-level="8.7.4" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#paso-3-establecer-nivel-de-significancia-3"><i class="fa fa-check"></i><b>8.7.4</b> Paso 3: Establecer nivel de significancia</a></li>
<li class="chapter" data-level="8.7.5" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#paso-4-calcular-estadístico-de-prueba-y-p-valor-2"><i class="fa fa-check"></i><b>8.7.5</b> Paso 4: Calcular estadístico de prueba y p-valor</a></li>
<li class="chapter" data-level="8.7.6" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#paso-5-tomar-una-decisión-3"><i class="fa fa-check"></i><b>8.7.6</b> Paso 5: Tomar una decisión</a></li>
<li class="chapter" data-level="8.7.7" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#paso-6-interpretación-3"><i class="fa fa-check"></i><b>8.7.7</b> Paso 6: Interpretación</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="asociación-de-dos-factores.html"><a href="asociación-de-dos-factores.html#ahora-hazlo-tú"><i class="fa fa-check"></i><b>8.8</b> Ahora hazlo tú!</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><i class="fa fa-check"></i><b>9</b> Midiendo la asociación de dos numéricas: La Correlación</a>
<ul>
<li class="chapter" data-level="9.1" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#objetivo-de-la-sesión-1"><i class="fa fa-check"></i><b>9.1</b> Objetivo de la sesión</a></li>
<li class="chapter" data-level="9.2" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#conceptos-básicos"><i class="fa fa-check"></i><b>9.2</b> Conceptos básicos</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#plano-cartesiano-y-diagrama-de-dispersión"><i class="fa fa-check"></i><b>9.2.1</b> Plano cartesiano y diagrama de dispersión</a></li>
<li class="chapter" data-level="9.2.2" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#varianza"><i class="fa fa-check"></i><b>9.2.2</b> Varianza</a></li>
<li class="chapter" data-level="9.2.3" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#covarianza"><i class="fa fa-check"></i><b>9.2.3</b> Covarianza</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#coeficiente-de-correlación-de-pearson"><i class="fa fa-check"></i><b>9.3</b> Coeficiente de Correlación de Pearson</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#definición-1"><i class="fa fa-check"></i><b>9.3.1</b> Definición</a></li>
<li class="chapter" data-level="9.3.2" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#interpretación"><i class="fa fa-check"></i><b>9.3.2</b> Interpretación</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#validación-con-prueba-de-hipótesis"><i class="fa fa-check"></i><b>9.4</b> Validación con prueba de hipótesis</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#paso-1-establecer-hipótesis-4"><i class="fa fa-check"></i><b>9.4.1</b> Paso 1: Establecer hipótesis</a></li>
<li class="chapter" data-level="9.4.2" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#paso-2-verificar-supuestos-4"><i class="fa fa-check"></i><b>9.4.2</b> Paso 2: Verificar supuestos</a></li>
<li class="chapter" data-level="9.4.3" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#paso-3-establecer-nivel-de-significancia-4"><i class="fa fa-check"></i><b>9.4.3</b> Paso 3: Establecer nivel de significancia</a></li>
<li class="chapter" data-level="9.4.4" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#paso-4-calcular-estadístico-de-prueba-y-p-valor-3"><i class="fa fa-check"></i><b>9.4.4</b> Paso 4: Calcular estadístico de prueba y p-valor</a></li>
<li class="chapter" data-level="9.4.5" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#paso-5-tomar-una-decisión-4"><i class="fa fa-check"></i><b>9.4.5</b> Paso 5: Tomar una decisión</a></li>
<li class="chapter" data-level="9.4.6" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#paso-6-interpretación-4"><i class="fa fa-check"></i><b>9.4.6</b> Paso 6: Interpretación</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#toma-nota"><i class="fa fa-check"></i><b>9.5</b> Toma nota</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#correlación-no-implica-causalidad"><i class="fa fa-check"></i><b>9.5.1</b> Correlación no implica causalidad</a></li>
<li class="chapter" data-level="9.5.2" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#cuidado-scatterplot-como-primer-paso-siempre"><i class="fa fa-check"></i><b>9.5.2</b> Cuidado: Scatterplot como primer paso SIEMPRE</a></li>
<li class="chapter" data-level="9.5.3" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#valores-extremos"><i class="fa fa-check"></i><b>9.5.3</b> Valores extremos</a></li>
<li class="chapter" data-level="9.5.4" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#tamaño-de-la-muestra"><i class="fa fa-check"></i><b>9.5.4</b> Tamaño de la muestra</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#ejercicio-1-3"><i class="fa fa-check"></i><b>9.6</b> Ejercicio 1</a></li>
<li class="chapter" data-level="9.7" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#utilizando-matrices"><i class="fa fa-check"></i><b>9.7</b> Utilizando matrices</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#matriz-de-scatterplot"><i class="fa fa-check"></i><b>9.7.1</b> Matriz de scatterplot</a></li>
<li class="chapter" data-level="9.7.2" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#matriz-de-correlación"><i class="fa fa-check"></i><b>9.7.2</b> Matriz de correlación</a></li>
<li class="chapter" data-level="9.7.3" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#graficando-la-matriz-de-correlación-con-corrplot"><i class="fa fa-check"></i><b>9.7.3</b> Graficando la matriz de correlación con <code>corrplot</code></a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="midiendo-la-asociación-de-dos-numéricas-la-correlación.html"><a href="midiendo-la-asociación-de-dos-numéricas-la-correlación.html#ejercicio-2-2"><i class="fa fa-check"></i><b>9.8</b> Ejercicio 2</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html"><i class="fa fa-check"></i><b>10</b> Regresión lineal simple: explicar y predecir</a>
<ul>
<li class="chapter" data-level="10.1" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#objetivo-de-la-sesión-2"><i class="fa fa-check"></i><b>10.1</b> Objetivo de la sesión</a></li>
<li class="chapter" data-level="10.2" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#pregunta-de-investigación-3"><i class="fa fa-check"></i><b>10.2</b> Pregunta de investigación</a></li>
<li class="chapter" data-level="10.3" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#recordando"><i class="fa fa-check"></i><b>10.3</b> Recordando</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#coeficiente-de-correlación-de-pearson-1"><i class="fa fa-check"></i><b>10.3.1</b> Coeficiente de Correlación de Pearson</a></li>
<li class="chapter" data-level="10.3.2" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#ahora-hazlo-tú-1"><i class="fa fa-check"></i><b>10.3.2</b> ¡Ahora hazlo tú!</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#introducción-a-la-regresión-lineal-simple"><i class="fa fa-check"></i><b>10.4</b> Introducción a la Regresión Lineal Simple</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#variable-dependiente-y-variable-independiente"><i class="fa fa-check"></i><b>10.4.1</b> Variable dependiente y variable independiente</a></li>
<li class="chapter" data-level="10.4.2" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#flashback-ecuación-de-la-recta"><i class="fa fa-check"></i><b>10.4.2</b> Flashback: Ecuación de la recta</a></li>
<li class="chapter" data-level="10.4.3" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#regresión-lineal-la-mejor-recta-para-la-nube-de-puntos"><i class="fa fa-check"></i><b>10.4.3</b> Regresión Lineal: La mejor recta para la nube de puntos</a></li>
<li class="chapter" data-level="10.4.4" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#calidad-de-ajuste-r2"><i class="fa fa-check"></i><b>10.4.4</b> Calidad de ajuste: R2</a></li>
<li class="chapter" data-level="10.4.5" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#significancia-estadística-de-los-coeficientes"><i class="fa fa-check"></i><b>10.4.5</b> Significancia estadística de los coeficientes</a></li>
<li class="chapter" data-level="10.4.6" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#la-rls-como-herramienta-predictiva"><i class="fa fa-check"></i><b>10.4.6</b> La RLS como herramienta predictiva</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#ejercicio-1-modelando-la-matrícula-escolar-rls"><i class="fa fa-check"></i><b>10.5</b> Ejercicio 1: Modelando la Matrícula escolar (RLS)</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#paso-0-identificar-claramente-la-variable-dependiente-y-la-variable-independiente"><i class="fa fa-check"></i><b>10.5.1</b> Paso 0: Identificar claramente la variable dependiente y la variable independiente</a></li>
<li class="chapter" data-level="10.5.2" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#paso-1-explorar-previamente-la-relación-de-las-variables"><i class="fa fa-check"></i><b>10.5.2</b> Paso 1: Explorar previamente la relación de las variables</a></li>
<li class="chapter" data-level="10.5.3" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#paso-2-planteamos-el-modelo-y-verificamos-si-es-válido-con-anova"><i class="fa fa-check"></i><b>10.5.3</b> Paso 2: Planteamos el modelo y verificamos si es válido con ANOVA</a></li>
<li class="chapter" data-level="10.5.4" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#paso-3-nivel-explicativo-del-modelo"><i class="fa fa-check"></i><b>10.5.4</b> Paso 3: Nivel explicativo del modelo</a></li>
<li class="chapter" data-level="10.5.5" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#paso-4-la-variable-x-aporta-al-modelo"><i class="fa fa-check"></i><b>10.5.5</b> Paso 4: La variable x aporta al modelo</a></li>
<li class="chapter" data-level="10.5.6" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#paso-5-construimos-la-ecuación-del-modelo-creado"><i class="fa fa-check"></i><b>10.5.6</b> Paso 5: Construimos la ecuación del modelo creado</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="regresión-lineal-simple-explicar-y-predecir.html"><a href="regresión-lineal-simple-explicar-y-predecir.html#ejercicio-2-3"><i class="fa fa-check"></i><b>10.6</b> Ejercicio 2</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html"><i class="fa fa-check"></i><b>11</b> Regresión lineal múltiple: más de una independiente</a>
<ul>
<li class="chapter" data-level="11.1" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#objetivo-de-la-sesión-3"><i class="fa fa-check"></i><b>11.1</b> Objetivo de la sesión</a></li>
<li class="chapter" data-level="11.2" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#regresión-lineal-múltiple"><i class="fa fa-check"></i><b>11.2</b> Regresión Lineal Múltiple</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#ecuación"><i class="fa fa-check"></i><b>11.2.1</b> Ecuación</a></li>
<li class="chapter" data-level="11.2.2" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#mayor-complejidad-para-visualizar-la-relación"><i class="fa fa-check"></i><b>11.2.2</b> Mayor complejidad para visualizar la relación</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#pregunta-de-investigación-4"><i class="fa fa-check"></i><b>11.3</b> Pregunta de investigación</a></li>
<li class="chapter" data-level="11.4" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#ejercicio-1-explicando-la-desigualdad-con-rlm"><i class="fa fa-check"></i><b>11.4</b> Ejercicio 1: Explicando la desigualdad con RLM</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#paso-0-identificar-claramente-la-variable-dependiente-y-las-variables-independientes"><i class="fa fa-check"></i><b>11.4.1</b> Paso 0: Identificar claramente la variable dependiente y laS variables independientes</a></li>
<li class="chapter" data-level="11.4.2" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#paso-1-explorar-previamente-la-relación-de-las-variables-1"><i class="fa fa-check"></i><b>11.4.2</b> Paso 1: Explorar previamente la relación de las variables</a></li>
<li class="chapter" data-level="11.4.3" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#paso-2-nuestro-modelo-es-válido"><i class="fa fa-check"></i><b>11.4.3</b> Paso 2: ¿Nuestro modelo es válido?</a></li>
<li class="chapter" data-level="11.4.4" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#paso-3-qué-tanto-explica-mi-modelo"><i class="fa fa-check"></i><b>11.4.4</b> Paso 3: ¿Qué tanto explica mi modelo?</a></li>
<li class="chapter" data-level="11.4.5" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#paso-4-las-variables-x-aportan-al-modelo-cuál-es-la-más-importante"><i class="fa fa-check"></i><b>11.4.5</b> Paso 4: ¿Las variables X aportan al modelo? ¿Cuál es la más importante?</a></li>
<li class="chapter" data-level="11.4.6" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#paso-5-cuál-es-la-ecuación-del-modelo"><i class="fa fa-check"></i><b>11.4.6</b> Paso 5: ¿Cuál es la ecuación del modelo?</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#tabla-para-comparar-modelos-stargazer"><i class="fa fa-check"></i><b>11.5</b> Tabla para comparar modelos (stargazer)</a></li>
<li class="chapter" data-level="11.6" data-path="regresión-lineal-múltiple-más-de-una-independiente.html"><a href="regresión-lineal-múltiple-más-de-una-independiente.html#ejercicio-2-4"><i class="fa fa-check"></i><b>11.6</b> Ejercicio 2</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html"><i class="fa fa-check"></i><b>12</b> Regresión lineal múltiple: elementos adicionales</a>
<ul>
<li class="chapter" data-level="12.1" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#objetivo-de-la-sesión-4"><i class="fa fa-check"></i><b>12.1</b> Objetivo de la sesión</a></li>
<li class="chapter" data-level="12.2" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#identificar-la-variable-que-aporta-más-al-modelo"><i class="fa fa-check"></i><b>12.2</b> Identificar la variable que aporta más al modelo</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#el-problema-de-la-unidad-de-medida"><i class="fa fa-check"></i><b>12.2.1</b> El problema de la unidad de medida</a></li>
<li class="chapter" data-level="12.2.2" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#solución-uso-de-coeficientes-estandarizados"><i class="fa fa-check"></i><b>12.2.2</b> Solución: Uso de coeficientes estandarizados</a></li>
<li class="chapter" data-level="12.2.3" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#ejercicio"><i class="fa fa-check"></i><b>12.2.3</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#sobre-variables-categóricas-en-la-rlm"><i class="fa fa-check"></i><b>12.3</b> Sobre variables categóricas en la RLM</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#variables-dummy-1-0-definición"><i class="fa fa-check"></i><b>12.3.1</b> Variables dummy (1-0): Definición</a></li>
<li class="chapter" data-level="12.3.2" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#variables-dummy-1-0-utilidad-en-la-rlm"><i class="fa fa-check"></i><b>12.3.2</b> Variables dummy (1-0): Utilidad en la RLM</a></li>
<li class="chapter" data-level="12.3.3" data-path="regresión-lineal-múltiple-elementos-adicionales.html"><a href="regresión-lineal-múltiple-elementos-adicionales.html#ejercicio-4"><i class="fa fa-check"></i><b>12.3.3</b> Ejercicio</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística para el Análisis Político I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ic-para-una-media-y-una-proporción-ic-entre-grupos" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Sesión 5</span> IC para una media y una proporción, IC entre grupos<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-para-una-media-y-una-proporción-ic-entre-grupos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="objetivo-de-la-sesión." class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Objetivo de la sesión.<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#objetivo-de-la-sesión." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Comprender qué es un índice aditivo y cómo se utiliza como medida resumen.</p></li>
<li><p>Calcular el IC del índice para toda la población y entre grupos.</p></li>
<li><p>Visualizar el IC del Índice entre grupos.</p></li>
</ul>
</div>
<div id="índice-aditivo" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Índice Aditivo<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#índice-aditivo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="https://pro.arcgis.com/es/pro-app/latest/tool-reference/spatial-statistics/GUID-4F8022C6-1AD0-4F94-B5F7-9288EA37DAD8-web.png" /></p>
<p>Un índice aditivo es una técnica utilizada en la investigación social y otras áreas para combinar múltiples indicadores o variables en una única medida compuesta. La idea central detrás de un índice aditivo es sumar las puntuaciones o valores de diferentes ítems para obtener un puntaje total que represente una característica o concepto más amplio que no se puede medir directamente con un solo ítem.</p>
<p>Supongamos que realizas una encuesta y pides a los encuestados que evalúen su satisfacción con los servicios públicos de agua, luz y desagüe utilizando una escala Likert de 1 (muy insatisfecho) a 5 (muy satisfecho). Ahora, deseas combinar estas tres variables en un índice aditivo que mida la satisfacción general con los servicios públicos.</p>
<p><strong>Paso 1: Obten los datos</strong>
Por ejemplo, un encuestado ha contestado:
Agua: 4
Luz: 5
Desagüe: 3</p>
<p><strong>Paso 2: Creación del índice aditivo</strong>
Para crear el índice, simplemente sumarías las puntuaciones de estas tres variables:</p>
<p>Índice de Satisfacción = Agua + Luz + Desagüe
Índice de Satisfacción = 4 + 5 + 3 = 12</p>
<p>El puntaje total para este encuestado en el índice de satisfacción con los servicios públicos sería 12. Dado que estás utilizando una escala Likert de 1 a 5 y tres servicios, el puntaje máximo posible para el índice sería 15 (si estuvieran muy satisfechos con los tres servicios) y el mínimo sería 3 (si estuvieran muy insatisfechos con los tres servicios).</p>
<p><strong>Paso 3: Estandarización</strong></p>
<p>Reescalar es el proceso de ajustar el rango de una variable para que se ajuste a una nueva escala. En el contexto de nuestro índice de satisfacción con los servicios públicos, reescalar los datos a una escala de 0 a 10 puede tener varias ventajas.</p>
<ul>
<li><p>Primero, una escala de 0 a 10 es intuitivamente comprensible para la mayoría de las personas, ya que es similar a las escalas que a menudo se utilizan en educación para calificar el desempeño.</p></li>
<li><p>Segundo, al tener un rango definido, facilita la interpretación y comparación de los resultados. Por ejemplo, un valor de 8 en esta escala sugiere una alta satisfacción, mientras que un valor cercano a 0 indica insatisfacción.</p></li>
<li><p>Finalmente, reescalar a una escala estándar como 0 a 10 puede facilitar la comparación con otros índices o estudios que utilicen la misma escala, permitiendo una evaluación más uniforme y coherente.</p></li>
</ul>
<p>Para ello, podemos utilizar el paquete <code>scales</code> y específicamente la función `rescale()``</p>
<p><strong>Paso 4: Describir</strong></p>
<p>Una vez reescalado, el índice se convierte en un resumen efectivo de las variables originales, consolidando la información en una única medida. Esta representación condensada facilita su uso en análisis posteriores. Por ejemplo, podemos obtener intervalos de confianza para el índice, proporcionando un rango de valores en el que es probable que se encuentre la verdadera media poblacional. Además, el índice reescalado puede ser utilizado en diversos modelos estadísticos, análisis de tendencias o incluso comparaciones entre diferentes grupos o períodos de tiempo, ofreciendo una herramienta versátil para la investigación y toma de decisiones.</p>
</div>
<div id="intervalos-de-confianza-para-grupos" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Intervalos de confianza para grupos<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#intervalos-de-confianza-para-grupos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>El intervalo de confianza de una media en grupos brinda un rango estimado para la verdadera media poblacional dentro de categorías específicas o subconjuntos de datos, siendo crucial en análisis sociopolíticos.</p></li>
<li><p>En lugar de un solo intervalo para toda una población, se calcula un intervalo para cada grupo de interés político o social.</p></li>
<li><p>Permite realizar comparaciones detalladas entre distintos grupos sociopolíticos o demográficos.</p></li>
<li><p>Su utilidad en ciencia política y ciencias sociales incluye: Evaluación de la aprobación de líderes políticos entre diferentes grupos demográficos (por ejemplo, por edad, género o nivel educativo), análisis de tendencias electorales en diferentes regiones o entre distintos grupos socioeconómicos, estudio de la percepción pública sobre políticas específicas, como reformas educativas o de salud, entre diferentes sectores de la población, comparación de niveles de confianza en instituciones gubernamentales entre urbanos y rurales o entre diferentes grupos étnicos, entre otros.</p></li>
<li><p>Es esencial para entender las dinámicas y divisiones dentro de una sociedad, identificando posibles brechas o áreas de consenso.</p></li>
</ul>
<p>En resumen, es una herramienta vital para académicos, analistas y tomadores de decisiones en ciencia política, permitiendo un análisis más profundo y matizado de las actitudes y percepciones públicas.</p>
<p>Para nuestros fines, nos alejaremos un poco de la fórmula que vimos la clase pasada y lo haremos todo mucho más rápido con la utilización de la función <code>ciMean()</code>.</p>
</div>
<div id="ejercicio-1" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Ejercicio 1<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ejercicio-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="pregunta-de-investigación" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Pregunta de investigación<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#pregunta-de-investigación" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En base a la data ENADES, calcule un índice aditivo de <strong>Percepción sobre la desigualdad en el acceso a servicios públicos</strong>.</p>
<p>Para ello, vamos a utilizar estas cuatro variables:</p>
<p><img src="figures/ENADES_p11.png" /></p>
<p>Brinde el intervalo de confianza de la media de percepción sobre la desigualdad en el acceso a servicios públicos en la población al 95%</p>
<p>Asimismo, genere una comparación de los intervalos de confianza para los sectores de “Lima Metropolitana” y “Perú sin Lima” (según variable zona3)</p>
<p><strong>ABRIMOS LA DATA</strong></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb94-1" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb94-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb94-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb94-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb94-3" tabindex="-1"></a><span class="fu">library</span>(lsr)</span>
<span id="cb94-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb94-4" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb97-1" tabindex="-1"></a>enades<span class="ot">&lt;-</span><span class="fu">read_spss</span>(<span class="st">&quot;https://github.com/ChristianChiroqueR/banco_de_datos/raw/main/ENADES_2022.sav&quot;</span>)</span></code></pre></div>
</div>
<div id="creamos-el-índice-aditivo" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Creamos el índice aditivo<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#creamos-el-índice-aditivo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Paso 1: Verificar que las variables corresponden al concepto</strong></p>
<p>En este caso las tres se destinan a medir una percepción en relación a la desigualdad de la entrega de un servicio por parte del Estado.</p>
<p><strong>Paso 2: Revisar el sentido de las categorías en el cuestionario/diccionario</strong></p>
<p>Antes de sumar las variables individuales para crear un índice aditivo, es esencial verificar la estructura y la coherencia de las categorías en las escalas de las variables que se combinarán. Las categorías de cada escala deben alinearse de manera que el progreso a través de las categorías refleje una progresión lógica y uniforme en la variable subyacente.</p>
<p>Por ejemplo, si estamos evaluando la satisfacción con ciertos servicios, las categorías de la escala deberían estructurarse de manera que un número más alto indique una mayor satisfacción, mientras que un número más bajo denota menos satisfacción. Esto asegura que el índice sea intuitivo: a medida que el valor del índice aumenta, también lo hace la intensidad o el grado de la característica que se está midiendo.</p>
<p>Al garantizar que las categorías de la escala estén bien alineadas y sean intuitivas, nos aseguramos de que el índice aditivo resultante sea válido y refleje de manera precisa el constructo que intentamos medir.</p>
<p>En este caso vemos que las variables tienen las siguientes escalas: (1) Muy desigual, (2) Poco desigual y (3) Nada desigual. Ciertamente, sería más intuitivo si el 3 indicaría “mucha desigualdad” y el 1 “poca desigualdad”</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb98-1" tabindex="-1"></a><span class="co">#Percepción de desigualdad en el acceso a la educación</span></span>
<span id="cb98-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb98-2" tabindex="-1"></a><span class="co">#summary(enades$p11.1)</span></span>
<span id="cb98-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb98-3" tabindex="-1"></a><span class="fu">table</span>(enades<span class="sc">$</span>p11<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## 
##   1   2   3 
## 912 503  80</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb100-1" tabindex="-1"></a><span class="co">#Percepción de desigualdad en el acceso a la salud</span></span>
<span id="cb100-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb100-2" tabindex="-1"></a><span class="co">#summary(enades$p11.2)</span></span>
<span id="cb100-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb100-3" tabindex="-1"></a><span class="fu">table</span>(enades<span class="sc">$</span>p11<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## 
##    1    2    3 
## 1080  361   56</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb102-1" tabindex="-1"></a><span class="co">#Percepción de desigualdad en el acceso al trabajo</span></span>
<span id="cb102-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb102-2" tabindex="-1"></a><span class="co">#summary(enades$p11.3)</span></span>
<span id="cb102-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb102-3" tabindex="-1"></a><span class="fu">table</span>(enades<span class="sc">$</span>p11<span class="fl">.3</span>)</span></code></pre></div>
<pre><code>## 
##   1   2   3 
## 885 544  56</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb104-1" tabindex="-1"></a><span class="co">#Percepción de desigualdad el acceso a la justicia</span></span>
<span id="cb104-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb104-2" tabindex="-1"></a><span class="co">#summary(enades$p11.4)</span></span>
<span id="cb104-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb104-3" tabindex="-1"></a><span class="fu">table</span>(enades<span class="sc">$</span>p11<span class="fl">.4</span>)</span></code></pre></div>
<pre><code>## 
##    1    2    3 
## 1274  170   48</code></pre>
<p>En el mundo de la investigación y el análisis de datos, la exploración descriptiva inicial es una etapa crucial que no debe pasarse por alto. Esta exploración nos permite comprender la estructura, la distribución y las características generales de nuestros datos antes de realizar análisis más complejos. Una de las razones más importantes para llevar a cabo esta fase exploratoria es la detección de valores atípicos o inusuales, incluidos los valores codificados como “No sabe/No responde” (NS/NR), que a menudo se representan con códigos numéricos específicos como 999, 888, entre otros.</p>
<p>Cuando no se detectan o se manejan adecuadamente, estos valores codificados como NS/NR pueden introducir errores significativos en nuestros análisis. Por ejemplo, si se incluyen en el cálculo de una media, estos valores altos (como 999) inflarán artificialmente la media, resultando en una representación imprecisa de la tendencia central de los datos. Además, estos valores pueden distorsionar otros cálculos y estadísticas descriptivas, como la mediana, la varianza, y el rango.</p>
<p>En el contexto de ciencias sociales y ciencia política, donde las encuestas y los cuestionarios son herramientas comunes, los valores de NS/NR son habituales. Los encuestados pueden no querer, o no saber, cómo responder a ciertas preguntas. Es esencial identificar y manejar adecuadamente estos valores para garantizar que los resultados del análisis sean válidos y representativos de la población en estudio. Por lo tanto, una exploración descriptiva cuidadosa es el primer paso crucial para garantizar la integridad y precisión de cualquier análisis posterior.</p>
<p>Como corroboramos que no hay problema de este tipo vamos a recodificar las variables para volverlas intuitivas.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-1" tabindex="-1"></a>enades<span class="ot">&lt;-</span>enades <span class="sc">|&gt;</span> </span>
<span id="cb106-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p11.1n=</span><span class="fu">case_when</span>(p11<span class="fl">.1</span><span class="sc">==</span><span class="dv">1</span><span class="sc">~</span><span class="dv">3</span>,</span>
<span id="cb106-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-3" tabindex="-1"></a>                          p11<span class="fl">.1</span><span class="sc">==</span><span class="dv">2</span><span class="sc">~</span><span class="dv">2</span>,</span>
<span id="cb106-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-4" tabindex="-1"></a>                          p11<span class="fl">.1</span><span class="sc">==</span><span class="dv">3</span><span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb106-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-5" tabindex="-1"></a>                          <span class="cn">TRUE</span><span class="sc">~</span><span class="cn">NA_real_</span>),</span>
<span id="cb106-6"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-6" tabindex="-1"></a>         <span class="at">p11.2n=</span><span class="fu">case_when</span>(p11<span class="fl">.2</span><span class="sc">==</span><span class="dv">1</span><span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb106-7"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-7" tabindex="-1"></a>                          p11<span class="fl">.2</span><span class="sc">==</span><span class="dv">2</span><span class="sc">~</span><span class="dv">2</span>,</span>
<span id="cb106-8"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-8" tabindex="-1"></a>                          p11<span class="fl">.2</span><span class="sc">==</span><span class="dv">3</span><span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb106-9"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-9" tabindex="-1"></a>                          <span class="cn">TRUE</span><span class="sc">~</span><span class="cn">NA_real_</span>),</span>
<span id="cb106-10"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-10" tabindex="-1"></a>         <span class="at">p11.3n=</span><span class="fu">case_when</span>(p11<span class="fl">.3</span><span class="sc">==</span><span class="dv">1</span><span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb106-11"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-11" tabindex="-1"></a>                          p11<span class="fl">.3</span><span class="sc">==</span><span class="dv">2</span><span class="sc">~</span><span class="dv">2</span>,</span>
<span id="cb106-12"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-12" tabindex="-1"></a>                          p11<span class="fl">.3</span><span class="sc">==</span><span class="dv">3</span><span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb106-13"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-13" tabindex="-1"></a>                          <span class="cn">TRUE</span><span class="sc">~</span><span class="cn">NA_real_</span>),</span>
<span id="cb106-14"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-14" tabindex="-1"></a>         <span class="at">p11.4n=</span><span class="fu">case_when</span>(p11<span class="fl">.4</span><span class="sc">==</span><span class="dv">1</span><span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb106-15"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-15" tabindex="-1"></a>                          p11<span class="fl">.4</span><span class="sc">==</span><span class="dv">2</span><span class="sc">~</span><span class="dv">2</span>,</span>
<span id="cb106-16"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-16" tabindex="-1"></a>                          p11<span class="fl">.4</span><span class="sc">==</span><span class="dv">3</span><span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb106-17"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb106-17" tabindex="-1"></a>                          <span class="cn">TRUE</span><span class="sc">~</span><span class="cn">NA_real_</span>))</span></code></pre></div>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb107-1" tabindex="-1"></a><span class="fu">table</span>(enades<span class="sc">$</span>p11<span class="fl">.1</span>n)</span></code></pre></div>
<pre><code>## 
##   1   2   3 
##  80 503 912</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb109-1" tabindex="-1"></a><span class="fu">table</span>(enades<span class="sc">$</span>p11<span class="fl">.2</span>n)</span></code></pre></div>
<pre><code>## 
##    1    2    3 
##   56  361 1080</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb111-1" tabindex="-1"></a><span class="fu">table</span>(enades<span class="sc">$</span>p11<span class="fl">.3</span>n)</span></code></pre></div>
<pre><code>## 
##   1   2   3 
##  56 544 885</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb113-1" tabindex="-1"></a><span class="fu">table</span>(enades<span class="sc">$</span>p11<span class="fl">.4</span>n)</span></code></pre></div>
<pre><code>## 
##    1    2    3 
##   48  170 1274</code></pre>
<p><strong>Paso 3: Creación del índice aditivo (sumar)</strong></p>
<p>Ahora sí podremos realizar el índice aditivo.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb115-1" tabindex="-1"></a>enades<span class="ot">&lt;-</span>enades <span class="sc">|&gt;</span> </span>
<span id="cb115-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb115-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">indice_aditivo=</span>p11<span class="fl">.1</span>n<span class="sc">+</span>p11<span class="fl">.2</span>n<span class="sc">+</span>p11<span class="fl">.3</span>n<span class="sc">+</span>p11<span class="fl">.4</span>n) <span class="co">#Creamos una nueva variable que es la suma de las originarias recodificadas. </span></span></code></pre></div>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb116-1" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb116-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb116-2" tabindex="-1"></a>  <span class="fu">count</span>(indice_aditivo)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 2
##    indice_aditivo     n
##             &lt;dbl&gt; &lt;int&gt;
##  1              4     5
##  2              5     3
##  3              6    15
##  4              7    35
##  5              8    82
##  6              9   145
##  7             10   274
##  8             11   337
##  9             12   550
## 10             NA    84</code></pre>
<p>Como nuestras variables de insumo tenían como valores posibles 1-3, nuestro índice tendrá una escala posible de 4 (si la persona contestó a todo con 1) a 12 (si la persona contestó a todo con 3).</p>
<p><strong>Paso 4: Estandarización</strong></p>
<p>Sobre este índice ya creado, podemos cambiarle la escala para que no sea de 4-12 sino de 0-10.</p>
<p>4A. Esto lo podemos realizar manualmente: 1) Identificamos el valor mínimo y máximo con summary(); 2) Restar a todos los valores el mínimo; 3) Al resultado, dividir por el máximo menos el mínimo; 4) Multiplicar por el número que será el nuevo máximo. Ejemplo:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb118-1" tabindex="-1"></a>enades <span class="sc">%&gt;%</span> </span>
<span id="cb118-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb118-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">indice_1_10=</span>(indice_aditivo<span class="dv">-4</span>)<span class="sc">/</span><span class="dv">8</span><span class="sc">*</span><span class="dv">10</span>) <span class="sc">%&gt;%</span> <span class="co"># </span></span>
<span id="cb118-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb118-3" tabindex="-1"></a>  <span class="fu">count</span>(indice_1_10)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 2
##    indice_1_10     n
##          &lt;dbl&gt; &lt;int&gt;
##  1        0        5
##  2        1.25     3
##  3        2.5     15
##  4        3.75    35
##  5        5       82
##  6        6.25   145
##  7        7.5    274
##  8        8.75   337
##  9       10      550
## 10       NA       84</code></pre>
<p>4b. O también con una función (bastante más rápido)</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb120-1" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb120-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb120-2" tabindex="-1"></a>enades<span class="sc">$</span>indice_aditivo_reescalado<span class="ot">&lt;-</span><span class="fu">rescale</span>(enades<span class="sc">$</span>indice_aditivo, <span class="at">to=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>)) <span class="co">#Aquí mencionas que quieresque la nueva escala sea de 0 al 10. </span></span></code></pre></div>
<p>Vemos que el resultado es exactamente el mismo.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb121-1" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb121-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb121-2" tabindex="-1"></a>  <span class="fu">count</span>(indice_aditivo_reescalado)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 2
##    indice_aditivo_reescalado     n
##                        &lt;dbl&gt; &lt;int&gt;
##  1                      0        5
##  2                      1.25     3
##  3                      2.5     15
##  4                      3.75    35
##  5                      5       82
##  6                      6.25   145
##  7                      7.5    274
##  8                      8.75   337
##  9                     10      550
## 10                     NA       84</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb123-1" tabindex="-1"></a>enades <span class="sc">%&gt;%</span> </span>
<span id="cb123-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb123-2" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb123-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb123-3" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x=</span>indice_aditivo_reescalado)<span class="sc">+</span></span>
<span id="cb123-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb123-4" tabindex="-1"></a>  <span class="fu">geom_bar</span>()<span class="sc">+</span></span>
<span id="cb123-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb123-5" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">&#39;count&#39;</span>, <span class="fu">aes</span>(<span class="at">label=</span>..count..), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
## ℹ Please use `after_stat(count)` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.</code></pre>
<pre><code>## Warning: Removed 84 rows containing non-finite values (`stat_count()`).
## Removed 84 rows containing non-finite values (`stat_count()`).</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
</div>
<div id="cálculo-del-intervalo-de-confianza-al-95" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Cálculo del intervalo de confianza al 95%<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cálculo-del-intervalo-de-confianza-al-95" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong><em>Estimación puntual</em></strong></p>
<p>El estimador puntual es una estadística descriptiva que se utiliza para estimar el valor desconocido de un parámetro poblacional a partir de una muestra. El estimador puntual proporciona una única estimación del valor del parámetro y se calcula a partir de los datos de la muestra.</p>
<p>En este caso, la mejor estimación de la media población es simplemente la media muestral.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb126-1" tabindex="-1"></a><span class="fu">mean</span>(enades<span class="sc">$</span>indice_aditivo_reescalado, <span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="co">#Calculamos la media, obviando valores perdidos. </span></span></code></pre></div>
<pre><code>## [1] 8.293568</code></pre>
</div>
<div id="ic-para-una-media" class="section level3 hasAnchor" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> IC para una media<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-para-una-media" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora, una vez identificado el estimador puntual, podemos cambiar nuestra estimación, ahora utilizando intervalos.</p>
<p>La clase pasada lo hicimos con la fórmula, paso por paso. Ahora, utilizaremos una función:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb128-1" tabindex="-1"></a><span class="co">#library(lsr) #Recuerda que esta función está en el paquete lsr</span></span>
<span id="cb128-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb128-2" tabindex="-1"></a><span class="fu">ciMean</span>(enades<span class="sc">$</span>indice_aditivo_reescalado, <span class="at">na.rm =</span> T) <span class="co"># Calculamos el intervalo de confianza de p17, obviando valores perdidos. </span></span></code></pre></div>
<pre><code>##          2.5%    97.5%
## [1,] 8.197055 8.390082</code></pre>
</div>
<div id="ic-para-una-media-según-grupos" class="section level3 hasAnchor" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> IC para una media según grupos<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-para-una-media-según-grupos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Una vez que ya tenemos nuestra variable numérica, lo que necesitamos para comparar es justamente un grupo de comparación. Ya hablando en programación del R, necesitamos un <strong>factor</strong>.</p>
<p>Recuerda que el factor era una variable que visualmente son números, pero teóricamente sabemos que cada número es un nivel.</p>
<p>Utilizaremos la variable zona3, la cual separa a los encuestados según su procedencia en: “Lima Metropolitana” y “Perú sin Lima”.</p>
<p>Veamos:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb130-1" tabindex="-1"></a>enades<span class="sc">$</span>zona3<span class="ot">&lt;-</span><span class="fu">factor</span>(enades<span class="sc">$</span>zona3, <span class="co"># Nombre de la variable a convertir</span></span>
<span id="cb130-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb130-2" tabindex="-1"></a>                     <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="co"># Definimos los niveles (esta variable sólo tenía 2 niveles)</span></span>
<span id="cb130-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb130-3" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Lima Metropolitana&quot;</span>, <span class="st">&quot;Perú sin Lima&quot;</span>)) <span class="co">#Colocamos sus etiquetas</span></span>
<span id="cb130-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb130-4" tabindex="-1"></a></span>
<span id="cb130-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb130-5" tabindex="-1"></a><span class="co">#Con este comando hemos sobreescrito la variable zona3. Ahora lo que inicialmente era una variable numérica, ahora es un factor. </span></span></code></pre></div>
<p>Corroboremos:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb131-1" tabindex="-1"></a><span class="fu">str</span>(enades<span class="sc">$</span>zona3) <span class="co">#Solicitamos la estructura de la variable zona3</span></span></code></pre></div>
<pre><code>##  Factor w/ 2 levels &quot;Lima Metropolitana&quot;,..: 1 1 2 2 2 2 2 2 2 2 ...</code></pre>
<p>Solicitemos el intervalo de confianza de la variable creada para cada grupo identificado:</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb133-1" tabindex="-1"></a>indice_segun_zona<span class="ot">&lt;-</span>enades <span class="sc">%&gt;%</span> </span>
<span id="cb133-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb133-2" tabindex="-1"></a>  <span class="fu">group_by</span>(zona3) <span class="sc">%&gt;%</span> <span class="co">#Agrupamos por zona</span></span>
<span id="cb133-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb133-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(indice_aditivo_reescalado, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co">#Utilizamos summarise y pedimos la media,</span></span>
<span id="cb133-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb133-4" tabindex="-1"></a>            <span class="at">ci_lower =</span> <span class="fu">ciMean</span>(indice_aditivo_reescalado, <span class="at">na.rm =</span> T)[<span class="dv">1</span>], <span class="co"># También el PRIMER ELEMENTO de la función ciMean</span></span>
<span id="cb133-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb133-5" tabindex="-1"></a>            <span class="at">ci_upper =</span> <span class="fu">ciMean</span>(indice_aditivo_reescalado, <span class="at">na.rm =</span> T)[<span class="dv">2</span>]) <span class="co">#Y el SEGUNDO ELEMENTO de la función ciMean</span></span></code></pre></div>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb134-1" tabindex="-1"></a>indice_segun_zona</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   zona3               mean ci_lower ci_upper
##   &lt;fct&gt;              &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Lima Metropolitana  8.48     8.33     8.64
## 2 Perú sin Lima       8.19     8.07     8.31</code></pre>
<p>Según el cálculo, para Lima Metropolitana la media poblacional se encuentra entre 8.49 y 8.77, mientras que para Perú sin Lima se encuentra entre 8.25 y 8.47.</p>
<p><strong>INTERPRETACIÓN</strong></p>
<p>Al comparar dos intervalos de confianza entre grupos, lo más importante a tener en cuenta son:</p>
<ul>
<li>Superposición de Intervalos: Si los intervalos de confianza de dos grupos no se superponen, esto sugiere una diferencia estadísticamente significativa entre las medias de los grupos en la población.</li>
</ul>
<p>-Posición del Intervalo en la Escala: Aparte de la superposición, es esencial observar dónde se sitúan los intervalos en la escala. Si un grupo tiene un intervalo de confianza que se sitúa consistentemente más alto que el otro, puede indicar una tendencia o dirección en la diferencia entre los grupos.</p>
<ul>
<li>Nivel de Confianza Utilizado y amplitud el intervalo: Es importante recordar el nivel de confianza utilizado al construir los intervalos (por ejemplo, 95%). Un nivel de confianza más alto resultaría en intervalos más amplios, mientras que un nivel más bajo daría como resultado intervalos más estrechos.</li>
</ul>
<p>Aplicando a los resultados precisados:</p>
<ul>
<li><p>Superposición: No hay. Un intervalo va de 8.49 a 8.77 (Lima Metropolitana) y el otro de 8.25 y 8.47 (Perú sin Lima). Esto sugiere una diferencia estadísticamente significativa entre estos sectores.</p></li>
<li><p>Posición del intervalo en la escala: Podemos decir que tenemos indicio de que en promedio la percepción de desigualdad en el acceso a servicios es más alta en Lima que en el resto del país.</p></li>
<li><p>Nivel de confianza: Recordemos, cuando usamos ciMean() estamos utilizando un nivel de confianza del 95% por default.</p></li>
</ul>
<p>Por ejemplo, cuánto sería los intervalos de confianza al 99%?</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb136-1" tabindex="-1"></a>enades <span class="sc">%&gt;%</span> </span>
<span id="cb136-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb136-2" tabindex="-1"></a>  <span class="fu">group_by</span>(zona3) <span class="sc">%&gt;%</span> </span>
<span id="cb136-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb136-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(indice_aditivo_reescalado, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb136-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb136-4" tabindex="-1"></a>            <span class="at">ci_lower =</span> <span class="fu">ciMean</span>(indice_aditivo_reescalado, <span class="at">na.rm =</span> <span class="cn">TRUE</span>, <span class="at">conf =</span> <span class="fl">0.99</span>)[<span class="dv">1</span>], </span>
<span id="cb136-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb136-5" tabindex="-1"></a>            <span class="at">ci_upper =</span> <span class="fu">ciMean</span>(indice_aditivo_reescalado, <span class="at">na.rm =</span> <span class="cn">TRUE</span>, <span class="at">conf =</span> <span class="fl">0.99</span>)[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   zona3               mean ci_lower ci_upper
##   &lt;fct&gt;              &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 Lima Metropolitana  8.48     8.28     8.69
## 2 Perú sin Lima       8.19     8.03     8.35</code></pre>
<blockquote>
<p>Qué puedes observar?</p>
</blockquote>
</div>
<div id="visualización" class="section level3 hasAnchor" number="5.4.6">
<h3><span class="header-section-number">5.4.6</span> Visualización<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#visualización" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Como dijimos, las barras de error en un gráfico de intervalos de confianza pueden ser útiles para comparar la precisión de las estimaciones entre diferentes grupos o condiciones.</p>
<p>Podemos utilizar un comando básico como la función <code>plotmeans()</code>:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb138-1" tabindex="-1"></a><span class="fu">library</span>(gplots)</span>
<span id="cb138-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb138-2" tabindex="-1"></a><span class="fu">plotmeans</span>(enades<span class="sc">$</span>indice_aditivo_reescalado<span class="sc">~</span>enades<span class="sc">$</span>zona3, <span class="at">p=</span><span class="fl">0.95</span>, </span>
<span id="cb138-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb138-3" tabindex="-1"></a>          <span class="at">xlab=</span><span class="st">&quot;Ámbito&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Índice de percepción de desigualdad en acceso a servicios&quot;</span>, </span>
<span id="cb138-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb138-4" tabindex="-1"></a>          <span class="at">main=</span><span class="st">&quot;Gráfico de medias de Índice Aditivo&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p>Sin embargo, te recomiendo utilizar <code>ggplot()</code>!</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb139-1" tabindex="-1"></a>indice_segun_zona <span class="sc">|&gt;</span> <span class="co">#Data</span></span>
<span id="cb139-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb139-2" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span>       <span class="co">#Iniciamos el ggplot. A partir de ahora son +! ya no |&gt;!</span></span>
<span id="cb139-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb139-3" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">y=</span>mean, <span class="at">x=</span>zona3)<span class="sc">+</span>  <span class="co">#Los grupos en el eje X y la media en el eje Y</span></span>
<span id="cb139-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb139-4" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>ci_lower, <span class="at">ymax=</span>ci_upper), <span class="at">width=</span><span class="fl">0.2</span>)<span class="sc">+</span> <span class="co">#Graficamos la barra de error</span></span>
<span id="cb139-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb139-5" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">paste</span>(<span class="fu">round</span>(mean, <span class="dv">2</span>))), <span class="at">vjust=</span><span class="dv">0</span>, <span class="at">size=</span><span class="dv">5</span>)<span class="sc">+</span> <span class="co">#Colocamos el texto del valor de la media</span></span>
<span id="cb139-6"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb139-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Procedencia&quot;</span>) <span class="sc">+</span> <span class="co">#Etiqueta del eje X</span></span>
<span id="cb139-7"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb139-7" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Percepción de la desigualdad&quot;</span>) <span class="co"># Etiqueta del eje y</span></span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<blockquote>
<p>RECUERDA: Se superponen los intervalos?</p>
</blockquote>
<p>Si los intervalos de confianza se superponen significa que no hay una diferencia estadísticamente significativa entre las estimaciones correspondientes a cada intervalo. Es decir, la diferencia entre las estimaciones no es lo suficientemente grande como para ser considerada significativa desde un punto de vista estadístico.</p>
<p><strong>IMPORTANTE!!</strong></p>
<p><strong>Es importante tener en cuenta que la superposición de los intervalos de confianza no es una prueba concluyente de que no hay una diferencia significativa entre las estimaciones. Se debe realizar una prueba de hipótesis para determinar si la diferencia es estadísticamente significativa o no. Sin embargo, la superposición de los intervalos de confianza puede ser una indicación inicial de que la diferencia no es significativa y que no se debe buscar más evidencia.</strong></p>
</div>
</div>
<div id="ejercicio-2" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Ejercicio 2<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ejercicio-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>PREGUNTA</strong></p>
<p>Utilizando la variable monto mínimo mensual que requiere su hogar para vivir (P08).</p>
<p>Calcule:</p>
<ul>
<li><p>Brinde el estimador puntual de la media poblacional.</p></li>
<li><p>Calcule el intervalo de confianza de la media poblacional.</p></li>
<li><p>Calcule los intervalos de confianza de la media según si el individuo vive en el área urbana o rural (area2). En otras palabras, compare la media de la variable en esos dos grupos.</p></li>
<li><p>Realice un gráfico de barras de error. Existe indicio de DIFERENCIA entre los dos grupos?</p></li>
</ul>
<blockquote>
<p>Tienes 15 minutos!</p>
</blockquote>
</div>
<div id="intervalo-de-una-proporción" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Intervalo de una proporción<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#intervalo-de-una-proporción" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="definición" class="section level3 hasAnchor" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Definición<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#definición" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En estadística, el intervalo de una proporción es un rango de valores posibles para la proporción de una característica en una población, que se estima a partir de una muestra aleatoria de la población. Al igual que con la media, el intervalo de una proporción se construye utilizando un nivel de confianza específico y se utiliza para determinar la precisión de la estimación de la proporción en la población.</p>
<p>Por ejemplo, si se desea estimar la proporción de personas en una población que votará por un candidato específico, se puede seleccionar una muestra aleatoria de la población y estimar la proporción de personas que votarán por ese candidato en la muestra. A partir de esta estimación, se puede construir un intervalo de confianza que contendrá el valor real de la proporción en la población con un cierto nivel de confianza.</p>
<p>El ancho del intervalo depende del tamaño de la muestra y del nivel de confianza especificado. A medida que el tamaño de la muestra aumenta, el intervalo se estrecha y se vuelve más preciso. Del mismo modo, a medida que se aumenta el nivel de confianza, el intervalo se amplía y se vuelve menos preciso.</p>
<p>El intervalo de una proporción es una herramienta útil en la inferencia estadística, ya que permite a los investigadores cuantificar la incertidumbre en una estimación de la proporción y determinar si una diferencia entre dos proporciones es estadísticamente significativa.</p>
</div>
<div id="fórmula" class="section level3 hasAnchor" number="5.6.2">
<h3><span class="header-section-number">5.6.2</span> Fórmula<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#fórmula" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Recuerda que en este caso, al igual que en la media, todo gira en torno a los principios de la curva normal, el número de desviaciones estándar/errores estándar a la izquierda y a la derecha, el teorema central del límite y la ley de los grandes números. Si alguno de estos conceptos no están claros, te recomiendo regresar a la sesión 4 y repasarlos!</p>
</blockquote>
<p>Para calcular el intervalo de confianza de una proporción variamos un poco la fórmula que ya conocemos hasta ahora.</p>
<p>Primero hay que tener en cuenta que cuando calculamos la proporción, nos estamos refiriendo específicamente a la proporción de <strong>UNA CATEGORÍA</strong> de una variable <strong>CATEGÓRICA</strong>. Hago el énfasis en ello porque siempre se genera la confusión de “a qué le estoy calculando la proporción”.</p>
<p>Dicho de otra manera, nosotros debemos poner el ojo en una categoría de una variable nominal/ordinal al principio de este cálculo.</p>
<p><span class="math display">\[\text{Intervalo de confianza para una proporción: } \hat{p} \pm z \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<p>Donde:</p>
<p><span class="math inline">\(\hat{p}\)</span> = Proporción muestral de la categoría elegida</p>
<p>z = Puntuación crítica dependiendo de nuestro nivel de confianza elegido</p>
<p><span class="math inline">\(\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span> = Error estándar de una proporción</p>
</div>
<div id="ic-de-proporción-con-la-fórmula" class="section level3 hasAnchor" number="5.6.3">
<h3><span class="header-section-number">5.6.3</span> IC de proporción con la fórmula<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-de-proporción-con-la-fórmula" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Primero ubiquemos una variable categórica. Utilicemos la p11.1:</p>
<p>¿Qué tan desigual es el acceso de los peruanos a la EDUCACIÓN?
1. Muy desigual
2. Poco desigual
3. Nada desigual</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb140-1" tabindex="-1"></a><span class="co">#Configuramos nuestra variable como factor</span></span>
<span id="cb140-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb140-2" tabindex="-1"></a>enades<span class="sc">$</span>p11<span class="fl">.1</span><span class="ot">&lt;-</span><span class="fu">factor</span>(enades<span class="sc">$</span>p11<span class="fl">.1</span>, <span class="co"># Nombre de la variable a convertir</span></span>
<span id="cb140-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb140-3" tabindex="-1"></a>                     <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="co"># Definimos los niveles (esta variable sólo tenía 2 niveles)</span></span>
<span id="cb140-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb140-4" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Muy desigual&quot;</span>, <span class="st">&quot;Poco desigual&quot;</span>, <span class="st">&quot;Nada desigual&quot;</span>)) <span class="co">#Colocamos sus etiquetas</span></span></code></pre></div>
<p>La muestra se divide entre estas tres opciones. Ahora elegimos <strong>UNA CATEGORÍA</strong> de estas tres a la que vamos a calcular la proporción. En este caso vamos a elegir la proporción de individuos que afirmó que el acceso a la educación en el Perú es “Muy desigual”.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb141-1" tabindex="-1"></a><span class="co">#Calculamos p</span></span>
<span id="cb141-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb141-2" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb141-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb141-3" tabindex="-1"></a>  <span class="fu">count</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb141-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb141-4" tabindex="-1"></a>  <span class="fu">drop_na</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span></span>
<span id="cb141-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb141-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p=</span>n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   p11.1             n      p
##   &lt;fct&gt;         &lt;int&gt;  &lt;dbl&gt;
## 1 Muy desigual    912 0.610 
## 2 Poco desigual   503 0.336 
## 3 Nada desigual    80 0.0535</code></pre>
<p>Ahora sabemos que nuestro <span class="math inline">\(\hat{p}\)</span> = 0.59</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb143-1" tabindex="-1"></a>p<span class="ot">&lt;-</span><span class="fl">0.61003344</span></span></code></pre></div>
<p>El número total de casos es:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb144-1" tabindex="-1"></a>n<span class="ot">&lt;-</span> <span class="dv">912</span><span class="sc">+</span><span class="dv">503</span><span class="sc">+</span><span class="dv">80</span></span></code></pre></div>
<p>Ahora definimos la puntuación crítica. Cuánto era para 95% de confianza?</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb145-1" tabindex="-1"></a>z<span class="ot">&lt;-</span><span class="fl">1.96</span></span></code></pre></div>
<p>Ahora el error estándar <span class="math inline">\(\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span></p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb146-1" tabindex="-1"></a>error_estandar<span class="ot">&lt;-</span> <span class="fu">sqrt</span>((p<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p))<span class="sc">/</span>n)</span></code></pre></div>
<p>Nuestro límite inferior es la proporción muestral menos z*error estándar:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb147-1" tabindex="-1"></a>limite_inferior<span class="ot">&lt;-</span> p<span class="sc">-</span>z<span class="sc">*</span>error_estandar</span>
<span id="cb147-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb147-2" tabindex="-1"></a>limite_inferior</span></code></pre></div>
<pre><code>## [1] 0.585309</code></pre>
<p>Y el límite superior es la proporción muestral más z*error estándar:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb149-1" tabindex="-1"></a>limite_superior<span class="ot">&lt;-</span> p<span class="sc">+</span>z<span class="sc">*</span>error_estandar</span>
<span id="cb149-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb149-2" tabindex="-1"></a>limite_superior</span></code></pre></div>
<pre><code>## [1] 0.6347579</code></pre>
<p>Lo podemos colocar todo en un data frame</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb151-1" tabindex="-1"></a>resultados<span class="ot">&lt;-</span><span class="fu">data.frame</span>(p, error_estandar, limite_inferior, limite_superior)</span>
<span id="cb151-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb151-2" tabindex="-1"></a>resultados <span class="sc">|&gt;</span> </span>
<span id="cb151-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb151-3" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">|&gt;</span> </span>
<span id="cb151-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb151-4" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
p
</th>
<th style="text-align:right;">
error_estandar
</th>
<th style="text-align:right;">
limite_inferior
</th>
<th style="text-align:right;">
limite_superior
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.6100334
</td>
<td style="text-align:right;">
0.0126145
</td>
<td style="text-align:right;">
0.585309
</td>
<td style="text-align:right;">
0.6347579
</td>
</tr>
</tbody>
</table>
</div>
<div id="ic-de-proporción-con-prop.test" class="section level3 hasAnchor" number="5.6.4">
<h3><span class="header-section-number">5.6.4</span> IC de proporción con <code>prop.test()</code><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-de-proporción-con-prop.test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora bien, también podemos utilizar la función <code>prop.test()</code>:</p>
<p>Recordemos:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb152-1" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb152-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb152-2" tabindex="-1"></a>  <span class="fu">count</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb152-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb152-3" tabindex="-1"></a>  <span class="fu">drop_na</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb152-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb152-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p=</span>n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   p11.1             n      p
##   &lt;fct&gt;         &lt;int&gt;  &lt;dbl&gt;
## 1 Muy desigual    912 0.610 
## 2 Poco desigual   503 0.336 
## 3 Nada desigual    80 0.0535</code></pre>
<p>Colocamos la <strong>frecuencia</strong> de la categoría elegida y el tamaño total de la muestra.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb154-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">912</span>, <span class="dv">1495</span>)<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 0.5847202 0.6347751
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<blockquote>
<p>Por qué colocamos frecuencia? Porque así está configurada esta función.</p>
</blockquote>
</div>
<div id="ic-de-proporción-según-grupos" class="section level3 hasAnchor" number="5.6.5">
<h3><span class="header-section-number">5.6.5</span> IC de proporción según grupos<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ic-de-proporción-según-grupos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora comparemos la proporción elegida (aquellos que creen que el acceso de los peruanos a la EDUCACIÓN es MUY DESIGUAL) entre el sector rural y urbano (area2).</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb156-1" tabindex="-1"></a>enades<span class="sc">$</span>area2<span class="ot">&lt;-</span> <span class="fu">factor</span>(enades<span class="sc">$</span>area2, <span class="co"># Nombre de la variable a convertir</span></span>
<span id="cb156-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb156-2" tabindex="-1"></a>                     <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="co"># Definimos los niveles (esta variable sólo tenía 2 niveles)</span></span>
<span id="cb156-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb156-3" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Urbano&quot;</span>, <span class="st">&quot;Rural&quot;</span>)) <span class="co">#Colocamos sus etiquetas</span></span></code></pre></div>
<p>Primero, nos tenemos que preguntar cuál es la frecuencia en cada grupo</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb157-1" tabindex="-1"></a>enades <span class="sc">|&gt;</span> </span>
<span id="cb157-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb157-2" tabindex="-1"></a>  <span class="fu">group_by</span>(area2) <span class="sc">|&gt;</span> </span>
<span id="cb157-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb157-3" tabindex="-1"></a>  <span class="fu">drop_na</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span></span>
<span id="cb157-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb157-4" tabindex="-1"></a>  <span class="fu">count</span>(p11<span class="fl">.1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb157-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb157-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p=</span>n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
## # Groups:   area2 [2]
##   area2  p11.1             n      p
##   &lt;fct&gt;  &lt;fct&gt;         &lt;int&gt;  &lt;dbl&gt;
## 1 Urbano Muy desigual    769 0.618 
## 2 Urbano Poco desigual   409 0.329 
## 3 Urbano Nada desigual    67 0.0538
## 4 Rural  Muy desigual    143 0.572 
## 5 Rural  Poco desigual    94 0.376 
## 6 Rural  Nada desigual    13 0.052</code></pre>
<p>Ahora calculamos la función teniendo en cuenta que:</p>
<ul>
<li>En el primer grupo hay 769 casos de éxito de un total de 1273.</li>
</ul>
<p>Lo ingresamos a la función:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb159-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">769</span>), <span class="at">n=</span><span class="fu">c</span>(<span class="dv">769</span><span class="sc">+</span><span class="dv">409</span><span class="sc">+</span><span class="dv">67</span>))<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 0.5899485 0.6446582
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<ul>
<li>En el segundo grupo hay 143 casos de éxito de un total de 257.</li>
</ul>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb161-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">143</span>), <span class="at">n=</span><span class="fu">c</span>(<span class="dv">143</span><span class="sc">+</span><span class="dv">94</span><span class="sc">+</span><span class="dv">13</span>))<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 0.5080285 0.6337218
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>Lo podemos ordenar en un data.frame.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb163-1" tabindex="-1"></a>resultados_prop<span class="ot">&lt;-</span>  <span class="fu">data.frame</span>(<span class="at">Grupo =</span><span class="fu">c</span>(<span class="st">&quot;Urbano&quot;</span>, <span class="st">&quot;Rural&quot;</span>), </span>
<span id="cb163-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb163-2" tabindex="-1"></a>                              <span class="at">P =</span><span class="fu">c</span>(<span class="fl">0.61767068</span>, <span class="fl">0.57200000</span>   ), </span>
<span id="cb163-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb163-3" tabindex="-1"></a>                              <span class="at">Lim_inf=</span><span class="fu">c</span>(<span class="fl">0.5899485</span>, <span class="fl">0.5080285</span>), </span>
<span id="cb163-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb163-4" tabindex="-1"></a>                              <span class="at">Lim_sup=</span> <span class="fu">c</span>(<span class="fl">0.6446582</span>,<span class="fl">0.6337218</span>))</span></code></pre></div>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb164-1" tabindex="-1"></a>resultados_prop</span></code></pre></div>
<pre><code>##    Grupo         P   Lim_inf   Lim_sup
## 1 Urbano 0.6176707 0.5899485 0.6446582
## 2  Rural 0.5720000 0.5080285 0.6337218</code></pre>
<p>Lo visualizamos:</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb166-1" tabindex="-1"></a>resultados_prop <span class="sc">|&gt;</span> <span class="co">#Data</span></span>
<span id="cb166-2"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb166-2" tabindex="-1"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span>       <span class="co">#Iniciamos el ggplot. A partir de ahora son +! ya no |&gt;!</span></span>
<span id="cb166-3"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb166-3" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">y=</span>p, <span class="at">x=</span>Grupo)<span class="sc">+</span>  <span class="co">#Los grupos en el eje X y la media en el eje Y</span></span>
<span id="cb166-4"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb166-4" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>Lim_inf, <span class="at">ymax=</span>Lim_sup), <span class="at">width=</span><span class="fl">0.2</span>)<span class="sc">+</span> <span class="co">#Graficamos la barra de error</span></span>
<span id="cb166-5"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb166-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Procedencia&quot;</span>) <span class="sc">+</span> <span class="co">#Etiqueta del eje X</span></span>
<span id="cb166-6"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb166-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;P la cobertura en educación es Muy Desigual&quot;</span>) <span class="co"># Etiqueta del eje y</span></span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<p>Otra alternativa es pedirlos al mismo tiempo en la función <code>prop.test()</code>. En este caso lo que nos muestra, es el <strong>intervalo de la diferencia</strong>.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#cb167-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">769</span>, <span class="dv">143</span>), <span class="at">n=</span><span class="fu">c</span>(<span class="dv">1273</span>, <span class="dv">257</span>))<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] -0.02108879  0.11641800
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>En este caso, se sigue la siguiente interpretación:</p>
<p>Si el intervalo de confianza no contiene el valor cero, esto sugiere que las proporciones de los dos grupos son significativamente diferentes y que la hipótesis nula de que las proporciones son iguales debe ser rechazada. Por otro lado, si el intervalo de confianza contiene el valor cero, no podemos rechazar la hipótesis nula y no podemos concluir que las proporciones son significativamente diferentes.</p>
</div>
</div>
<div id="ejercicio-3" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> Ejercicio 3<a href="ic-para-una-media-y-una-proporción-ic-entre-grupos.html#ejercicio-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>PREGUNTA</strong></p>
<p>Utilizando la variable “ideología2” (1: Izquierda, 2:Centro, 3:Derecha):</p>
<p>Realice lo siguiente:</p>
<ul>
<li><p>Brinde el estimador puntual de la proporción de población de Izquierda en el Perú.</p></li>
<li><p>Calcule el intervalo de confianza de la proporción poblacional de Izquierda en el Perú.</p></li>
<li><p>Calcule por separado, utilizando prop.test(), la proporción de población de izquierda en el área urbano y rural (area2).</p></li>
<li><p>Mediante la función prop.test(), compare los dos grupos y evalúe el intervalo de confianza de la diferencia en los p poblacionales.</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introducción-a-la-estadística-inferencial-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="prueba-de-hipótesis-t.test-y-prop.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ChristianChiroqueR/Estadistica_AP_1_PUCP/edit/master/05-inferencia_2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ChristianChiroqueR/Estadistica_AP_1_PUCP/blob/master/05-inferencia_2.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
