<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Sesión 2 Manipulación de datos y estadísticos descriptivos | Estadística para el Análisis Político I</title>
  <meta name="description" content="Sesión 2 Manipulación de datos y estadísticos descriptivos | Estadística para el Análisis Político I" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Sesión 2 Manipulación de datos y estadísticos descriptivos | Estadística para el Análisis Político I" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Sesión 2 Manipulación de datos y estadísticos descriptivos | Estadística para el Análisis Político I" />
  
  
  

<meta name="author" content="Docente: Christian Chiroque Ruiz" />


<meta name="date" content="2023-09-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="visualización-de-datos-con-ggplot2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística AP I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#los-pilares-de-la-estadística-prueba"><i class="fa fa-check"></i><b>1.1</b> Los pilares de la Estadística PRUEBA</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#definición"><i class="fa fa-check"></i><b>1.1.1</b> Definición</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#unidad-de-análisis"><i class="fa fa-check"></i><b>1.1.2</b> Unidad de análisis</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#tipos-de-variable"><i class="fa fa-check"></i><b>1.1.3</b> Tipos de variable</a></li>
<li class="chapter" data-level="1.1.4" data-path="index.html"><a href="index.html#escalas-de-medición"><i class="fa fa-check"></i><b>1.1.4</b> Escalas de medición</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#los-objetos-elementos-básicos-en-el-r"><i class="fa fa-check"></i><b>1.2</b> Los objetos: elementos básicos en el R</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#las-estructuras-en-el-r"><i class="fa fa-check"></i><b>1.3</b> Las Estructuras en el R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#los-vectores"><i class="fa fa-check"></i><b>1.3.1</b> Los vectores</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#un-vector-especial-los-factores"><i class="fa fa-check"></i><b>1.3.2</b> Un vector especial: los factores</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#data-frames"><i class="fa fa-check"></i><b>1.3.3</b> Data frames</a></li>
<li class="chapter" data-level="1.3.4" data-path="index.html"><a href="index.html#propiedades"><i class="fa fa-check"></i><b>1.3.4</b> Propiedades</a></li>
<li class="chapter" data-level="1.3.5" data-path="index.html"><a href="index.html#índices"><i class="fa fa-check"></i><b>1.3.5</b> Índices</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#nuestras-herramientas-paquetes-y-funciones"><i class="fa fa-check"></i><b>1.4</b> Nuestras herramientas: Paquetes y funciones</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#paquetes"><i class="fa fa-check"></i><b>1.4.1</b> Paquetes</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#funciones"><i class="fa fa-check"></i><b>1.4.2</b> Funciones</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#abrir-una-base-de-datos"><i class="fa fa-check"></i><b>1.5</b> Abrir una base de datos</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#manipulación-de-datos-con-tidyverse"><i class="fa fa-check"></i><b>1.6</b> Manipulación de datos con Tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html"><i class="fa fa-check"></i><b>2</b> Manipulación de datos y estadísticos descriptivos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#preparación"><i class="fa fa-check"></i><b>2.1</b> Preparación</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#entorno-de-trabajo"><i class="fa fa-check"></i><b>2.1.1</b> Entorno de trabajo</a></li>
<li class="chapter" data-level="2.1.2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#paquetes-a-utilizar"><i class="fa fa-check"></i><b>2.1.2</b> Paquetes a utilizar</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#base-de-datos"><i class="fa fa-check"></i><b>2.2</b> Base de datos</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#importación"><i class="fa fa-check"></i><b>2.2.1</b> Importación</a></li>
<li class="chapter" data-level="2.2.2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#verificar-el-tipo-de-variable"><i class="fa fa-check"></i><b>2.2.2</b> Verificar el tipo de variable</a></li>
<li class="chapter" data-level="2.2.3" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#creación-de-subset"><i class="fa fa-check"></i><b>2.2.3</b> Creación de subset</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-tendencia-central"><i class="fa fa-check"></i><b>2.3</b> Estadísticos de tendencia central</a></li>
<li class="chapter" data-level="2.4" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-posición"><i class="fa fa-check"></i><b>2.4</b> Estadísticos de posición</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#percentiles"><i class="fa fa-check"></i><b>2.4.1</b> Percentiles</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-dispersión"><i class="fa fa-check"></i><b>2.5</b> Estadísticos de dispersión</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#el-rango"><i class="fa fa-check"></i><b>2.5.1</b> El Rango</a></li>
<li class="chapter" data-level="2.5.2" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#la-varianza"><i class="fa fa-check"></i><b>2.5.2</b> La Varianza</a></li>
<li class="chapter" data-level="2.5.3" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#la-desviación-estándar"><i class="fa fa-check"></i><b>2.5.3</b> La Desviación Estándar</a></li>
<li class="chapter" data-level="2.5.4" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#el-rango-intercuartílico"><i class="fa fa-check"></i><b>2.5.4</b> El Rango intercuartílico</a></li>
<li class="chapter" data-level="2.5.5" data-path="manipulación-de-datos-y-estadísticos-descriptivos.html"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#curvas-de-distribución-de-frecuencias"><i class="fa fa-check"></i><b>2.5.5</b> Curvas de distribución de frecuencias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html"><i class="fa fa-check"></i><b>3</b> Visualización de datos con ggplot2</a>
<ul>
<li class="chapter" data-level="3.1" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#ggplot2-una-herramienta-para-la-visualización"><i class="fa fa-check"></i><b>3.1</b> GGPLOT2: Una herramienta para la visualización</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#descripción"><i class="fa fa-check"></i><b>3.1.1</b> Descripción</a></li>
<li class="chapter" data-level="3.1.2" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#las-siete-capas"><i class="fa fa-check"></i><b>3.1.2</b> Las siete capas</a></li>
<li class="chapter" data-level="3.1.3" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#slow-ggplot"><i class="fa fa-check"></i><b>3.1.3</b> Slow ggplot</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html#código"><i class="fa fa-check"></i><b>3.2</b> Código</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html"><i class="fa fa-check"></i><b>4</b> Estadística Inferencial: Introducción</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#antecedentes-relevantes"><i class="fa fa-check"></i><b>4.1</b> Antecedentes relevantes</a></li>
<li class="chapter" data-level="4.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#elementos-básicos-de-probabilidad"><i class="fa fa-check"></i><b>4.2</b> Elementos básicos de probabilidad</a></li>
<li class="chapter" data-level="4.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#ejercicio-con-r"><i class="fa fa-check"></i><b>4.3</b> Ejercicio con R</a></li>
<li class="chapter" data-level="4.4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#elementos-básicos-de-la-inferencia"><i class="fa fa-check"></i><b>4.4</b> Elementos básicos de la inferencia</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#definiciones-preliminares"><i class="fa fa-check"></i><b>4.4.1</b> Definiciones preliminares</a></li>
<li class="chapter" data-level="4.4.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#estimación-puntual"><i class="fa fa-check"></i><b>4.4.2</b> Estimación puntual</a></li>
<li class="chapter" data-level="4.4.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#error-de-muestreo"><i class="fa fa-check"></i><b>4.4.3</b> Error de muestreo</a></li>
<li class="chapter" data-level="4.4.4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#distribuciones-de-muestreo."><i class="fa fa-check"></i><b>4.4.4</b> Distribuciones de muestreo.</a></li>
<li class="chapter" data-level="4.4.5" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#error-estándar"><i class="fa fa-check"></i><b>4.4.5</b> Error estándar</a></li>
<li class="chapter" data-level="4.4.6" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#teorema-del-límite-central"><i class="fa fa-check"></i><b>4.4.6</b> Teorema del límite central</a></li>
<li class="chapter" data-level="4.4.7" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#ley-de-los-grandes-números"><i class="fa fa-check"></i><b>4.4.7</b> Ley de los grandes números</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#intervalo-de-confianza-de-una-media"><i class="fa fa-check"></i><b>4.5</b> Intervalo de confianza de una media</a></li>
<li class="chapter" data-level="4.6" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#ejercicio-con-r-enades-2022"><i class="fa fa-check"></i><b>4.6</b> Ejercicio con R: ENADES 2022</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#abrir-base-de-datos"><i class="fa fa-check"></i><b>4.6.1</b> Abrir base de datos</a></li>
<li class="chapter" data-level="4.6.2" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#identificar-una-variable-numérica"><i class="fa fa-check"></i><b>4.6.2</b> Identificar una variable numérica</a></li>
<li class="chapter" data-level="4.6.3" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#cálculo-del-estimador-puntual-media-muestral"><i class="fa fa-check"></i><b>4.6.3</b> Cálculo del estimador puntual: media muestral</a></li>
<li class="chapter" data-level="4.6.4" data-path="estadística-inferencial-introducción.html"><a href="estadística-inferencial-introducción.html#cálculo-del-intervalo-de-confianza-al-95"><i class="fa fa-check"></i><b>4.6.4</b> Cálculo del intervalo de confianza al 95%</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística para el Análisis Político I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="manipulación-de-datos-y-estadísticos-descriptivos" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Sesión 2</span> Manipulación de datos y estadísticos descriptivos<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#manipulación-de-datos-y-estadísticos-descriptivos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="preparación" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Preparación<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#preparación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="entorno-de-trabajo" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Entorno de trabajo<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#entorno-de-trabajo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Crea la carpeta donde guardarás toda la información creada.</p></li>
<li><p>Te recomiendo que para cada clase crees un Proyecto de R. Eso te permitirá mantener un orden.</p></li>
<li><p>Una vez creado, puedes crear un R Markdown como este para empezar a trabajar.</p></li>
</ul>
</div>
<div id="paquetes-a-utilizar" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Paquetes a utilizar<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#paquetes-a-utilizar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Ahora bien, DE PREFERENCIA, siempre que inicies un R Markdown o Script en el R Studio tienes que abrir los paquetes que vas a utilizar. En este caso vamos a utilizar el paquete Tidyverse (que ya incluye muchos otros paquetes ya explicados). Puedes abrirlo con el siguiente comando:</li>
</ul>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb64-1" tabindex="-1"></a><span class="co"># install.packages(&quot;tidyverse&quot;)</span></span>
<span id="cb64-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb64-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<ul>
<li>Recuerda que la función library(nombre_del_paquete) sirve para abrir los paquetes YA INSTALADOS. Si te sale un mensaje que dice que “no existe el paquete” debes instalarlo con la función install.packages(línea previa).</li>
</ul>
<hr />
</div>
</div>
<div id="base-de-datos" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Base de datos<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#base-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="importación" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Importación<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#importación" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para la parte I, II y III de esta clase utilizaremos la base de datos de los resultados de las elecciones presidenciales del 2011.</p>
<p>Vamos a realizar un breve reporte sobre los porcentajes obtenidos por la organización política “Gana Perú”.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb65-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb65-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb65-2" tabindex="-1"></a>elecciones <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;RESULTADOS_EG_PRESIDENCIAL_2011.xls&quot;</span>)</span></code></pre></div>
<p>Luego de abrir una base de datos, siempre te recomiendo darle un primer vistazo.</p>
<p>Puedes ver las primeras diez filas con:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb66-1" tabindex="-1"></a><span class="fu">head</span>(elecciones, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 11
##    UBIGEO DEPARTAMENTO PROVINCIA  
##    &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;      
##  1 010101 AMAZONAS     CHACHAPOYAS
##  2 010101 AMAZONAS     CHACHAPOYAS
##  3 010101 AMAZONAS     CHACHAPOYAS
##  4 010101 AMAZONAS     CHACHAPOYAS
##  5 010101 AMAZONAS     CHACHAPOYAS
##  6 010101 AMAZONAS     CHACHAPOYAS
##  7 010101 AMAZONAS     CHACHAPOYAS
##  8 010101 AMAZONAS     CHACHAPOYAS
##  9 010101 AMAZONAS     CHACHAPOYAS
## 10 010101 AMAZONAS     CHACHAPOYAS
## # ℹ 8 more variables:
## #   DISTRITO &lt;chr&gt;,
## #   ORGANIZACIÓN_POLITICA &lt;chr&gt;,
## #   VOTOS_VALIDOS_OP &lt;dbl&gt;,
## #   VOTOS_VALIDOS &lt;dbl&gt;,
## #   VOTOS_BLANCO &lt;dbl&gt;,
## #   VOTOS_NULOS &lt;dbl&gt;, …</code></pre>
<p>También puedes hacerle click en Environment o colocar:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb68-1" tabindex="-1"></a><span class="co">#View(elecciones)</span></span></code></pre></div>
</div>
<div id="verificar-el-tipo-de-variable" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Verificar el tipo de variable<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#verificar-el-tipo-de-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Veamos las variables, podemos utilizar la función <code>names(nombre_de_data)</code></p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb69-1" tabindex="-1"></a><span class="fu">names</span>(elecciones)</span></code></pre></div>
<pre><code>##  [1] &quot;UBIGEO&quot;               
##  [2] &quot;DEPARTAMENTO&quot;         
##  [3] &quot;PROVINCIA&quot;            
##  [4] &quot;DISTRITO&quot;             
##  [5] &quot;ORGANIZACIÓN_POLITICA&quot;
##  [6] &quot;VOTOS_VALIDOS_OP&quot;     
##  [7] &quot;VOTOS_VALIDOS&quot;        
##  [8] &quot;VOTOS_BLANCO&quot;         
##  [9] &quot;VOTOS_NULOS&quot;          
## [10] &quot;NUMERO_ELECTORES&quot;     
## [11] &quot;VOTOS_EMITIDOS&quot;</code></pre>
<p>Puedes editar los nombres si deseas. En este caso vamos a cambiar el nombre de la variable <strong>ORGANIZACIÓN_POLITICA</strong> por <strong>ORG_POL</strong>.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb71-1" tabindex="-1"></a>elecciones<span class="ot">&lt;-</span> elecciones <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">ORG_POL=</span>ORGANIZACIÓN_POLITICA)</span></code></pre></div>
<blockquote>
<p><strong>Observación: Ten en cuenta que aquí estamos sobre escribiendo.</strong></p>
</blockquote>
<p>Veamos si el formato es adecuado.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb72-1" tabindex="-1"></a><span class="fu">str</span>(elecciones)</span></code></pre></div>
<pre><code>## tibble [23,958 × 11] (S3: tbl_df/tbl/data.frame)
##  $ UBIGEO          : chr [1:23958] &quot;010101&quot; &quot;010101&quot; &quot;010101&quot; &quot;010101&quot; ...
##  $ DEPARTAMENTO    : chr [1:23958] &quot;AMAZONAS&quot; &quot;AMAZONAS&quot; &quot;AMAZONAS&quot; &quot;AMAZONAS&quot; ...
##  $ PROVINCIA       : chr [1:23958] &quot;CHACHAPOYAS&quot; &quot;CHACHAPOYAS&quot; &quot;CHACHAPOYAS&quot; &quot;CHACHAPOYAS&quot; ...
##  $ DISTRITO        : chr [1:23958] &quot;CHACHAPOYAS&quot; &quot;CHACHAPOYAS&quot; &quot;CHACHAPOYAS&quot; &quot;CHACHAPOYAS&quot; ...
##  $ ORG_POL         : chr [1:23958] &quot;FUERZA NACIONAL&quot; &quot;PARTIDO POLITICO ADELANTE&quot; &quot;DESPERTAR NACIONAL&quot; &quot;GANA PERU&quot; ...
##  $ VOTOS_VALIDOS_OP: num [1:23958] 6 24 35 2971 7 ...
##  $ VOTOS_VALIDOS   : num [1:23958] 11148 11148 11148 11148 11148 ...
##  $ VOTOS_BLANCO    : num [1:23958] 1034 1034 1034 1034 1034 ...
##  $ VOTOS_NULOS     : num [1:23958] 340 340 340 340 340 340 340 340 340 340 ...
##  $ NUMERO_ELECTORES: num [1:23958] 15748 15748 15748 15748 15748 ...
##  $ VOTOS_EMITIDOS  : num [1:23958] 12522 12522 12522 12522 12522 ...</code></pre>
<p>Ok, los caracteres están como <code>chr</code> y las variables numéricas como <code>num.</code></p>
</div>
<div id="creación-de-subset" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Creación de subset<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#creación-de-subset" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Aquí nos debemos preguntar: a lo largo de nuestro trabajo, vamos a utilizar toda la data o sólo una parte?</p>
<p>En este caso puntual, sólo vamos a utilizar aquellos resultados de la organización política Gana Perú. Por ello, vamos a hacer un filtro con ese criterio y vamos a **crear un subset o una data ya filtrada”.</p>
<p>A esta data la llamaremos <strong>elecciones_GN</strong>.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb74-1" tabindex="-1"></a>elecciones_GN <span class="ot">&lt;-</span> elecciones<span class="sc">%&gt;%</span> <span class="fu">filter</span>(ORG_POL<span class="sc">==</span><span class="st">&quot;GANA PERU&quot;</span>) </span></code></pre></div>
<hr />
</div>
</div>
<div id="estadísticos-de-tendencia-central" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Estadísticos de tendencia central<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-tendencia-central" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Como nuestro objetivo es explorar el porcentaje de votos válidos obtenidos por Gana Perú, vamos a crear esa variable en base a dos variable observables: el número de votos obtenidos y el número total de votos válidos.</p>
<p>Utilizamos la función <code>mutate()</code>.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb75-1" tabindex="-1"></a>elecciones_GN<span class="ot">&lt;-</span>elecciones_GN <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">porc.voto=</span>VOTOS_VALIDOS_OP<span class="sc">/</span>VOTOS_VALIDOS<span class="sc">*</span><span class="dv">100</span>)</span></code></pre></div>
<p>Ahora podemos calculas los tres estadísticos de tendencia central con la función <code>summarise()</code>.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb76-1" tabindex="-1"></a>elecciones_GN<span class="sc">%&gt;%</span> </span>
<span id="cb76-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb76-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Media=</span><span class="fu">mean</span>(porc.voto, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-3"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb76-3" tabindex="-1"></a>            <span class="at">Mediana=</span><span class="fu">median</span>(porc.voto, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   Media Mediana
##   &lt;dbl&gt;   &lt;dbl&gt;
## 1  38.9    35.1</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb78-1" tabindex="-1"></a><span class="co"># Recuerda que colocamos na.rm = TRUE para que haga el cálculo omitiendo</span></span>
<span id="cb78-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb78-2" tabindex="-1"></a><span class="co"># aquellas celdas vacías (valores perdidos)</span></span></code></pre></div>
<hr />
</div>
<div id="estadísticos-de-posición" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Estadísticos de posición<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-posición" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="percentiles" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Percentiles<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#percentiles" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Los estadísticos de posición son medidas que indican la posición relativa de un valor dentro de un conjunto de datos ordenados de menor a mayor.</p></li>
<li><p>Los estadísticos de posición más utilizados son los percentiles (y sus derivados que son los cuartiles y deciles).</p></li>
<li><p>Los estadísticos de posición son útiles para resumir los datos y obtener información sobre la distribución de los mismos.</p></li>
<li><p>Se utilizan para describir la dispersión de los datos alrededor de la mediana, así como identificar valores atípicos o extremos en el conjunto de datos.</p></li>
</ul>
<p>Para calcular un determinado percentil podemos solicitarlo utilizando la función <code>summarise()</code> junto con <code>quantile()</code>. Vamos a solicitar los cuartiles (el percentil 25, 50 y 75) de la variable porc.voto:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb79-1" tabindex="-1"></a>elecciones_GN <span class="sc">%&gt;%</span> </span>
<span id="cb79-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb79-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">P25=</span><span class="fu">quantile</span>(porc.voto, <span class="fl">0.25</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb79-3"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb79-3" tabindex="-1"></a>            <span class="at">P50=</span><span class="fu">quantile</span>(porc.voto, <span class="fl">0.50</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb79-4"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb79-4" tabindex="-1"></a>            <span class="at">P75=</span><span class="fu">quantile</span>(porc.voto, <span class="fl">0.75</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##     P25   P50   P75
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  21.6  35.1  56.0</code></pre>
<p>Si son muchos percentiles también puedes usar la función concatenar <code>c()</code>, como en el siguiente ejemplo:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb81-1" tabindex="-1"></a>elecciones_GN <span class="sc">%&gt;%</span> </span>
<span id="cb81-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb81-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">quantile</span>(porc.voto, <span class="fu">c</span>(<span class="fl">0.10</span>, <span class="fl">0.25</span>,<span class="fl">0.50</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>), <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## Warning: Returning more (or less) than 1 row
## per `summarise()` group was
## deprecated in dplyr 1.1.0.
## ℹ Please use `reframe()` instead.
## ℹ When switching from `summarise()`
##   to `reframe()`, remember that
##   `reframe()` always returns an
##   ungrouped data frame and adjust
##   accordingly.
## Call
## `lifecycle::last_lifecycle_warnings()`
## to see where this warning was
## generated.</code></pre>
<pre><code>## # A tibble: 5 × 1
##   quantile(porc.voto, c(0.1, 0.25,…¹
##                                &lt;dbl&gt;
## 1                               11.4
## 2                               21.6
## 3                               35.1
## 4                               56.0
## 5                               70.7
## # ℹ abbreviated name:
## #   ¹​`quantile(porc.voto, c(0.1, 0.25, 0.5, 0.75, 0.9), na.rm = TRUE)`</code></pre>
<hr />
</div>
</div>
<div id="estadísticos-de-dispersión" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Estadísticos de dispersión<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#estadísticos-de-dispersión" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las medidas de dispersión son una serie de estadísticos que nos permiten conocer la variabilidad o amplitud de los datos en un conjunto de observaciones. Estas medidas nos indican cuánto se alejan los valores de la media, la mediana o cualquier otro estadístico de tendencia central, lo que es de gran utilidad para entender la homogeneidad o heterogeneidad de la distribución de los datos.</p>
<p>Las medidas de dispersión más comunes son el rango, la varianza, la desviación estándar, el rango intercuartílico y el coeficiente de variación.</p>
<div id="el-rango" class="section level3 hasAnchor" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> El Rango<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#el-rango" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El rango es una medida de dispersión que se utiliza para determinar la amplitud total de un conjunto de datos. Es la diferencia entre el valor máximo y el valor mínimo en un conjunto de datos. Es una medida muy sencilla de calcular y proporciona una idea general de la variabilidad de los datos. Sin embargo, no toma en cuenta la distribución de los datos en el conjunto, lo que puede hacer que la medida sea menos informativa en ciertos casos.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb84-1" tabindex="-1"></a>elecciones_GN <span class="sc">%&gt;%</span> </span>
<span id="cb84-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb84-2" tabindex="-1"></a>  <span class="fu">filter</span>(ORG_POL<span class="sc">==</span><span class="st">&quot;GANA PERU&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb84-3"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb84-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Rango=</span><span class="fu">max</span>(porc.voto, <span class="at">na.rm=</span><span class="cn">TRUE</span>)<span class="sc">-</span><span class="fu">min</span>(porc.voto, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   Rango
##   &lt;dbl&gt;
## 1  98.1</code></pre>
<p>En este caso vemos que los valores de la variable <strong>porc.voto</strong> tiene un rango de 98.1 unidades (porcentuales) .</p>
</div>
<div id="la-varianza" class="section level3 hasAnchor" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> La Varianza<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#la-varianza" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La varianza es una medida de dispersión que indica qué tan dispersos están los datos con respecto a su media.</p>
<p><span class="math display">\[\sigma^2 = \frac{\sum_{i=1}^n (x_i - \mu)^2}{n}\]</span></p>
<p>Matemáticamente, la varianza se define como la media aritmética de los cuadrados de las diferencias entre cada valor de la variable y la media.</p>
<p>Lo calculamos utilizando la función <code>var()</code>:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb86-1" tabindex="-1"></a>elecciones_GN <span class="sc">%&gt;%</span> </span>
<span id="cb86-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb86-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Varianza=</span><span class="fu">var</span>(porc.voto, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   Varianza
##      &lt;dbl&gt;
## 1     472.</code></pre>
<p>En este ejemplo, el porcentaje de los Votos obtenidos por Gana Perú tiene una dispersión de 472 entre los distritos del Perú.</p>
<blockquote>
<p>Recuerda que la varianza puede servir a la hora de comparar dos variable que están medidas en las mismas unidades (como si comparáramos este porcentaje vs el obtenido por Fuerza 2011). Si deseamos analizar una única variable es más fácil ver la <strong>Desviación Estándar</strong>.</p>
</blockquote>
</div>
<div id="la-desviación-estándar" class="section level3 hasAnchor" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> La Desviación Estándar<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#la-desviación-estándar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Es la medida de dispersión más común y se calcula como la raíz cuadrada de la varianza. Nos indica cuánto se desvían los valores de la distribución con respecto a la media.</p>
<p><span class="math display">\[\sqrt{\text{Var}(X)}\]</span></p>
<p>La desviación estándar se expresa en las mismas unidades que los datos originales, lo que la hace fácilmente interpretable.</p>
<p>Una desviación estándar pequeña indica que los datos están muy concentrados alrededor de la media, mientras que una desviación estándar grande indica que los datos están más dispersos y que existe una mayor variabilidad en los mismos.</p>
<p>Lo calculamos usando la función <code>sd()</code>:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb88-1" tabindex="-1"></a>elecciones_GN <span class="sc">%&gt;%</span> </span>
<span id="cb88-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb88-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Desv_est=</span><span class="fu">sd</span>(porc.voto, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   Desv_est
##      &lt;dbl&gt;
## 1     21.7</code></pre>
<p>La forma de interpretación es que <strong>los valores observados están en promedio a una distancia de 21 unidades de la media</strong>.</p>
</div>
<div id="el-rango-intercuartílico" class="section level3 hasAnchor" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> El Rango intercuartílico<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#el-rango-intercuartílico" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El rango intercuartil (IQR por sus siglas en inglés) es una medida de dispersión utilizada en estadística que se define como la diferencia entre el tercer y primer cuartil de un conjunto de datos. En otras palabras, el IQR mide la distancia entre el 25% y el 75% de los datos ordenados de menor a mayor.</p>
<p>El IQR es una medida de dispersión robusta que no se ve afectada por valores atípicos o extremos en los datos, a diferencia del rango o la desviación estándar. Es útil para resumir la variabilidad de los datos en un intervalo de valores que contiene la mayor parte de los datos y que no está influenciado por los valores extremos. El IQR se puede utilizar para identificar valores atípicos o para comparar la variabilidad entre diferentes conjuntos de datos.</p>
<p>Lo calculamos utilizando la función <code>IQR()</code>:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb90-1" tabindex="-1"></a>elecciones_GN <span class="sc">%&gt;%</span> </span>
<span id="cb90-2"><a href="manipulación-de-datos-y-estadísticos-descriptivos.html#cb90-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">IQR=</span><span class="fu">IQR</span>(porc.voto, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##     IQR
##   &lt;dbl&gt;
## 1  34.4</code></pre>
<p>En este caso vemos que el IQR de la variable porc.voto es de 34.4.</p>
<p>Es decir, la distancia entre el primer cuartil y el tercer cuartil es de 34 unidades en la escala de la variable (porcentaje).</p>
<hr />
</div>
<div id="curvas-de-distribución-de-frecuencias" class="section level3 hasAnchor" number="2.5.5">
<h3><span class="header-section-number">2.5.5</span> Curvas de distribución de frecuencias<a href="manipulación-de-datos-y-estadísticos-descriptivos.html#curvas-de-distribución-de-frecuencias" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Las curvas de distribución son representaciones gráficas de la distribución de una variable aleatoria. Estas curvas se utilizan para mostrar cómo se distribuyen los valores de una variable en un conjunto de datos.</p>
<p>El principal objetivo examinar las posiciones relativas de la media, la mediana y la moda, para estimar la FORMA DE UNA DISTRIBUCIÓN DE FRECUENCIAS.</p>
<p><img src="https://www.biologyforlife.com/uploads/2/2/3/9/22392738/c101b0da6ea1a0dab31f80d9963b0368_orig.png" /></p>
<p>Tenemos dos grandes opciones:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Distribución normal</strong>: Curva de distribución de frecuencias donde la media, la mediana y la moda de una variable son iguales entre sí y la distribución de la puntuaciones tiene forma de campana.</p></li>
<li><p><strong>Distribución sesgada</strong>: Curva de distribución de frecuencias en la cual la media, la mediana y la moda de una variable son desiguales y algunos de los sujetos tienen puntuaciones sumamente altas o bajas.</p></li>
</ol>
<p>Ahora veamos nuestro ejemplo, a qué curva de distribución se asemejará?</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>Vemos que nuestra variable de Porcentaje de votos valídos obtenido por Gana Perú a nivel distrital, posee una distribución con un sesgo positivo.</p>
<p>Veamos si es cierto la teoría. Grafiquemos la media (38.90), mediana (35.13) y moda (27.00) en dicha curva de distribución.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>Corroboramos lo explicitado por la teoría en cuento a la relación entre el sesgo y el posicionamiento de los estadísticos de tendencia central.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="visualización-de-datos-con-ggplot2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ChristianChiroqueR/Estadistica_AP_1_PUCP/edit/master/02-descriptivos.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ChristianChiroqueR/Estadistica_AP_1_PUCP/blob/master/02-descriptivos.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
